/**
*******************************************************************************
 @file felix_hw_info.h

 @brief Felix HW constants

 These are various magic numbers chosen for the design.
 This file is automatically generated for one specific version of the HW.

 @copyright Imagination Technologies Ltd. All Rights Reserved.

 @license Strictly Confidential.
   No part of this software, either material or conceptual may be copied or
   distributed, transmitted, transcribed, stored in a retrieval system or
   translated into any human or computer language in any form by any means,
   electronic, mechanical, manual or other-wise, or disclosed to third
   parties without the express written permission of
   Imagination Technologies Limited,
   Unit 8, HomePark Industrial Estate,
   King's Langley, Hertfordshire,
   WD4 8LZ, U.K.

******************************************************************************/
#ifndef FELIX_HW_INFO_H_
#define FELIX_HW_INFO_H_

#include "img_types.h"
/**
 * @defgroup FELIX_HW_INFO HW Information
 * @brief Information about design and registers in HW
 * @ingroup CI_API
 * @{
 */
/*-----------------------------------------------------------------------------
 * Following elements are in the FELIX_HW_INFO documentation module
 *---------------------------------------------------------------------------*/

/**
 * @name version
 * @{
 */

/** @brief core designer */
#define FELIX_DESIGNER 0u
/** @brief major */
#define FELIX_VERSION_MAJ 2u
/** @brief minor */
#define FELIX_VERSION_MIN 1u
/** @brief maintenance */
#define FELIX_VERSION_MNT 0u

/** @brief Imagination Technologies Group ID */
#define FELIX_GROUP_ID 0x17
/** @brief Felix core allocation ID */
#define FELIX_ALLOCATION_ID 0x1

/**
 * @}
 * @name Context level
 * @{
 */

/** @brief number of elements in YCC - Used in CCM, R2Y and Y2R */
#define YCC_COEFF_NO 3
/** @brief number of elements in RGB - Used in CCM, R2Y and Y2R */
#define RGB_COEFF_NO 3

/** @brief Maximum number of context the driver can handle */
#define CI_N_CONTEXT 2
/** @brief Maximum number of imager the driver can handle */
#define CI_N_IMAGERS 4
/**
 * @brief Maximum number of external data-generator that the driver can handle
 */
#define CI_N_EXT_DATAGEN 4
/**
 * @brief Maximum number of internal data-generator that the driver can handle
 */
#define CI_N_IIF_DATAGEN 1

/** @brief Minimum recommended horizontal blanking for imagers */
#define FELIX_MIN_H_BLANKING (100)
/** @brief Minimum recommended vertical blanking for imagers */
#define FELIX_MIN_V_BLANKING (14)

#define FELIX_MAX_RTM_VALUES (8)

/**
 * @brief Maximum number of frames expected per active contexts
 *
 * Can be used to define a bigger value than the linked list queue size.
 *
 * @note used only if MMU is enabled
 */
#define CI_MAX_N_BUFF 10

/**
 * @}
 * @name GMA: Gamma Look Up Table (separate register bank)
 * @{
 */

/** @brief Size of a GMA Look Up table */
#define GMA_N_POINTS  (63)

/**
 * @}
 * @name BLC: black level
 * @{
 */
/** @brief Number of entries in BLACK_FIXED_OFFSET */
#define BLC_OFFSET_NO 4

/**
 * @}
 * @name RLT information
 * @{
 */

#define RLT_SLICE_N_FIELDS (2)
#define RLT_SLICE_N_ENTRIES (8)
/** @brief Number of RLT slice value registers */
#define RLT_SLICE_N 4
/** @brief Number of points per RLT slice */
#define RLT_SLICE_N_POINTS (RLT_SLICE_N_ENTRIES*RLT_SLICE_N_FIELDS)
#define RLT_N_POINTS (RLT_SLICE_N_POINTS*RLT_SLICE_N)

/**
 * @}
 * @name LSH: lens shading
 * @{
 */

/** @brief Number of registers in lens shading table LENS_SHADING_GRADIENTS */
#define LSH_GRADS_NO 4
/**
 * @brief Minimum number of bits per difference value in lens shading grid
 * in sys.mem. (see @ref LSH_DELTA_BITS_MAX)
 */
#define LSH_DELTA_BITS_MIN 4
/**
 * @brief Maximum number of bits per difference value in lens shading grid
 * in sys.mem. (see @ref LSH_DELTA_BITS_MIN)
 */
#define LSH_DELTA_BITS_MAX 10
/**
 * @brief Minimum 2^n supported for the deshading tile size
 * (see @ref LSH_TILE_BITS_MAX)
 */
#define LSH_TILE_BITS_MIN 3
/**
 * @brief Maximum 2^n supported for the deshading tile size
 * (see @ref LSH_TILE_BITS_MIN)
 */
#define LSH_TILE_BITS_MAX 7
/** @brief Minimum tile size in CFA */
#define LSH_TILE_MIN (1 << LSH_TILE_BITS_MIN)
/** @brief Maximum tile size in CFA */
#define LSH_TILE_MAX (1 << LSH_TILE_BITS_MAX)

/** @brief Number of bytes the LSH_LINE_SIZE must be aligned to */
#define LSH_LINE_WIDTH_ALIGN

/**
 * @brief Number of fractional bits in the LSH grid vertex
 * - should use LSH_VERTEX_FRAC_PART
 */
#define LSH_VERTEX_FRAC 10
/**
 * @brief Number of integer bits in the LSH grid vertex
 * - should use LSH_VERTEX_INT_PART
 */
#define LSH_VERTEX_INT 2
/** @brief Is the LSH grid vertex signed */
#define LSH_VERTEX_SIGNED 0


/**
 * @}
 * @name DNS: Denoiser
 * @{
 */

/** 
 * @brief Number of entries in the 1st section of the LUT
 * (num entries in registers * table size)
 */
#define DNS_N_LUT0 (2*4)
/**
 * @brief Number of entries in the 2nd section of the LUT
 * (num entries in registers * table size)
 */
#define DNS_N_LUT1 (2*3)
/**
 * @brief Number of entries in the 3rd section of the LUT
 * (num entries in registers * table size)
 */
#define DNS_N_LUT2 (2*3)
/**
 * @brief Number of entries in the Look Up Table curve; +1 for the
 * extra-point used for interpolation
 */
#define DNS_N_LUT (DNS_N_LUT0+DNS_N_LUT1+DNS_N_LUT2+1)

/**
 * @}
 * @name DPF: Defective Pixel Fixing
 * @{
 */

// map information: coordinates (input & output map)
#define DPF_MAP_COORD_OFFSET (0x0)

#define DPF_MAP_COORD_X_COORD_MASK (0x00001FFF)
#define DPF_MAP_COORD_X_COORD_LSBMASK (0x00001FFF)
#define DPF_MAP_COORD_X_COORD_SHIFT (0)
#define DPF_MAP_COORD_X_COORD_LENGTH (13)
#define DPF_MAP_COORD_X_COORD_SIGNED_FIELD (IMG_FALSE)

#define DPF_MAP_COORD_Y_COORD_MASK (0x1FFF0000)
#define DPF_MAP_COORD_Y_COORD_LSBMASK (0x00001FFF)
#define DPF_MAP_COORD_Y_COORD_SHIFT (16)
#define DPF_MAP_COORD_Y_COORD_LENGTH (13)
#define DPF_MAP_COORD_Y_COORD_SIGNED_FIELD (IMG_FALSE)

// map information: data (output only)
#define DPF_MAP_DATA_OFFSET (0x4)

#define DPF_MAP_DATA_PIXEL_MASK (0x0000FFFF)
#define DPF_MAP_DATA_PIXEL_LSBMASK (0x0000FFFF)
#define DPF_MAP_DATA_PIXEL_SHIFT (0)
#define DPF_MAP_DATA_PIXEL_LENGTH (16)
#define DPF_MAP_DATA_PIXEL_SIGNED_FIELD (IMG_FALSE)

#define DPF_MAP_DATA_CONFIDENCE_MASK (0x00FF0000)
#define DPF_MAP_DATA_CONFIDENCE_LSBMASK (0x000000FF)
#define DPF_MAP_DATA_CONFIDENCE_SHIFT (16)
#define DPF_MAP_DATA_CONFIDENCE_LENGTH (7)
#define DPF_MAP_DATA_CONFIDENCE_SIGNED_FIELD (IMG_FALSE)

#define DPF_MAP_DATA_STATUS_MASK (0x80000000)
#define DPF_MAP_DATA_STATUS_LSBMASK (0x1)
#define DPF_MAP_DATA_STATUS_SHIFT (31)
#define DPF_MAP_DATA_STATUS_LENGTH (1)
#define DPF_MAP_DATA_STATUS_SIGNED_FIELD (IMG_FALSE)

/** @brief Number of lines in a DPF window - function of the parallelism */
#define DPF_WINDOW_HEIGHT(P) (10 + 2*P)
/** @brief Size in bytes per DPF input map entry */
#define DPF_MAP_INPUT_SIZE (4)
/** @brief Size in bytes per DPF output map entry */
#define DPF_MAP_OUTPUT_SIZE (8)

/** @brief Maximum number of map entries per sensor line */
#define DPF_MAP_MAX_PER_LINE (32)

/**
 * @}
 * @name LCA: lateral chromatic aberration
 * @{
 */

/**
 * @brief delta value transformed by polynomial needs to be normalised to
 * this image size
 */
#define LCA_CURVE_MAX 1024
/** @brief number of elements in the LCA red and blue coeffs tables */
#define LCA_COEFFS_NO 3

// DMO has no registers


/**
 * @}
 * @name MGM: Main Gamut Mapper
 * @{
 */

#define MGM_N_SLOPE 3
#define MGM_N_COEFF 6
/** Value range for the pixel values using in the Gammut range registers */
#define MGM_MULT 256

// GMA

// R2Y: RGB to YCC

/**
 * @}
 * @name MIE: Image Enhancer
 * @{
 */

/** @brief Number of points in the vibrancy curve */
#define MIE_VIBRANCY_N 32

#define MIE_NUM_MEMCOLOURS 3
/** @brief Number of slice per memory colour */
#define MIE_NUM_SLICES 4

/** @brief Number of elements in the Gaussian Scale curve (12) */
#define MIE_GAUSS_SC_N (MIE_NUM_MEMCOLOURS*MIE_NUM_SLICES)
/** @brief Number of elements in the Gaussian Gain curve (12) */
#define MIE_GAUSS_GN_N (MIE_NUM_MEMCOLOURS*MIE_NUM_SLICES)

#define MIE_SATMULT_NUMPOINTS_EXP 5
#define MIE_SATMULT_NUMPOINTS 32

#define MIE_GAUSS_SFT_ADDR_WIDTH 8

/**
 * @}
 * @name TNM: tone mapper
 * @{
 */

/**
 * @brief number of points in the TM global mapping curve
 * (including automatically the initial and last point)
 */
#define TNM_CURVE_NPOINTS 63
/** @brief HW needs at least 40 pixels per columns to generate histograms */
#define TNM_MIN_COL_WIDTH 40
#define TNM_MAX_COL_WIDTH 16383
/** @brief Maximum number of columns for the tone mapping */
#define TNM_MAX_COL 32

/** @brief tone mapper min output Y value (fixed for 10 bits) */
//#define TNM_OUT_MIN_Y 16
/** @brief tone mapper min output Y value (fixed for 10 bits) */
//#define TNM_OUT_MAX_Y 235
/** @brief tone mapper min output chroma value (fixed for 10 bits) */
//#define TNM_OUT_MIN_C 16
/** @brief tone mapper min output chroma value (fixed for 10 bits) */
//#define TNM_OUT_MAX_C 240


/** @brief tone mapper min output Y value (fixed for 10 bits) */
#if defined(INFOTM_SUPPORT_TNM_BIG_LUMA_AREA)
/** @brief tone mapper min output Y value (fixed for 10 bits) */
#define TNM_OUT_MIN_Y 2
/** @brief tone mapper min output Y value (fixed for 10 bits) */
#define TNM_OUT_MAX_Y 253
/** @brief tone mapper min output chroma value (fixed for 10 bits) */
#define TNM_OUT_MIN_C 2
/** @brief tone mapper min output chroma value (fixed for 10 bits) */
#define TNM_OUT_MAX_C 253
#else
#define TNM_OUT_MIN_Y 5
/** @brief tone mapper min output Y value (fixed for 10 bits) */
#define TNM_OUT_MAX_Y 250
/** @brief tone mapper min output chroma value (fixed for 10 bits) */
#define TNM_OUT_MIN_C 5
/** @brief tone mapper min output chroma value (fixed for 10 bits) */
#define TNM_OUT_MAX_C 250
#endif

/**
 * @}
 * @name SHA sharpening
 * @{
 */

#define SHA_N_WEIGHT 6
#define SHA_N_COMPARE 7

/**
 * @}
 * @name Scalers: ESC & DSC
 * @{
 */

#define SCALER_PHASES (8)
/** @brief Number of fractional bits for the taps precision */
#define SCALER_TAPS_FRAC (6)

#define ESC_H_PITCH_FRAC 15  // phase + subphase
#define ESC_H_PITCH_INT 6
#define ESC_H_PITCH_SIGNED 0

#define ESC_V_PITCH_FRAC 15  // phase + subphase
#define ESC_V_PITCH_INT 6
#define ESC_V_PITCH_SIGNED 0

/** @brief nb of horizontal filter taps for luma */
#define ESC_H_LUMA_TAPS 16
/** @brief nb of horizontal filter taps for chroma */
#define ESC_H_CHROMA_TAPS 8
/** @brief nb of vertical filter taps for luma */
#define ESC_V_LUMA_TAPS 8
/** @brief nb of vertical filter taps for chroma */
#define ESC_V_CHROMA_TAPS 4

#define DSC_H_PITCH_FRAC 15  // phase + subphase
#define DSC_H_PITCH_INT 6
#define DSC_H_PITCH_SIGNED 0

#define DSC_V_PITCH_FRAC 15  // phase + subphase
#define DSC_V_PITCH_INT 6
#define DSC_V_PITCH_SIGNED 0

/** @brief nb of horizontal filter taps for luma */
#define DSC_H_LUMA_TAPS 8
/** @brief nb of horizontal filter taps for chroma */
#define DSC_H_CHROMA_TAPS 4
/** @brief nb of vertical filter taps for luma */
#define DSC_V_LUMA_TAPS 4
/** @brief nb of vertical filter taps for chroma */
#define DSC_V_CHROMA_TAPS 2

// Y2R: YCC to RGB

/**
 * @}
 * @name DGM: Display Gamut Mapper
 * @{
 */

#define DGM_N_SLOPE 3
#define DGM_N_COEFF 6
#define DGM_MULT 256

/*
 * statistics
 */

/**
 * @}
 * @name FOS: focus statistics
 * @{
 */

/** @brief Number of horizontal tiles for the FOS statistics */
#define FOS_H_TILES 7
/** @brief Number of vertical tiles for the FOS statistics */
#define FOS_V_TILES 7

/**
 * @}
 * @name EXS: exposure clipping statistics
 * @{
 */

/** @brief Number of horizontal tiles for the EXS statistics */
#define EXS_H_TILES 7
/** @brief Number of vertical tiles for the EXS statistics */
#define EXS_V_TILES 7
/** @brief Minimum tile width in pixels */
#define EXS_MIN_WIDTH 8
/** @brief Minimum tile height in pixels */
#define EXS_MIN_HEIGHT 8


/**
 * @}
 * @name HIS: histograms statistics
 * @{
 */

#define HIS_GLOBAL_BINS 64
#define HIS_REGION_BINS 16
#define HIS_REGION_HTILES 7
#define HIS_REGION_VTILES 7
/** @brief minimum tile size in pixels */
#define HIS_MIN_TILE_WIDTH 8
/** @brief minimum tile size in pixels */
#define HIS_MIN_TILE_HEIGHT 8

/**
 * @}
 * @name WBS: White balance statistics
 * @{
 */

/** @brief Number of region of interest in the WBS */
#define WBS_NUM_ROI 2

#define WBS_USR_BITDEPTH 12
#define WBS_OFFS_WIDTH 13

/**
 * @}
 * @name ENS: Encoder Statistics
 * @{
 */

/**
 * @brief conversion helper between NCOUPLES_EXP and the number of lines in
 * a region
 *
 * (reg = log2(nlines)-ENS_EXP_ADD and vice versa in HW
 * nlines = 1<<(reg+ENS_EXP_ADD)
 */
#define ENS_EXP_ADD (1+2)
/** @brief maximum value in the register */
#define ENS_NCOUPLE_REG_MAX ((1<<3)-1)
/** @brief Minimum number of couples (before register transformation) */
#define ENS_NLINES_MIN (1 << ENS_EXP_ADD)
/** @brief Maximum number of couples (before register transformation) */
#define ENS_NLINES_MAX (1 << (ENS_NCOUPLE_REG_MAX+ENS_EXP_ADD))
/**
 * @brief Output size in bytes per region (used for computation of the size
 * of the ENS_WR_ADDR buffer)
 */
#define ENS_OUT_SIZE (8)

/*
 * ENS_NBURST = 1 << ($ENS_BURST_WIDTH - log2($DATA_WORD_WIDTH))
 * ENS_BURST_WIDTH = 9
 * DATA_WORD_WIDTH = 64
 * log2($DATA_WORD_WIDTH) = 6
 * ENS_NBURST = 8 
 */

/**
 * @}
 * @name Save structure info
 * @{
 */

/* these offsets are usable with the regio2 generated header for the
 * save structure (hw_struct/save.h) */
/** @brief Name of the first CRC "register" in the save structure */
#define SAVE_STRUCT_CRC_FIRST FELIX_SAVE_CRC_IIF_REG_OFFSET
/** @brief Name of the last CRC "register" in the save structure */
#define SAVE_STRUCT_CRC_LAST  FELIX_SAVE_CRC_RBW_RES_CONFIG_OFFSET

/**
 * @}
 * @name system memory
 * @{
 */

/* remove warning when using sim and driver headers */
#undef SYSMEM_ALIGNMENT
/**
 * @brief [bytes] data structures in system memory must be aligned to an
 * address which is a multiple of this
 */
#define SYSMEM_ALIGNMENT (64)

/**
 * @brief Value used in linked list to mean invalid address.
 *
 * Value is -1 (0xffffffff) but the bottom 6 bits are masked therefore
 * it is 0xffffffc0
 */
#define SYSMEM_INVALID_ADDR ((IMG_UINT32)0xffffffc0)

/*
 * configuration for the MEMORY_CONTROL register and other registers
 * with caching
 */
/** @brief Value for MEMORY_CONTROL:ENC_CACHE_POLICY */
#define USE_ENC_CACHE_POLICY (0)
/** @brief Value for MEMORY_CONTROL:DISP_DE_CACHE_POLICY */
#define USE_DISP_DE_CACHE_POLICY (0)
/** @brief Value for MEMORY_CONTROL:REG_CACHE_POLICY */
#define USE_REG_CACHE_POLICY (0)
/** @brief Value for MEMORY_CONTROL:LENS_CACHE_POLICY */
#define USE_LENS_CACHE_POLICY (0)
/** @brief Value for MEMORY_CONTROL:MEM_DUMP_CACHE_POLICY */
#define USE_MEM_DUMP_CACHE_POLICY (0)
/** @brief Value for MEMORY_CONTROL:ENS_CACHE_POLICY */
#define USE_ENS_CACHE_POLICY (0)
/** @brief Value for MEMORY_CONTROL:RAW_2D_CACHE_POLICY */
#define USE_RAW_2D_CACHE_POLICY (0)
/** @brief Value for MEMORY_CONTROL:HDF_RD_CACHE_POLICY */
#define USE_HDF_RD_CACHE_POLICY (0)
/** @brief Value for MEMORY_CONTROL:DPF_READ_CACHE_POLICY */
#define USE_DPF_READ_CACHE_POLICY (0)
/** @brief Value for MEMORY_CONTROL:DPF_WRITE_CACHE_POLICY */
#define USE_DPF_WRITE_CACHE_POLICY (0)
/** @brief Value for MEMORY_CONTROL:HDF_WR_CACHE_POLICY */
#define USE_HDF_WR_CACHE_POLICY (0)

/** @brief Value for MEMORY_CONTROL2:ENC_FORCE_FENCE */
#define USE_ENC_FORCE_FENCE (0)
/** @brief Value for MEMORY_CONTROL2:DISP_DE_FORCE_FENCE */
#define USE_DISP_DE_FORCE_FENCE (0)
/** @brief Value for MEMORY_CONTROL2:HDF_WR_FORCE_FENCE */
#define USE_HDF_WR_FORCE_FENCE (0)
/** @brief Value for MEMORY_CONTROL2:RAW_2D_FORCE_FENCE */
#define USE_RAW_2D_FORCE_FENCE (0)
/** @brief Value for MEMORY_CONTROL2:MEM_DUMP_REMOVE_FENCE */
#define USE_MEM_DUMP_REMOVE_FENCE (1)
/** @brief Value for MEMORY_CONTROL2:ENC_L_REMOVE_FENCE */
#define USE_ENC_L_REMOVE_FENCE (1)
/** @brief Value for MEMORY_CONTROL2:DISP_DE_REMOVE_FENCE */
#define USE_DISP_DE_REMOVE_FENCE (1)
/** @brief Value for MEMORY_CONTROL2:OTHERS_REMOVE_FENCE */
#define USE_OTHERS_REMOVE_FENCE (1)
/** @brief Value for MEMORY_CONTROL2:HDF_WR_REMOVE_FENCE */
#define USE_HDF_WR_REMOVE_FENCE (1)
/** @brief Value for MEMORY_CONTROL2:RAW_2D_REMOVE_FENCE */
#define USE_RAW_2D_REMOVE_FENCE (1)

// defined in regsiters/data_generator.h
#define USE_DG_IFF_CACHE_POLICY \
    (FELIX_DG_IIF_DG_CTRL_DG_IIF_CACHE_POLICY_DEFAULT)

/**
 * @}
 */
/**
 * @}
 */
/*-----------------------------------------------------------------------------
 * End of the FELIX_HW_INFO documentation module
 *---------------------------------------------------------------------------*/

#endif /* FELIX_HW_INFO_H_ */
