#! /bin/sh

case "$1" in
	start|"")
		modprobe Felix
		modprobe ddk_sensor i2c_addr=0x6c mipi=1 lanes=1 i2c_chn=0x03
		modprobe hx280enc_h1
		videoboxd
		;;
	stop)
		killall videoboxd
		;;
	*)
		echo "Usage: videobox {start|stop}" >&2
		exit 1
		;;
esac

