obj-y += board.o
obj-y += board_x15_mid_i80.o
obj-y += board_x15_mid_lcd1.o
obj-y += board_box_lcd1.o

EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/common
EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/implementation

