/**
******************************************************************************
@file   /home/jenkins/builds/workspace/ISP_PKG/build/CI/felix/regdefs2.7/regdefs//registers/fields_gasket_mipi.h

@brief  FIELDS_GASKET_MIPI_H registers and fields property array (name, offset, etc)

@author <Autogenerated>
		<b>Copyright 2005 by Imagination Technologies Limited.</b>
		All rights reserved.  No part of this software, either
		material or conceptual may be copied or distributed,
		transmitted, transcribed, stored in a retrieval system
		or translated into any human or computer language in any
		form by any means, electronic, mechanical, manual or
		other-wise, or disclosed to third parties without the
		express written permission of Imagination Technologies
		Limited, Unit 8, HomePark Industrial Estate,
		King's Langley, Hertfordshire, WD4 8LZ, U.K.


<b>Description:</b>
		Defines the FieldDefnListEl structure if not already defined (FIELD_DEFN_LIST_EL).


		Defines an array of FieldDefnListEl that contains all registers and fields information (non-sorted).
<b>Platform:</b> ?
@Version 1.0

******************************************************************************/

#if !defined (__FIELDS_GASKET_MIPI_H__)
#define __FIELDS_GASKET_MIPI_H__

#ifdef __cplusplus
extern "C" {
#endif

#ifndef FIELD_DEFN_LIST_EL
#define FIELD_DEFN_LIST_EL
/** @brief Register information structure */
typedef struct _FieldDefnListEl
{
	const IMG_CHAR*		szRegName; /**< @brief Register's name */
	const IMG_CHAR*		szFieldName; /**< @brief Field's name */
	IMG_UINT32		ui32RegOffset; /**< @brief Register's offset in Bytes in the register bank */
	IMG_UINT32		ui32FieldStart; /**< @brief Field's starting offset in bits (from ui32RegOffset) */
	IMG_UINT32		ui32FieldEnd; /**< @brief Field's ending offset in bits (from ui32RegOffset) */
	IMG_UINT32		ui32FieldDefault; /**< @brief Field's default value */
} FieldDefnListEl;
#endif // FIELD_DEFN_LIST_EL


#define FELIX_GAS_MIPI_FIELDS FieldDefnListEl felix_gas_mipi_fields[] = {\
	{"GPIO_IN", "GPIO_IN", 0x00000000, 0, 15, 0x0},\
	{"GPIO_OUT", "GPIO_OUT", 0x00000004, 0, 7, 0x0},\
	{"GASKET_INTER_ENABLE", "GPIO_IN_WRITE_EN", 0x00000008, 3, 3, 0x0},\
	{"GASKET_INTER_ENABLE", "IMGR_MIPI_HS_SOT_SYNC_ERROR_EN", 0x00000008, 2, 2, 0x0},\
	{"GASKET_INTER_ENABLE", "IMGR_MIPI_HS_SOT_ERROR_EN", 0x00000008, 1, 1, 0x0},\
	{"GASKET_INTER_ENABLE", "IMGR_MIPI_ESC_ULP_EN", 0x00000008, 0, 0, 0x0},\
	{"GASKET_INTER_CLEAR", "GPIO_IN_WRITE_CLR", 0x0000000C, 3, 3, 0x0},\
	{"GASKET_INTER_CLEAR", "IMGR_MIPI_HS_SOT_SYNC_ERROR_CLR", 0x0000000C, 2, 2, 0x0},\
	{"GASKET_INTER_CLEAR", "IMGR_MIPI_HS_SOT_ERROR_CLR", 0x0000000C, 1, 1, 0x0},\
	{"GASKET_INTER_CLEAR", "IMGR_MIPI_ESC_ULP_CLR", 0x0000000C, 0, 0, 0x0},\
	{"GASKET_INTER_STATUS", "GPIO_IN_WRITE", 0x00000010, 9, 9, 0x0},\
	{"GASKET_INTER_STATUS", "IMGR_MIPI_HS_SOT_SYNC_ERROR", 0x00000010, 5, 8, 0x0},\
	{"GASKET_INTER_STATUS", "IMGR_MIPI_HS_SOT_ERROR", 0x00000010, 1, 4, 0x0},\
	{"GASKET_INTER_STATUS", "IMGR_MIPI_ESC_ULP", 0x00000010, 0, 0, 0x0},\
	{"GASKET_CONTROL", "GASKET_CLEAR_FIFO_FLAG", 0x00000014, 3, 3, 0x0},\
	{"GASKET_CONTROL", "GASKET_RESET", 0x00000014, 2, 2, 0x0},\
	{"GASKET_CONTROL", "GASKET_CLEAR_CNT", 0x00000014, 1, 1, 0x0},\
	{"GASKET_CONTROL", "GASKET_ENABLE", 0x00000014, 0, 0, 0x0},\
	{"GASKET_MIPI_STATUS", "MIPI_ECC_CORRECTED_CNT", 0x00000060, 24, 31, 0x0},\
	{"GASKET_MIPI_STATUS", "MIPI_ECC_ERROR_CNT", 0x00000060, 16, 23, 0x0},\
	{"GASKET_MIPI_STATUS", "MIPI_HDR_ERROR_CNT", 0x00000060, 8, 15, 0x0},\
	{"GASKET_MIPI_STATUS", "MIPI_CRC_ERROR_CNT", 0x00000060, 0, 7, 0x0},\
	{"GASKET_MIPI_STATUS2", "MIPI_FIFO_FULL", 0x00000064, 3, 3, 0x0},\
	{"GASKET_MIPI_STATUS2", "MIPI_ENABLE_LANE", 0x00000064, 0, 2, 0x0},\
	{"GASKET_MIPI_STATUS3", "MIPI_SOT_ERROR_CNT", 0x00000068, 0, 15, 0x0},\
	{"GASKET_FRAME_CNT", "GASKET_FRAME_CNT", 0x00000080, 0, 31, 0x0},\
	{"GASKET_CRC", "GASKET_CRC", 0x00000100, 0, 31, 0x0},\
};

#define FELIX_GAS_MIPI_ADD_FIELD_DEFNS(DefnSet, Memspace, MemspaceID) \
	{ \
		int i; \
		FELIX_GAS_MIPI_FIELDS; \
		for (i = 0; i < (sizeof(felix_gas_mipi_fields)/sizeof(*felix_gas_mipi_fields)); i++) \
		{ \
			addFieldDefn(DefnSet, Memspace, MemspaceID, \
				felix_gas_mipi_fields[i].szRegName, \
				felix_gas_mipi_fields[i].szFieldName, \
				felix_gas_mipi_fields[i].ui32RegOffset, \
				felix_gas_mipi_fields[i].ui32FieldStart, \
				felix_gas_mipi_fields[i].ui32FieldEnd, \
				felix_gas_mipi_fields[i].ui32FieldDefault); \
		} \
	}




#ifdef __cplusplus
}
#endif

#endif /* __FIELDS_GASKET_MIPI_H__ */
