/**
******************************************************************************
@file   /home/jenkins/builds/workspace/ISP_PKG/build/CI/felix/regdefs2.7/regdefs//registers/fields_ext_phy.h

@brief  FIELDS_EXT_PHY_H registers and fields property array (name, offset, etc)

@author <Autogenerated>
		<b>Copyright 2005 by Imagination Technologies Limited.</b>
		All rights reserved.  No part of this software, either
		material or conceptual may be copied or distributed,
		transmitted, transcribed, stored in a retrieval system
		or translated into any human or computer language in any
		form by any means, electronic, mechanical, manual or
		other-wise, or disclosed to third parties without the
		express written permission of Imagination Technologies
		Limited, Unit 8, HomePark Industrial Estate,
		King's Langley, Hertfordshire, WD4 8LZ, U.K.


<b>Description:</b>
		Defines the FieldDefnListEl structure if not already defined (FIELD_DEFN_LIST_EL).


		Defines an array of FieldDefnListEl that contains all registers and fields information (non-sorted).
<b>Platform:</b> ?
@Version 1.0

******************************************************************************/

#if !defined (__FIELDS_EXT_PHY_H__)
#define __FIELDS_EXT_PHY_H__

#ifdef __cplusplus
extern "C" {
#endif

#ifndef FIELD_DEFN_LIST_EL
#define FIELD_DEFN_LIST_EL
/** @brief Register information structure */
typedef struct _FieldDefnListEl
{
	const IMG_CHAR*		szRegName; /**< @brief Register's name */
	const IMG_CHAR*		szFieldName; /**< @brief Field's name */
	IMG_UINT32		ui32RegOffset; /**< @brief Register's offset in Bytes in the register bank */
	IMG_UINT32		ui32FieldStart; /**< @brief Field's starting offset in bits (from ui32RegOffset) */
	IMG_UINT32		ui32FieldEnd; /**< @brief Field's ending offset in bits (from ui32RegOffset) */
	IMG_UINT32		ui32FieldDefault; /**< @brief Field's default value */
} FieldDefnListEl;
#endif // FIELD_DEFN_LIST_EL


#define FELIX_GASK_PHY_FIELDS FieldDefnListEl felix_gask_phy_fields[] = {\
	{"DG_STATUS", "RESERVED", 0x00000000, 0, 31, 0x0},\
	{"DG_REF_CLK_SET", "DG_REF_CLK_SET", 0x00000004, 0, 0, 0x1},\
	{"DG_PIXEL_RATE", "DG_PIXEL_CLK_DIV", 0x00000008, 16, 23, 0x0},\
	{"DG_PIXEL_RATE", "DG_PIXEL_CLK_MULT", 0x00000008, 0, 6, 0x0},\
	{"MIPI_DPHY_CTRL", "MIPI_ENABLE_LANE", 0x0000000C, 0, 2, 0x0},\
	{"MIPI_DPHY_RESET", "SOFT_RESET", 0x00000010, 0, 0, 0x0},\
	{"SENSOR_RESETN", "SENSOR_RESETN", 0x00000014, 0, 0, 0x1},\
	{"SENSOR_SELECT", "SENSOR_SELECT", 0x00000018, 0, 1, 0x0},\
	{"PLL_UPDATE_DISABLED", "DISABLE_PLL_UPDATE", 0x0000001C, 0, 0, 0x0},\
	{"MIPI_ECC_ERROR_CNT", "MIPI_ECC_ERROR_CNT", 0x00000020, 0, 31, 0x0},\
	{"MIPI_ECC_CORRECT_CNT", "MIPI_ECC_CORRECT_CNT", 0x00000024, 0, 31, 0x0},\
	{"RTM_EXT_MUX", "RTM_EXT_MUX", 0x00000080, 0, 31, 0x0},\
	{"RTM_EXT", "RTM_EXT", 0x00000084, 0, 31, 0x0},\
};

#define FELIX_GASK_PHY_ADD_FIELD_DEFNS(DefnSet, Memspace, MemspaceID) \
	{ \
		int i; \
		FELIX_GASK_PHY_FIELDS; \
		for (i = 0; i < (sizeof(felix_gask_phy_fields)/sizeof(*felix_gask_phy_fields)); i++) \
		{ \
			addFieldDefn(DefnSet, Memspace, MemspaceID, \
				felix_gask_phy_fields[i].szRegName, \
				felix_gask_phy_fields[i].szFieldName, \
				felix_gask_phy_fields[i].ui32RegOffset, \
				felix_gask_phy_fields[i].ui32FieldStart, \
				felix_gask_phy_fields[i].ui32FieldEnd, \
				felix_gask_phy_fields[i].ui32FieldDefault); \
		} \
	}




#ifdef __cplusplus
}
#endif

#endif /* __FIELDS_EXT_PHY_H__ */
