#include "spv_language_res.h"


const char *language_en[] = {
	"On",
	"Off",
	"Auto",
	"Ok",
	"Cancel",
	"1s",
	"2s",
	"3s",
	"5s",
	"10s",
	"15s",
	"20s",
	"30s",
	"1 Minute",
	"3 Minutes",
	"5 Minutes",
	"10 Minutes",
	//video setting
	"Video Resolution",
	"2448x2448 30fps",
	"1920x1080 60fps",
	"1920x1080 30fps",
	"1280x720 30fps",
	"3264x3264",
	"2880x2880",
	"2048x2048",
	"1920x1920",
	"1472x1472",
	"1088x1088",
	"768x768",
	"Video Record Mode",
	"Video Preview Mode",
	"360 Panorama Round",
	"360 Panorama Expand",
	"Two Segment",
	"Three Segment",
	"Four Segment",
	"Round",
	"VR",
	"Loop Recording",
	"Video Timelapsed Image",
	"Video High Speed",
	"WDR",
	"EV Compensation",
	"+2.0",
	"+1.5",
	"+1.0",
	"+0.5",
	"0",
	"-0.5",
	"-1.0",
	"-1.5",
	"-2.0",
	"Date Stamp",
	"Restore Default",
	"Restore to default?",
	"Reset",
	"Record Audio",
	//photo Setting
	"Photo Resolution",
	"16M(4096x4096)",
	"10M(3264x3264)",
	"8M(2880x2880)",
	"5M(3040x1520)",
	"4M(2448x2448)",
	"Photo Capture Mode",
	"Photo Preview Mode",
	"Capture By Timer",
	"Loop Capture",
	"Capture Sequence",
	"3P/S",
	"5P/S",
	"7P/S",
	"10P/S",
	"Photo Quality",
	"Fine",
	"Normal",
	"Economy",
	"Sharpness",
	"Strong",
	"Soft",
	"White Balance",
	"Daylight",
	"Cloudy",
	"Tungsten",
	"Fluorescent",
	"Color",
	"Black & White",
	"Sepia",
	"ISO Limit",
	"800",
	"400",
	"200",
	"100",
	"Anti Shaking",
	//general settting
	"Language",
	"Englist",
	"简体中文",
	"繁體中文",
	"Français",
	"Español",
	"Italiano",
	"Português",
	"Deutsch",
	"Русский",
	"한국어",
	"にほんご ",
	"Wifi Mode",
	"Wifi Direct",
	"Wifi Router",
	"Led Frequence",
	"50HZ",
	"60HZ",
	"LED",
	"Car DV",
	"Parking Guard",
	"Gsensor",
	"Image Rotation",
	"Date Setting",
	"Date:",
	"Time:",
	"AM",
	"PM",
	"Volume",
	"10%",
	"20%",
	"30%",
	"40%",
	"50%",
	"60%",
	"70%",
	"80%",
	"90%",
	"100%",
	"Key Tone",
    "Display brightness",
    "High",
    "Medium",
    "Low",
	"Auto Sleep",
	"Auto Power Off",
	"Delayed Shutdown",
	"Format",
	"Format SD card?",
	"Reset Camera?",
	"Reset camera to default?",
	"Version",
	"Product:",
	"Software:",
	"UpdateTime:",
	"Inc:",
	"Formatting...",
	"Format error",
	"SD card is empty",
	"SD card is full",
	"Undetect SD Card",
	"SD card error",
	"SD card error, Formate it",
	"Preparing SD card",
	"WIFI connecting...",
	"WIFI off",
	"GOODBYE!",
	"Camera Busy",
	"Low Power, Please Charge",
};

const char *language_zh[] = {
	"开",
	"关",
	"自动",
	"确认",
	"取消",
	"1s",
	"2s",
	"3s",
	"5s",
	"10s",
	"15s",
	"20s",
	"30s",
	"1分钟",
	"3分钟",
	"5分钟",
	"10分钟",
	//video setting
	"视频分辨率",
	"2448x2448 30fps",
	"1920x1080 60fps",
	"1920x1080 30fps",
	"1280x720 30fps",
	"3264x3264",
	"2880x2880",
	"2048x2048",
	"1920x1920",
	"1472x1472",
	"1088x1088",
	"768x768",
	"视频拍摄模式",
	"视频预览模式",
	"360全景圆形",
	"360全景展开",
	"二分割",
	"三分割",
	"四分割",
	"圆环",
	"VR",
	"循环录影",
	"缩时录影",
	"高速摄影",
	"WDR",
	"曝光补偿EV",
	"2.0",
	"1.5",
	"1.0",
	"0.5",
	"0",
	"-0.5",
	"-1.0",
	"-1.5",
	"-2.0",
	"时间标签",
	"恢复默认",
	"恢复默认设置?",
	"重置",
	"录音",
	//photo setting
	"图像解析度",
	"16M(4096x4096)",
	"10M(3264x3264)",
	"8M(2880x2880)",
	"5M(3040x1520)",
	"4M(2448x2448)",
	"拍照模式",
	"图片预览模式",
	"定时拍照",
	"自动拍照",
	"连拍",
	"3P/S",
	"5P/S",
	"7P/S",
	"10P/S",
	"图像质量",
	"好",
	"一般",
	"经济",
	"锐度",
	"强烈",
	"柔和",
	"白平衡WB",
	"日光",
	"阴天",
	"钨丝灯",
	"荧光灯",
	"色彩",
	"黑白",
	"棕褐色",
	"ISO限制",
	"800",
	"400",
	"200",
	"100",
	"防抖动",
	//general setting
	"语言",
	"Englist",
	"简体中文",
	"繁體中文",
	"Français",
	"Español",
	"Italiano",
	"Português",
	"Deutsch",
	"Русский",
	"한국어",
	"にほんご ",
	"无线模式",
	"WIFI直连",
	"WIFI路由",
	"光源频率",
	"50HZ",
	"60HZ",
	"LED灯",
	"车载模式",
	"停车守卫",
	"重力感应",
	"影像倒置",
	"时间日期设置",
	"日期:",
	"时间:",
	"AM",
	"PM",
	"音量",
	"10%",
	"20%",
	"30%",
	"40%",
	"50%",
	"60%",
	"70%",
	"80%",
	"90%",
	"100%",
	"按键声音",
    "显示亮度",
    "高",
    "中",
    "低",
	"自动屏保",
	"自动关机",
	"延时关机",
	"格式化",
	"是否格式化存储卡?",
	"相机重置",
	"是否重置相机?",
	"版本",
	"型号:",
	"软件版本:",
	"更新时间:",
	"厂商:",
	//sd toast
	"正在格式化...",
	"格式化出错",
	"存储卡为空",
	"存储卡已满",
	"未检测到存储卡",
	"存储卡错误",
	"存储卡错误,格式化",
	"存储卡准备中",
	"WIFI 配置中...",
	"WIFI 已关闭",
	"再见",
	"相机忙",
	"电池电量低",
};

const char *language_tw[] = {
	"開",
	"關",
	"自動",
	"確認",
	"取消",
	"1秒",
	"2秒",
	"3秒",
	"5秒",
	"10秒",
	"15秒",
	"20秒",
	"30秒",
	"1分鐘",
	"3分鐘",
	"5分鐘",
	"10分鐘",
	"視頻分辨率",
	"2448x2448 30fps",
	"1920x1080 60fps",
	"1920x1080 30fps",
	"1280x720 30fps",
	"3264x3264",
	"2880x2880",
	"2048x2048",
	"1920x1920",
	"1472x1472",
	"1088x1088",
	"768x768",
	"視頻拍攝模式",
	"視頻預覽模式",
	"360全景圓形",
	"360全景展開",
	"二分割",
	"三分割",
	"四分割",
	"圓環",
	"VR",
	"循環錄影",
	"縮時錄影",
	"高速攝影",
	"WDR",
	"曝光補償EV",
	"+2",
	"+1.5",
	"+1",
	"+0.5",
	"0",
	"-0.5",
	"-1",
	"-1.5",
	"-2",
	"時間標籤",
	"恢復默認",
	"恢復默認設置?",
	"重置",
	"錄音",
	"圖像解析度",
	"16M(4096x4096)",
	"10M(3264x3264)",
	"8M(2880x2880)",
	"5M(3040x1520)",
	"4M(2448x2448)",
	"拍照模式",
	"圖片預覽模式",
	"定時拍照",
	"自動拍照",
	"連拍",
	"3P/S",
	"5P/S",
	"7P/S",
	"10P/S",
	"圖像質量",
	"好",
	"一般",
	"經濟",
	"銳度",
	"強烈",
	"柔和",
	"白平衡WB",
	"日光",
	"陰天",
	"鎢絲燈",
	"熒光燈",
	"色彩",
	"黑白",
	"棕褐色",
	"ISO限制",
	"800",
	"400",
	"200",
	"100",
	"防抖動",
	"語言",
	"Englist",
	"简体中文",
	"繁體中文",
	"Français",
	"Español",
	"Italiano",
	"Português",
	"Deutsch",
	"Русский",
	"한국어",
	"にほんご ",
	"無線模式",
	"WIFI直連",
	"WIFI路由",
	"光源頻率",
	"50HZ",
	"60HZ",
	"LED燈",
	"車載模式",
	"停車守衛",
	"重力感應",
	"影像倒置",
	"時間日期設置",
	"日期:",
	"時間:",
	"AM",
	"PM",
	"音量",
	"10%",
	"20%",
	"30%",
	"40%",
	"50%",
	"60%",
	"70%",
	"80%",
	"90%",
	"100%",
	"按鍵聲音",
	"顯示亮度",
	"高",
	"中",
	"低",
	"自動屏保",
	"自動關機",
	"延時關機",
	"格式化",
	"是否格式化存儲卡?",
	"相機重置",
	"是否重置相機?",
	"版本",
	"型號:",
	"軟件版本:",
	"更新時間:",
	"廠商:",
	"正在格式化...",
	"格式化出錯",
	"存儲卡為空",
	"存儲卡已滿",
	"未檢測到存儲卡",
	"存儲卡錯誤",
	"存儲卡錯誤,格式化",
	"存儲卡準備中",
	"WIFI 配置中...",
	"WIFI 已關閉",
	"再見",
	"相機忙",
	"電池電量低",
};

const char *language_fr[] = {
	"ouvert",
	"proche",
	"automatique",
	"confirmer",
	"annulé",
	"1 secondes",
	"2 secondes",
	"3 secondes",
	"5 secondes",
	"10 secondes",
	"15 secondes",
	"20 secondes",
	"30 secondes",
	"1 minutes",
	"3 minutes",
	"5 minutes",
	"10 minutes",
	"Résolution vidéo",
	"2448x2448 30fps",
	"1920x1080 60fps",
	"1920x1080 30fps",
	"1280x720 30fps",
	"3264x3264",
	"2880x2880",
	"2048x2048",
	"1920x1920",
	"1472x1472",
	"1088x1088",
	"768x768",
	"mode de capture vidéo",
	"Mode vidéo Aperçu",
	"360 Panorama Round",
	"360 Panorama Agrandir",
	"Deux scission",
	"Divisé en trois morceaux",
	"quadrilatère",
	"anneau",
	"VR",
	"enregistrement en boucle",
	"Shrink pendant l'enregistrement",
	"la photographie à haute vitesse",
	"WDR",
	"Compensation de l'exposition EV",
	"+2",
	"+1.5",
	"+1",
	"+0.5",
	"0",
	"-0.5",
	"-1",
	"-1.5",
	"-2",
	"étiquette Temps",
	"Restore Default",
	"Restaurer les paramètres par défaut?",
	"remettre",
	"enregistrement",
	"Résolution de l'image",
	"16M (4096x4096)",
	"10M (3264x3264)",
	"8M (2880x2880)",
	"5M (3040x1520)",
	"4M (2448x2448)",
	"Mode caméra",
	"mode de prévisualisation de l'image",
	"Temps de prendre des photos",
	"appareil photo automatique",
	"éclater",
	"3 P/S",
	"5 P/S",
	"7 P/S",
	"10 P/S",
	"qualité d'image",
	"bon",
	"général",
	"économie",
	"acuité",
	"fort",
	"doux",
	"WB WB",
	"lumière du soleil",
	"jour nuageux",
	"tungstène",
	"fluorescent",
	"couleur",
	"Noir et blanc",
	"brun",
	"limite ISO",
	"800",
	"400",
	"200",
	"100",
	"stabiliser",
	"langue",
	"Englist",
	"简体中文",
	"繁體中文",
	"Français",
	"Español",
	"Italiano",
	"Português",
	"Deutsch",
	"Русский",
	"한국어",
	"にほんご ",
	"mode sans fil",
	"WIFI Direct Connect",
	"routage WIFI",
	"La fréquence de la source lumineuse",
	"50HZ",
	"60HZ",
	"lumières LED",
	"Mode voiture",
	"gardiens de parking",
	"Capteur de gravité",
	"Image inversée",
	"Paramètres heure et date",
	"Date:",
	"Durée:",
	"AM",
	"PM",
	"volume",
	"10%",
	"20%",
	"30%",
	"40%",
	"50%",
	"60%",
	"70%",
	"80%",
	"90%",
	"100%",
	"bip",
	"luminosité",
	"haut",
	"dans",
	"faible",
	"automatique d'écran",
	"arrêt automatique",
	"arrêt différé",
	"format",
	"Format carte?",
	"Réinitialiser l'appareil",
	"Que ce soit pour réinitialiser l'appareil photo aux valeurs par défaut?",
	"libération",
	"Type de produit:",
	"Version du logiciel:",
	"Mise à jour:",
	"Fabricant:",
	"Formatage ...",
	"Erreur de format",
	"La carte mémoire est vide",
	"La carte mémoire est pleine",
	"La carte mémoire est non détectée",
	"Erreur de carte mémoire",
	"Erreur de carte mémoire, le formatage",
	"Préparation de la carte mémoire",
	"configuration WIFI ...",
	"WIFI fermé",
	"au revoir",
	"Caméra occupée",
	"Batterie faible, s'il vous plat charger",
};

const char *language_es[] = {
	"abierto",
	"cerca",
	"automático",
	"confirmar",
	"cancelado",
	"1 segundos",
	"2 segundos",
	"3 segundos",
	"5 segundos",
	"10 segundos",
	"15 segundos",
	"20 segundos",
	"30 segundos",
	"1 minutos",
	"3 minutos",
	"5 minutos",
	"10 minutos",
	"Resolución de vídeo",
	"2448x2448 30fps",
	"1920x1080 60fps",
	"1920x1080 30fps",
	"1280x720 30fps",
	"3264x3264",
	"2880x2880",
	"2048x2048",
	"1920x1920",
	"1472x1472",
	"1088x1088",
	"768x768",
	"el modo de captura de vídeo",
	"Modo de vista previa de vídeo",
	"360 Panorama Ronda",
	"360 Panorama Expand",
	"dos dividida",
	"Dividido en tres piezas",
	"patio",
	"anillo",
	"VR",
	"grabación en bucle",
	"Shrink durante la grabación",
	"Fotografía de alta velocidad",
	"WDR",
	"Compensación de la exposición EV",
	"+2",
	"+1.5",
	"+1",
	"+0.5",
	"0",
	"-0.5",
	"-1,0",
	"-1.5",
	"-2",
	"sello de tiempo",
	"restaurar valores predeterminados",
	"Restaurar la configuración predeterminada?",
	"reajustar",
	"grabación",
	"resolución de la imagen",
	"16M (4096x4096)",
	"10M (3264x3264)",
	"8M (2880x2880)",
	"5M (3040x1520)",
	"4M (2448x2448)",
	"el modo de cámara",
	"el modo de previsualización de la imagen",
	"Tiempo de la toma de fotografías",
	"cámara automática",
	"Burst",
	"3 P/S",
	"5 P/S",
	"7 P/S",
	"10 P/S",
	"Calidad de imagen",
	"bueno",
	"general",
	"economía",
	"nitidez",
	"fuerte",
	"suave",
	"WB WB",
	"luz del sol",
	"día nublado",
	"tungsteno",
	"fluorescente",
	"color",
	"en blanco y negro",
	"marrón",
	"límite de la norma ISO",
	"800",
	"400",
	"200",
	"100",
	"estabilizar",
	"idioma",
	"Englist",
	"简体中文",
	"繁體中文",
	"Français",
	"Español",
	"Italiano",
	"Português",
	"Deutsch",
	"Русский",
	"한국어",
	"にほんご ",
	"Modo inalámbrico",
	"WIFI Direct Connect",
	"enrutamiento WIFI",
	"La frecuencia de la fuente de luz",
	"50 HZ",
	"60 HZ",
	"Las luces LED",
	"Modo vehículo",
	"guardias de aparcamiento",
	"sensor de gravedad",
	"imagen invertida",
	"Configuraciones de hora y fecha",
	"fecha:",
	"tiempo:",
	"AM",
	"primer ministro",
	"volumen",
	"10%",
	"20%",
	"30%",
	"40%",
	"50%",
	"60%",
	"70%",
	"80%",
	"90%",
	"100%",
	"bip",
	"brillo de la pantalla",
	"alto",
	"en",
	"bajo",
	"Salvapantallas automática",
	"apagado automático",
	"apagado retardado",
	"formato",
	"tarjeta de formato?",
	"Restablecer cámara",
	"Ya sea para restablecer la cámara a los valores predeterminados?",
	"liberación",
	"Tipo de producto:",
	"Versión de software:",
	"actualizado:",
	"fabricante:",
	"Formato ...",
	"error de formato",
	"La tarjeta de memoria está vacía",
	"La tarjeta de memoria está llena",
	"No se detecta la tarjeta de memoria",
	"error en la tarjeta de memoria",
	"error en la tarjeta de memoria, formatear",
	"preparación de tarjeta de memoria",
	"configuración WIFI ...",
	"WIFI cerrada",
	"adiós",
	"cámara ocupada",
	"Batería baja, cargue",
};

const char *language_it[] = {
	"aperto",
	"vicino",
	"automatico",
	"confermare",
	"annullato",
	"1 secondi",
	"2 secondi",
	"3 secondi",
	"5 secondi",
	"10 secondi",
	"15 secondi",
	"20 secondi",
	"30 secondi",
	"1 minuti",
	"3 minuti",
	"5 minuti",
	"10 minuti",
	"Risoluzione video",
	"2448x2448 30fps",
	"1920x1080 60fps",
	"1920x1080 30fps",
	"1280x720 30fps",
	"3264x3264",
	"2880x2880",
	"2048x2048",
	"1920x1920",
	"1472x1472",
	"1088x1088",
	"768x768",
	"modalità di cattura video",
	"modalità Video Preview",
	"360 Panorama rotonda",
	"360 Panorama Expand",
	"due spaccatura",
	"Diviso in tre pezzi",
	"quadrilatero",
	"anello",
	"VR",
	"registrazione loop",
	"Shrink durante la registrazione",
	"fotografia ad alta velocità",
	"WDR",
	"Compensazione dell'esposizione EV",
	"+2.0",
	"+1.5",
	"+1",
	"+0.5",
	"0",
	"-0.5",
	"-1",
	"-1.5",
	"-2",
	"etichetta tempo",
	"Ripristina impostazioni predefinite",
	"Ripristinare le impostazioni predefinite?",
	"reset",
	"registrazione",
	"La risoluzione dell'immagine",
	"16M (4096x4096)",
	"10M (3264x3264)",
	"8M (2880x2880)",
	"5M (3040x1520)",
	"4M (2448x2448)",
	"modalità fotocamera",
	"modalità di anteprima Immagine",
	"immagini tempo prendendo",
	"macchina fotografica automatica",
	"scoppiare",
	"3 P/S",
	"5 P/S",
	"7 P/S",
	"10 P/S",
	"Qualità dell'immagine",
	"buono",
	"generale",
	"economia",
	"nitidezza",
	"forte",
	"dolce",
	"WB WB",
	"luce del sole",
	"giorno nuvoloso",
	"tungsteno",
	"fluorescente",
	"colore",
	"In bianco e nero",
	"marrone",
	"limite ISO",
	"800",
	"400",
	"200",
	"100",
	"stabilizzare",
	"lingua",
	"Englist",
	"简体中文",
	"繁體中文",
	"Français",
	"Español",
	"Italiano",
	"Português",
	"Deutsch",
	"Русский",
	"한국어",
	"にほんご ",
	"Modalità wireless",
	"WIFI Direct Connect",
	"WIFI instradamento",
	"La frequenza della sorgente luminosa",
	"50 HZ",
	"60 HZ",
	"luci a LED",
	"Modalità auto",
	"guardie Parcheggio",
	"sensore di gravità",
	"immagine invertita",
	"Impostazioni di data e",
	"data:",
	"tempo:",
	"AM",
	"PM",
	"volume",
	"10%",
	"20%",
	"30%",
	"40%",
	"50%",
	"60%",
	"70%",
	"80%",
	"90%",
	"100%",
	"bip",
	"luminosità schermo",
	"alto",
	"in",
	"basso",
	"Screensaver automatica",
	"spegnimento automatico",
	"spegnimento ritardato",
	"formato",
	"carta di formato?",
	"ripristino Camera",
	"Sia per ripristinare la fotocamera a valori di default?",
	"rilascio",
	"Tipo di prodotto:",
	"Versione Software:",
	"aggiornamento:",
	"Produttore:",
	"Formattazione ...",
	"errore formattazione",
	"La scheda di memoria è vuota",
	"La scheda di memoria è piena",
	"La scheda di memoria non viene rilevata",
	"Errore memory card",
	"Errore memory card, la formattazione",
	"Preparazione della scheda di memoria",
	"Configurazione Wi-Fi ...",
	"WIFI chiusa",
	"addio",
	"Camera occupato",
	"Batteria scarica, si prega di carica",
};

const char *language_pt[] = {
	"aberto",
	"perto",
	"automático",
	"confirmar",
	"cancelado",
	"1 segundos",
	"2 segundo",
	"3 segundo",
	"5 segundos",
	"10 segundos",
	"15 segundos",
	"20 segundos",
	"30 segundos",
	"1 minutos",
	"3 minutos,",
	"5 minutos",
	"10 minutos",
	"resolução de vídeo",
	"2448x2448 30fps",
	"1920x1080 60fps",
	"1920x1080 30fps",
	"1280x720 30fps",
	"3264x3264",
	"2880x2880",
	"2048x2048",
	"1920x1920",
	"1472x1472",
	"1088x1088",
	"768x768",
	"modo de captura de vídeo",
	"Modo Video Preview",
	"360 Panorama Rodada",
	"360 Panorama Expandir",
	"dois divisão",
	"Dividido em três partes",
	"quadrângulo",
	"anel",
	"VR",
	"gravação em loop",
	"Encolher durante a gravação",
	"fotografia de alta velocidade",
	"WDR",
	"Compensação de Exposição EV",
	"+2",
	"+1.5",
	"+1",
	"+0.5",
	"0",
	"-0.5",
	"-1",
	"-1.5",
	"-2",
	"etiqueta tempo",
	"restaurar padrão",
	"Restaurar configurações padrão?",
	"restabelecer",
	"gravação",
	"A resolução da imagem",
	"16M (4096x4096)",
	"10M (3264x3264)",
	"8M (2880x2880)",
	"5M (3040x1520)",
	"4M (2448x2448)",
	"modo de câmera",
	"modo de visualização da imagem",
	"Tempo de tirar fotos",
	"câmera automática",
	"Explosão",
	"3 P/S",
	"5 P/S",
	"7 P/S",
	"10 P/S",
	"Qualidade de imagem",
	"bom",
	"geral",
	"economia",
	"agudeza",
	"forte",
	"suave",
	"WB WB",
	"luz solar",
	"dia nublado",
	"tungstênio",
	"fluorescente",
	"cor",
	"Preto e branco",
	"marrom",
	"limite de ISO",
	"800",
	"400",
	"200",
	"100",
	"estabilizar",
	"idioma",
	"Englist",
	"简体中文",
	"繁體中文",
	"Français",
	"Español",
	"Italiano",
	"Português",
	"Deutsch",
	"Русский",
	"한국어",
	"にほんご ",
	"Modo sem fio",
	"WIFI Direct Connect",
	"roteamento WIFI",
	"A frequência da fonte de luz",
	"50 HZ",
	"60 HZ",
	"luzes LED",
	"Modo de carro",
	"guardas de estacionamento",
	"sensor de gravidade",
	"imagem invertida",
	"configurações de data e hora",
	"data:",
	"tempo:",
	"AM",
	"PM",
	"volume",
	"10%",
	"20%",
	"30%",
	"40%",
	"50%",
	"60%",
	"70%",
	"80%",
	"90%",
	"100%",
	"bip",
	"o brilho da tela",
	"alto",
	"em",
	"baixo",
	"Protetores de tela automática",
	"desligamento automático",
	"desactivação temporizada",
	"formato",
	"Formatar cartão?",
	"Redefinir câmera",
	"Se deseja redefinir a câmera para os valores padrão?",
	"lançamento",
	"Tipo de produto:",
	"versão do software:",
	"Atualizado:",
	"fabricante:",
	"Formatação ...",
	"erro de formatação",
	"O cartão de memória está vazia",
	"O cartão de memória está cheio",
	"O cartão de memória não é detectado",
	"Erro no cartão",
	"Erro no cartão de memória, formatar",
	"preparação cartão de memória",
	"configuração de Wi-Fi ...",
	"WIFI Closed",
	"adeus",
	"câmera ocupada",
	"Bateria fraca, carregue",
};

const char *language_de[] = {
	"geöffnet",
	"schließen",
	"automatisch",
	"bestätigen",
	"annulliert",
	"1 Sekunde",
	"2 Sekunden",
	"3 Sekunden",
	"5 Sekunden",
	"10 Sekunden",
	"15 Sekunden",
	"20 Sekunden",
	"30 Sekunden",
	"1 Minute",
	"3 Minuten",
	"5 Minuten",
	"10 Minuten",
	"Video-Auflösung",
	"2448x2448 30fps",
	"1920x1080 60fps",
	"1920x1080 30fps",
	"1280x720 30fps",
	"3264x3264",
	"2880x2880",
	"2048x2048",
	"1920x1920",
	"1472x1472",
	"1088x1088",
	"768x768",
	"Video-Capture-Modus",
	"Video-Vorschau-Modus",
	"360 Panorama-Runde",
	"360 Panorama Expand",
	"Zwei geteilte",
	"Aufgeteilt in drei Stücke",
	"Quad",
	"Ring",
	"VR",
	"Loop-Aufnahme",
	"Schrumpf während der Aufnahme",
	"High-Speed-Fotografie",
	"WDR",
	"Belichtungskorrektur EV",
	"+2",
	"+1.5",
	"+1",
	"+0.5",
	"0",
	"-0,5",
	"-1,0",
	"-1,5",
	"-2,0",
	"Zeit-Label",
	"Standard wiederherstellen",
	"Standardeinstellungen wiederherstellen?",
	"zurückstellen",
	"Aufnahme",
	"Bildauflösung",
	"16M (4096x4096)",
	"10M (3264x3264)",
	"8M (2880x2880)",
	"5M (3040x1520)",
	"4M (2448x2448)",
	"Kameramodus",
	"Bild-Vorschau-Modus",
	"Zeit, die Bilder",
	"Automatische Kamera",
	"bersten",
	"3 P/S",
	"5 P/S",
	"7 P/S",
	"10 P/S",
	"Bildqualität",
	"gut",
	"General",
	"Wirtschaft",
	"Schärfe",
	"stark",
	"sanft",
	"WB WB",
	"Sonnenlicht",
	"Bewölkter Tag",
	"Wolfram",
	"fluoreszierend",
	"Farbe",
	"Schwarzweiss",
	"braun",
	"ISO-Grenzwert",
	"800",
	"400",
	"200",
	"100",
	"stabilisieren",
	"Sprache",
	"Englist",
	"简体中文",
	"繁體中文",
	"Français",
	"Español",
	"Italiano",
	"Português",
	"Deutsch",
	"Русский",
	"한국어",
	"にほんご ",
	"Wireless-Modus",
	"WIFI Direct Connect",
	"WIFI-Routing",
	"Die Frequenz der Lichtquelle",
	"50HZ",
	"60HZ",
	"LED-Leuchten",
	"Auto-Modus",
	"Parkwächter",
	"Schwerkraft-Sensor",
	"Inverted Bild",
	"Uhrzeit- und Datumseinstellungen",
	"Datum:",
	"Zeit:",
	"AM",
	"PM",
	"Volumen",
	"10%",
	"20%",
	"30%",
	"40%",
	"50%",
	"60%",
	"70%",
	"80%",
	"90%",
	"100%",
	"Beep",
	"Display-Helligkeit",
	"hoch",
	"in",
	"niedrig",
	"Automatische Bildschirmschoner",
	"Automatische Abschaltung",
	"Verzögerte Abschaltung",
	"Format",
	"Format-Karte?",
	"Kamera zurücksetzen",
	"Ob die Kamera auf die Standardwerte zurücksetzen?",
	"Veröffentlichung",
	"Produkttyp:",
	"Software-Version:",
	"Aktualisiert:",
	"Hersteller:",
	"Formatierung ...",
	"Formatfehler",
	"Die Speicherkarte ist leer",
	"Speicherkarte ist voll",
	"Die Speicherkarte wird nicht erkannt",
	"Speicherkartenfehler",
	"Speicherkartenfehler, die Formatierung",
	"Speicherkarte Vorbereitung",
	"WIFI-Konfiguration ...",
	"WIFI geschlossen",
	"Auf Wiedersehen",
	"Kamera beschäftigt",
	"Niedrige Batterie, bitte aufladen",
};

const char *language_ru[] = {
	"открытый",
	"близко",
	"автоматический",
	"подтвердить",
	"отменен",
	"1 секунда",
	"2 секунды",
	"3 секунды",
	"5 секунд",
	"10 секунд",
	"15 секунд",
	"20 секунд",
	"30 секунд",
	"На 1-й",
	"3 минуты",
	"5 минут",
	"10 минут",
	"Разрешение видео",
	"2448x2448 30 кадров в секунду",
	"1920х1080 60fps",
	"1920х1080 30 кадров в секунду",
	"1280x720 30 кадров в секунду",
	"3264x3264",
	"2880x2880",
	"2048x2048",
	"1920x1920",
	"1472x1472",
	"1088x1088",
	"768x768",
	"Режим съемки видео",
	"Режим Video Preview",
	"360 Панорама Круглый",
	"360 Panorama Увеличить",
	"Два сплит",
	"Разделенный на три части",
	"Quad",
	"кольцо",
	"VR",
	"Циклическая запись",
	"Термоусадочная во время записи",
	"Скоростная фотосъемка",
	"WDR",
	"Компенсация экспозиции EV",
	"+2.0",
	"+1.5",
	"+1.0",
	"+0.5",
	"0",
	"-0.5",
	"-1.0",
	"-1.5",
	"-2.0",
	"метка времени",
	"Восстановить значения по умолчанию",
	"Восстановление настроек по умолчанию?",
	"сброс",
	"запись",
	"разрешение изображения",
	"16M (4096x4096)",
	"10M (3264x3264)",
	"8M (2880x2880)",
	"5M (3040x1520)",
	"4M (2448x2448)",
	"режим камеры",
	"режим предварительного просмотра изображения",
	"Время принимать фотографии",
	"автоматический фотоаппарат",
	"взрыв",
	"3 P/S",
	"5 P/S",
	"7 P/S",
	"10 P/S",
	"Качество изображения",
	"хорошо",
	"общий",
	"экономика",
	"сметливость",
	"сильный",
	"пологий",
	"WB WB",
	"солнечный свет",
	"Пасмурный день",
	"вольфрам",
	"флуоресцентный",
	"цвет",
	"Черно-белое изображение",
	"коричневый",
	"предел ISO",
	"800",
	"400",
	"200",
	"100",
	"стабилизироваться",
	"язык",
	"Englist",
	"简体中文",
	"繁體中文",
	"Français",
	"Español",
	"Italiano",
	"Português",
	"Deutsch",
	"Русский",
	"한국어",
	"にほんご ",
	"Режим беспроводной сети",
	"WIFI Direct Connect",
	"маршрутизации WIFI",
	"Частота источника света",
	"50HZ",
	"60HZ",
	"Светодиодные фонари",
	"Режим автомобиля",
	"Парковочные охранники",
	"датчик силы тяжести",
	"перевернутое изображение",
	"Настройки времени и даты",
	"Дата:",
	"Время:",
	"AM",
	"PM",
	"объем",
	"10%",
	"20%",
	"30%",
	"40%",
	"50%",
	"60%",
	"70%",
	"80%",
	"90%",
	"100%",
	"гудок",
	"яркость дисплея",
	"высокая",
	"в",
	"низкий",
	"Автоматические заставки",
	"автоматический отсекатель",
	"Задержка выключения",
	"формат",
	"Формат карты?",
	"Сброс камеры",
	"Независимо от того, чтобы сбросить камеру к значениям по умолчанию?",
	"релиз",
	"Тип продукта:",
	"Версия программного обеспечения:",
	"Обновлено:",
	"Производитель:",
	"Форматирование ...",
	"ошибка в формате",
	"Карта памяти пуста",
	"Карта памяти заполнена",
	"Карта памяти не обнаружено",
	"Ошибка карты памяти",
	"Ошибка карты памяти, форматирование",
	"Подготовка карты памяти",
	"Конфигурация WIFI ...",
	"WIFI Закрыто",
	"до свидания",
	"камера занята",
	"Низкий уровень заряда батареи, оплатите пожалуйста",
};

const char *language_kr[] = {
	"열린",
	"가까운",
	"자동적 인",
	"확인",
	"취소",
	"일초",
	"이초",
	"삼초",
	"오초",
	"십초",
	"15초",
	"20초",
	"30초",
	"일분",
	"삼분",
	"오분",
	"십분",
	"비디오 해상도",
	"2448x2448 30fps의",
	"1920 × 1080 60fps로",
	"1920 × 1080 30fps의",
	"1280 * 720 30fps의",
	"3264x3264",
	"2880x2880",
	"최대 2048x2048",
	"1920x1920",
	"1472x1472",
	"1088x1088",
	"768x768",
	"비디오 캡처 모드",
	"비디오 미리보기 모드",
	"360 파노라마 라운드",
	"360 파노라마 확장",
	"두 분할",
	"3 세트로 나뉘어",
	"쿼드",
	"링",
	"VR",
	"반복 기록",
	"녹화 중 축소",
	"고속 사진",
	"WDR",
	"노출 보정 EV",
	"+2",
	"+1.5",
	"+1",
	"+0.5",
	"0",
	"-0.5",
	"-1",
	"-1.5",
	"-2",
	"시간 레이블",
	"기본값 복원",
	"기본 설정을 복원?",
	"재설정",
	"녹음",
	"이미지 해상도",
	"16M (4096x4096)",
	"10M (3264x3264)",
	"8M (2880x2880)",
	"5M (3040x1520)",
	"4M (2448x2448)",
	"카메라 모드",
	"이미지 미리보기 모드",
	"시간 사진 촬영",
	"자동 카메라",
	"버스트",
	"3 P/S",
	"5 P/S",
	"7 P/S",
	"10 P/S",
	"이미지 품질",
	"좋은",
	"일반",
	"경제",
	"날카로움",
	"강한",
	"부드러운",
	"WB WB",
	"햇빛",
	"흐린 날",
	"텅스텐",
	"형광",
	"색",
	"흑백의",
	"갈색",
	"ISO 제한",
	"-800",
	"-400",
	"-200",
	"-100",
	"안정",
	"언어",
	"Englist",
	"简体中文",
	"繁體中文",
	"Français",
	"Español",
	"Italiano",
	"Português",
	"Deutsch",
	"Русский",
	"한국어",
	"にほんご ",
	"무선 모드",
	"WIFI 직접 연결",
	"와이파이 라우팅",
	"상기 광원의 주파수",
	"50HZ",
	"60HZ",
	"LED 조명",
	"자동차 모드",
	"주차장 경비원",
	"중력 센서",
	"반전 이미지",
	"시간과 날짜 설정",
	"날짜 :",
	"시간 :",
	"AM",
	"PM",
	"체적",
	"10%",
	"20%",
	"30%",
	"40%",
	"50%",
	"60%",
	"70%",
	"80%",
	"90%",
	"100%",
	"음",
	"디스플레이 밝기",
	"높은",
	"에",
	"낮은",
	"자동 스크린 세이버",
	"자동 종료",
	"지연 종료",
	"체재",
	"카드를 포맷?",
	"리셋 카메라",
	"기본값으로 카메라를 리셋할지 여부?",
	"해제",
	"제품 유형 :",
	"소프트웨어 버전 :",
	"업데이트 :",
	"제조 업체 :",
	"서식 ...",
	"형식 오류",
	"메모리 카드가 비어",
	"메모리 카드가 가득",
	"메모리 카드가 감지되지 않습니다",
	"메모리 카드 오류",
	"메모리 카드 오류, 서식",
	"메모리 카드 준비",
	"WIFI 구성 ...",
	"WIFI 폐쇄",
	"안녕",
	"바쁜 카메라",
	"배터리 부족, 충전하시기 바랍니다",
};

const char *language_jp[] = {
	"オープン",
	"クローズ",
	"自動",
	"確認します",
	"キャンセル",
	"1秒",
	"2秒",
	"3秒",
	"5秒",
	"10秒",
	"15秒",
	"20秒",
	"30秒",
	"1分",
	"3分",
	"5分",
	"10分",
	"ビデオ解像度",
	"2448x2448 30fpsの",
	"1920x1080 60fpsの",
	"1920x1080 30fpsの",
	"1280x720 30fpsの",
	"3264x3264",
	"2880x2880",
	"2048x2048",
	"1920x1920",
	"1472x1472",
	"1088x1088",
	"768x768",
	"ビデオキャプチャモード",
	"ビデオプレビューモード",
	"360パノラマラウンド",
	"360パノラマ展開",
	"二つの分割",
	"3個に分割",
	"クワッド",
	"リング",
	"VR",
	"ループ・レコーディング",
	"記録中シュリンク",
	"高速写真",
	"WDR",
	"露出補正EV",
	"+2",
	"+1.5",
	"+1",
	"+0.5",
	"0",
	"-0.5",
	"-1",
	"-1.5",
	"-2",
	"時間ラベル",
	"デフォルトに戻します",
	"既定の設定を復元しますか?",
	"リセット",
	"記録",
	"画像解像度",
	"16M（4096×4096）",
	"10M（3264x3264）",
	"8M（2880x2880）",
	"5M (3040x1520)",
	"4M（2448x2448）",
	"カメラモード",
	"イメージプレビューモード",
	"時間写真を撮ります",
	"自動カメラ",
	"バースト",
	"3 P/S",
	"5 P/S",
	"7 P/S",
	"10 P/S",
	"画質",
	"グッド",
	"一般的な",
	"経済",
	"切れ味",
	"強いです",
	"ジェントル",
	"WB WB",
	"日光",
	"曇りの日",
	"タングステン",
	"蛍光灯",
	"カラー",
	"白黒",
	"ブラウン",
	"ISOの制限",
	"800",
	"400",
	"200",
	"100",
	"安定させます",
	"言語",
	"Englist",
	"简体中文",
	"繁體中文",
	"Français",
	"Español",
	"Italiano",
	"Português",
	"Deutsch",
	"Русский",
	"한국어",
	"にほんご ",
	"ワイヤレスモード",
	"WIFIダイレクトコネクト",
	"WIFIルーティング",
	"光源の周波数",
	"50HZ",
	"60HZ",
	"LEDライト",
	"カーモード",
	"駐車場警備員",
	"重力センサ",
	"倒立像",
	"日付と時刻の設定",
	"日付:",
	"時間:",
	"AM",
	"PM",
	"ボリューム",
	"10%",
	"20%",
	"30%",
	"40%",
	"50%",
	"60%",
	"70%",
	"80%",
	"90%",
	"100%",
	"ビープ音",
	"ディスプレイの明るさ",
	"ハイ",
	"で",
	"ロー",
	"自動スクリーンセーバー",
	"自動遮断",
	"遅れてシャットダウン",
	"フォーマット",
	"フォーマットカード?",
	"カメラをリセット",
	"デフォルト値にカメラをリセットするかどうか?",
	"リリース",
	"製品タイプ:",
	"ソフトウェアバージョン:",
	"更新日:",
	"メーカー:",
	"フォーマット...",
	"フォーマットエラー",
	"メモリカードは空です",
	"メモリーカードがいっぱいです",
	"メモリカードが検出されません",
	"メモリーカードエラー",
	"メモリカードエラー、書式設定",
	"メモリーカードの準備",
	"WIFIの設定...",
	"WIFIクローズド",
	"さようなら",
	"忙しいカメラ",
	"ローバッテリー、充電してください。",
};

const char **g_language = language_zh;

int GetStringId(const char *value)
{
    int i, id = 0;
    for(i = 0; i < STRING_END; i ++)
    {
        if(!strcasecmp(value, language_en[i]))
        {
            id = i + 1;
            break;
        }
    }
    return id;
}

