#
# Makefile InfotmMeida foundations.
#
# Copyright (c) 2009~2014 ShangHai Infotm Ltd all rights reserved.
#
#

include drivers/infotm/common/InfotmMedia/env.mk

obj-y += list_c.o
obj-y += mempool_c.o

EXTRA_CFLAGS += -Idrivers/infotm/common/InfotmMedia/include

