obj-y += lcdc/
obj-y += tvif/
#obj-y += i80/
obj-y += irq.o
obj-y += controller.o

EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/common
EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/implementation
EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/implementation/module/access

