
obj-$(CONFIG_INFOTM_CAMERA_SENSOR) += sensors/
obj-$(CONFIG_INFOTM_ISP) += isp/
obj-$(CONFIG_INFOTM_CAMIF) += camif/
obj-$(CONFIG_INFOTM_DUAL_BRIDGE) += bridge/
obj-$(CONFIG_INFOTM_MIPI_CSI) += csi/

