obj-y += logo_bmp.o

EXTRA_CFLAGS += -Idrivers/infotm/coronampw/display/common
EXTRA_CFLAGS += -Idrivers/infotm/coronampw/display/abstraction
EXTRA_CFLAGS += -Idrivers/infotm/coronampw/display/implementation

