#
#  Makefile for the foet core drivers.
#
#  Each configuration option enables a list of files.
obj-$(CONFIG_INFOTM_FODET)   += drv_fodet.o ci_fodet.o

EXTRA_CFLAGS += -DIMG_KERNEL_MODULE
#EXTRA_CFLAGS += -DINFOTM_FODET
