cmake_minimum_required (VERSION 2.8)

get_filename_component (SENSORAPI_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)

#
# needs the FelixLib project to exists before called!
#

#find_package(ImgIncludes REQUIRED) # should be found by the application
find_package(FelixCommon REQUIRED)

if (NOT DEFINED SENSOR_AR330)
  set(SENSOR_AR330 TRUE)
endif()

if (NOT DEFINED SENSOR_AR330_DVP)
  set(SENSOR_AR330_DVP TRUE)
endif()
if (NOT DEFINED SENSOR_AR330_MIPI)
  set(SENSOR_AR330_MIPI TRUE)
endif()
if (NOT DEFINED SENSOR_IMX322_DVP)
  set(SENSOR_IMX322_DVP TRUE)
endif()
if (NOT DEFINED SENSOR_IMX179_MIPI)
  set(SENSOR_IMX179_MIPI TRUE)
endif()

if (NOT DEFINED SENSOR_99141_DVP)
  set(SENSOR_99141_DVP TRUE)
endif()
if (NOT DEFINED SENSOR_683Dual_MIPI)
  set(SENSOR_683Dual_MIPI TRUE)
endif()
#if (NOT DEFINED SENSOR_P401)
#  set(SENSOR_P401 FALSE)
#endif()
#if (NOT DEFINED SENSOR_OV4688)
#  set(SENSOR_OV4688 FALSE)
#endif()

if (NOT DEFINED SENSOR_OV2710)
  set(SENSOR_OV2710 TRUE)
endif()
if (NOT DEFINED SENSOR_OV4689)
  set(SENSOR_OV4689 TRUE)
endif()

set (SENSORAPI_FOUND TRUE)
set (SENSORAPI_INCLUDE_DIRS ${SENSORAPI_PREFIX}/include ${FELIXCOMMON_INCLUDE_DIRS})
set (SENSORAPI_DEFINITIONS)
set (SENSORAPI_NAME sensorapi)
set (SENSORAPI_LIBRARIES ${SENSORAPI_NAME})

if (CI_EXT_DATA_GENERATOR)
    find_package(FelixDG REQUIRED)
    set(SENSORAPI_INCLUDE_DIRS ${SENSORAPI_INCLUDE_DIRS} ${FELIXDG_INCLUDE_DIRS})
    set(SENSORAPI_DEFINITIONS ${SENSORAPI_DEFINITIONS} ${FELIXDG_DEFINITIONS})
endif()
