#ifndef __SPV_CONFIG_KEYS_H__
#define __SPV_CONFIG_KEYS_H__

#define GETKEY(id) g_config_key[id]
#define GETVALUE(id) language_en[id - 1]

#define MAX_VALUE_COUNT 12

enum ITEM_ID {
    ID_CURRENT_MODE,

    //video
    ID_VIDEO_RESOLUTION = 1,
	ID_VIDEO_RECORD_MODE,
	ID_VIDEO_PREVIEW,
    ID_VIDEO_LOOP_RECORDING,
	ID_VIDEO_TIMELAPSED_IMAGE,
	ID_VIDEO_HIGH_SPEED,
    ID_VIDEO_WDR,
    ID_VIDEO_EV,
	ID_VIDEO_GSENSOR,
    ID_VIDEO_DATE_STAMP,
    ID_VIDEO_RECORD_AUDIO,
    ID_VIDEO_RESET,

    //photo
    ID_PHOTO_RESOLUTION,
	ID_PHOTO_CAPTUREMODE,
	ID_PHOTO_PREVIEW,
	ID_PHOTO_MODE_TIMER,
	ID_PHOTO_MODE_AUTO,
	ID_PHOTO_MODE_SEQUENCE,
	ID_PHOTO_QUALITY,
    ID_PHOTO_SHARPNESS,
    ID_PHOTO_WHITE_BALANCE,
    ID_PHOTO_COLOR,
    ID_PHOTO_ISO_LIMIT,
    ID_PHOTO_EV,
    ID_PHOTO_ANTI_SHAKING,
    ID_PHOTO_DATE_STAMP,
    ID_PHOTO_RESET,

    //setup
    ID_SETUP_LANGUAGE,
	ID_SETUP_WIFI_MODE,
	ID_SETUP_LED_FREQ, 
	ID_SETUP_LED,
	ID_SETUP_CARDV_MODE,
    ID_SETUP_PARKING_GUARD,
	ID_SETUP_IMAGE_ROTATION,
    ID_SETUP_DATE_TIME,
	ID_SETUP_VOLUME,
	ID_SETUP_KEY_TONE,
    ID_SETUP_DISPLAY_BRIGHTNESS,
	ID_SETUP_AUTO_SLEEP,
	ID_SETUP_AUTO_POWER_OFF,
	ID_SETUP_DELAYED_SHUTDOWN,
	ID_SETUP_FORMAT,
	ID_SETUP_CAMERA_RESET,
	ID_SETUP_VERSION,

    //data & time
    ID_SETUP_DATE,
    ID_SETUP_TIME,

    //external status key
    ID_WIFI_AP_SSID,
    ID_WIFI_AP_PSWD,
    ID_WIFI_AP_KEYMGMT,
    ID_WIFI_STA_SSID,
    ID_WIFI_STA_PSWD,
    ID_WIFI_STA_KEYMGMT,

    ID_REVERSE_IMAGE,
};


extern const char *g_mode_name[];
extern const char *g_config_key[];

int GetKeyId(const char *key);
#endif //__SPV_ITEM_H__
