obj-y += logo_bmp.o

EXTRA_CFLAGS += -Idrivers/infotm/common/display/common
EXTRA_CFLAGS += -Idrivers/infotm/common/display/abstraction   
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation

