obj-y += lcd_panel_params/
obj-y += lcd_panel.o

EXTRA_CFLAGS += -Idrivers/infotm/q3f/display/common
EXTRA_CFLAGS += -Idrivers/infotm/q3f/display/implementation/module/terminal/lcd_panel/lcd_panel_params
EXTRA_CFLAGS += -Idrivers/infotm/q3f/display/implementation/module/interface/dev