#ifndef __IMAP_USBOTG_H__
#define __IMAP_USBOTG_H__

//
// OTG slave register
//
#define OTGS_ACR				(USBOTG_BASE_REG_PA + 0x4000)
#define OTGS_MDAR				(USBOTG_BASE_REG_PA + 0x4004)
#define OTGS_UDCR				(USBOTG_BASE_REG_PA + 0x4008)
#define OTGS_FNCR				(USBOTG_BASE_REG_PA + 0x400c)
#define OTGS_FHHR				(USBOTG_BASE_REG_PA + 0x4010)
#define OTGS_PRIR				(USBOTG_BASE_REG_PA + 0x4014)
#define OTGS_STR0				(USBOTG_BASE_REG_PA + 0x4018)
#define OTGS_STR1				(USBOTG_BASE_REG_PA + 0x401c)
#define OTGS_BFCR				(USBOTG_BASE_REG_PA + 0x4020)
#define OTGS_TBCR0				(USBOTG_BASE_REG_PA + 0x4030)
#define OTGS_TBCR1				(USBOTG_BASE_REG_PA + 0x4034)
#define OTGS_TBCR2				(USBOTG_BASE_REG_PA + 0x4038)
#define OTGS_TBCR3				(USBOTG_BASE_REG_PA + 0x403C)
#define OTGS_IER				(USBOTG_BASE_REG_PA + 0x4050)
#define OTGS_IDR				(USBOTG_BASE_REG_PA + 0x4054)
#define OTGS_ISR				(USBOTG_BASE_REG_PA + 0x4058)
#define OTGS_CCR				(USBOTG_BASE_REG_PA + 0x4070)
#define OTGS_PIR0				(USBOTG_BASE_REG_PA + 0x4074)
#define OTGS_PIR1				(USBOTG_BASE_REG_PA + 0x4078)
#define OTGS_EDR0				(USBOTG_BASE_REG_PA + 0x4080)
#define OTGS_EDR1				(USBOTG_BASE_REG_PA + 0x4084)
#define OTGS_EDR2				(USBOTG_BASE_REG_PA + 0x4088)
#define OTGS_EDR3				(USBOTG_BASE_REG_PA + 0x408c)
#define OTGS_EDR4				(USBOTG_BASE_REG_PA + 0x4090)
#define OTGS_EDR5				(USBOTG_BASE_REG_PA + 0x4094)
#define OTGS_EDR6				(USBOTG_BASE_REG_PA + 0x4098)

//
// OTG link register
//
#define OTGL_BCWR				(USBOTG_BASE_REG_PA + 0x8000)
#define OTGL_BCSR				(USBOTG_BASE_REG_PA + 0x8010)
#define OTGL_ISR				(USBOTG_BASE_REG_PA + 0x8020)
#define OTGL_IER				(USBOTG_BASE_REG_PA + 0x8030)
#define OTGL_IDR				(USBOTG_BASE_REG_PA + 0x8040)











#endif /*__IMAP_USBOTG_H__*/
