#ifndef __IMAPX_MPDMA__
#define __IMAPX_MPDMA__

#define MPDMA_INTERADDR			(MPDMA_BASE_REG_PA + 0x0)
#define MPDMA_ALT1_INTERADDR	(MPDMA_BASE_REG_PA + 0x4)
#define MPDMA_ALT2_INTERADDR	(MPDMA_BASE_REG_PA + 0x8)
#define MPDMA_ALT3_INTERADDR	(MPDMA_BASE_REG_PA + 0xc)
#define MPDMA_DMAENABLE			(MPDMA_BASE_REG_PA + 0x10)
#define MPDMA_INTRMASK			(MPDMA_BASE_REG_PA + 0x14)

#define MPDMA_EXTERADDR			(MPDMA_BASE_REG_PA + 0x80)
#define MPDMA_CONTROL			(MPDMA_BASE_REG_PA + 0x84)

#define MPDMA_ALT1_EXTERADDR	(MPDMA_BASE_REG_PA + 0x88)
#define MPDMA_ALT1_CONTROL		(MPDMA_BASE_REG_PA + 0x8c)

#define MPDMA_ALT2_EXTERADDR	(MPDMA_BASE_REG_PA + 0x90)
#define MPDMA_ALT2_CONTROL		(MPDMA_BASE_REG_PA + 0x94)

#define MPDMA_ALT3_EXTERADDR	(MPDMA_BASE_REG_PA + 0x98)
#define MPDMA_ALT3_CONTROL		(MPDMA_BASE_REG_PA + 0x9c)

#endif
