cmake_minimum_required (VERSION 2.8)

get_filename_component (FELIXCOMMON_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)

set (FELIXCOMMON_FOUND TRUE)
set (FELIXCOMMON_INCLUDE_DIRS ${FELIXCOMMON_PREFIX}/include/)
set (FELIXCOMMON_DEFINITIONS)

if (DEFINED FELIXCOMMON_NDEBUG)
    set(FELIXCOMMON_DEFINES ${FELIXCOMMON_DEFINITIONS}
        -DLOG_NDEBUG=${FELIXCOMMON_NDEBUG})
    #message("FELIXCOMMON_NDEBUG=${FELIXCOMMON_NDEBUG}")
endif()
if (DEFINED FELIXCOMMON_NPERF)
    set(FELIXCOMMON_DEFINITIONS ${FELIXCOMMON_DEFINITIONS}
        -DLOG_NPERF=${FELIXCOMMON_NPERF})
    #message("FELIXCOMMON_NPERF=${FELIXCOMMON_NPERF}")
endif()

set (FELIXCOMMON_NAME FelixCommon)
set (FELIXCOMMON_LIBRARIES ${FELIXCOMMON_NAME})

set (FELIXCOMMON_BUILD_KO ${FELIXCOMMON_PREFIX}/FelixCommon_kernel.cmake)
