obj-$(CONFIG_CPU_FREQ_GOV_INFODEMAND)  += cpufreq_infodemand.o infotm_arbi.o

obj-$(CONFIG_INFOTM_CPU_FIT)			+=percpu_dvfs.o cpu_fit.o

obj-$(CONFIG_INFOTM_VOL_FIT)			+=vol_fit.o

obj-$(CONFIG_INFOTM_CPUFREQ) += imapx800-cpufreq.o

