/*!
******************************************************************************
@file   : /home/jenkins/builds/workspace/ISP_PKG/build/CI/felix/regdefs2.7/regdefs//hw_struct/ext_data_generation.h

@brief  

@Author <Autogenerated>

		<b>Copyright 2005 by Imagination Technologies Limited.</b>
		All rights reserved.  No part of this software, either
		material or conceptual may be copied or distributed,
		transmitted, transcribed, stored in a retrieval system
		or translated into any human or computer language in any
		form by any means, electronic, mechanical, manual or
		other-wise, or disclosed to third parties without the
		express written permission of Imagination Technologies
		Limited, Unit 8, HomePark Industrial Estate,
		King's Langley, Hertfordshire, WD4 8LZ, U.K.

<b>Description:</b>\n
		This file contains the EXT_DATA_GENERATION_H Defintions.


 Register Attributes meaning:
 @li <REG>_OFFSET <int> offset in bytes from the register bank
 @li <REG>_STRIDE <int> [table register only] distance in bytes between table entries
 @li <REG>_NO_ENTRIES <int> [table register only] number of entries in the table
 @li <REG>_TRUSTED <bool> [only if register is trusted] if the register can only be written by trusted source

 Fields Attributes meaning:
 @li <FIELD>_MASK <int> in register
 @li <FIELD>_LSBMASK <int> when field is shifted to LSBs
 @li <FIELD>_SHIFT <int> in bits from LSB
 @li <FIELD>_LENGTH <int> in bits
 @li <FIELD>_DEFAULT <int>
 @li <FIELD>_SIGNED_FIELD <bool>
 @li <FIELD>_NO_REPS <int> [repeated field only] number of time the field is repeated
 @li <FIELD>_SIZE <int> [repeated field only] size of repeated field (same than LENGTH)

 If the register bank is a structure <BANK>_BYTE_SIZE <int> is defined as the size in memory.
******************************************************************************/

#if !defined (__EXT_DATA_GENERATION_H__)
#define __EXT_DATA_GENERATION_H__

#ifdef __cplusplus
extern "C" {
#endif


#define DATA_GENERATION_POINTERS_GROUP_DG_LINK_ADDR_OFFSET		(0x0000)

/* DATA_GENERATION_POINTERS_GROUP, DG_LINK_ADDR, DG_LINK_ADDRESS
*/
#define DATA_GENERATION_POINTERS_GROUP_DG_LINK_ADDR_DG_LINK_ADDRESS_MASK		(0xFFFFFFC0)
#define DATA_GENERATION_POINTERS_GROUP_DG_LINK_ADDR_DG_LINK_ADDRESS_LSBMASK		(0x03FFFFFF)
#define DATA_GENERATION_POINTERS_GROUP_DG_LINK_ADDR_DG_LINK_ADDRESS_SHIFT		(6)
#define DATA_GENERATION_POINTERS_GROUP_DG_LINK_ADDR_DG_LINK_ADDRESS_LENGTH		(26)
#define DATA_GENERATION_POINTERS_GROUP_DG_LINK_ADDR_DG_LINK_ADDRESS_DEFAULT		(0)
#define DATA_GENERATION_POINTERS_GROUP_DG_LINK_ADDR_DG_LINK_ADDRESS_SIGNED_FIELD	(IMG_FALSE)

#define DATA_GENERATION_POINTERS_GROUP_DG_TAG_OFFSET		(0x0004)

/* DATA_GENERATION_POINTERS_GROUP, DG_TAG, DG_TAG
*/
#define DATA_GENERATION_POINTERS_GROUP_DG_TAG_DG_TAG_MASK		(0xFFFFFFFF)
#define DATA_GENERATION_POINTERS_GROUP_DG_TAG_DG_TAG_LSBMASK		(0xFFFFFFFF)
#define DATA_GENERATION_POINTERS_GROUP_DG_TAG_DG_TAG_SHIFT		(0)
#define DATA_GENERATION_POINTERS_GROUP_DG_TAG_DG_TAG_LENGTH		(32)
#define DATA_GENERATION_POINTERS_GROUP_DG_TAG_DG_TAG_DEFAULT		(0)
#define DATA_GENERATION_POINTERS_GROUP_DG_TAG_DG_TAG_SIGNED_FIELD	(IMG_FALSE)

#define DATA_GENERATION_POINTERS_GROUP_DG_ADDR_DATA_OFFSET		(0x0008)

/* DATA_GENERATION_POINTERS_GROUP, DG_ADDR_DATA, DG_ADDR_DATA
*/
#define DATA_GENERATION_POINTERS_GROUP_DG_ADDR_DATA_DG_ADDR_DATA_MASK		(0xFFFFFFC0)
#define DATA_GENERATION_POINTERS_GROUP_DG_ADDR_DATA_DG_ADDR_DATA_LSBMASK		(0x03FFFFFF)
#define DATA_GENERATION_POINTERS_GROUP_DG_ADDR_DATA_DG_ADDR_DATA_SHIFT		(6)
#define DATA_GENERATION_POINTERS_GROUP_DG_ADDR_DATA_DG_ADDR_DATA_LENGTH		(26)
#define DATA_GENERATION_POINTERS_GROUP_DG_ADDR_DATA_DG_ADDR_DATA_DEFAULT		(0)
#define DATA_GENERATION_POINTERS_GROUP_DG_ADDR_DATA_DG_ADDR_DATA_SIGNED_FIELD	(IMG_FALSE)

#define DATA_GENERATION_POINTERS_GROUP_DG_DATA_STRIDE_OFFSET		(0x000C)

/* DATA_GENERATION_POINTERS_GROUP, DG_DATA_STRIDE, DG_ADDR_DATA_STRIDE
*/
#define DATA_GENERATION_POINTERS_GROUP_DG_DATA_STRIDE_DG_ADDR_DATA_STRIDE_MASK		(0xFFFFFFC0)
#define DATA_GENERATION_POINTERS_GROUP_DG_DATA_STRIDE_DG_ADDR_DATA_STRIDE_LSBMASK		(0x03FFFFFF)
#define DATA_GENERATION_POINTERS_GROUP_DG_DATA_STRIDE_DG_ADDR_DATA_STRIDE_SHIFT		(6)
#define DATA_GENERATION_POINTERS_GROUP_DG_DATA_STRIDE_DG_ADDR_DATA_STRIDE_LENGTH		(26)
#define DATA_GENERATION_POINTERS_GROUP_DG_DATA_STRIDE_DG_ADDR_DATA_STRIDE_DEFAULT		(0)
#define DATA_GENERATION_POINTERS_GROUP_DG_DATA_STRIDE_DG_ADDR_DATA_STRIDE_SIGNED_FIELD	(IMG_FALSE)

/*
 * size of the memory structure DATA_GENERATION_POINTERS_GROUP
 * Computed from DG_DATA_STRIDE offset and size
 */
#define DATA_GENERATION_POINTERS_GROUP_BYTE_SIZE		(0x0010)


#ifdef __cplusplus
}
#endif

#endif /* __EXT_DATA_GENERATION_H__ */
