obj-y += osd_x15.o
EXTRA_CFLAGS += -Idrivers/infotm/coronampw/display/common
EXTRA_CFLAGS += -Idrivers/infotm/coronampw/display/implementation
EXTRA_CFLAGS += -Idrivers/infotm/coronampw/display/implementation/module/access
EXTRA_CFLAGS += -Idrivers/infotm/coronampw/display/implementation/module/controller

