obj-$(CONFIG_ARCH_IMAPX910)	+= imapx910/
obj-$(CONFIG_ARCH_IMAPX15)	+= imapx15/
obj-$(CONFIG_ARCH_APOLLO)  += apollo/
obj-$(CONFIG_ARCH_Q3F)  += q3f/
obj-$(CONFIG_ARCH_APOLLO3)  += apollo3/
obj-$(CONFIG_ARCH_CORONAMPW)  += coronampw/
obj-y	+= common/
