/****************************************************************************
*              Copyright 2007 - 2011, Hisilicon Tech. Co., Ltd.
*                           ALL RIGHTS RESERVED
* FileName: hi_msession_rtsp_o_http_error.h
* Description: vod error code list
*
* History:
* Version   Date         Author     DefectNum    Description
* 1.1       2008-02-29   w54723     NULL         Create this file.
*****************************************************************************/

#ifndef __HI_MSESSION_RTSP_O_HTTP_ERROR_H__
#define __HI_MSESSION_RTSP_O_HTTP_ERROR_H__

#ifdef __cplusplus
#if __cplusplus
extern "C"{
#endif
#endif /* __cplusplus */
//#include "hi_type.h"
#include "ext_defs.h" 

#define HI_ERR_RTSP_O_HTTP_SOCKET_ERR          HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x01)
#define HI_ERR_RTSP_O_HTTP_LISNSVR_INIT        HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x02)
#define HI_ERR_RTSP_O_HTTP_LISNSVR_SELECT      HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x03)
#define HI_ERR_RTSP_O_HTTP_BUFF_SMALL          HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x04)
#define HI_ERR_RTSP_O_HTTP_MALLOC              HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x05)

#define HI_ERR_RTSP_O_HTTP_SOCKET_CLOSE        HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x06)

#define HI_ERR_RTSP_O_HTTP_SVR_THREAD          HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x07)

#define HI_ERR_RTSP_O_HTTP_PARSE_ERROR         HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x08)
#define HI_ERR_RTSP_O_HTTP_INVALID_URL         HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x09)

#define HI_ERR_RTSP_O_HTTP_SEQ                 HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x0A)

#define HI_ERR_RTSP_O_HTTP_NOT_SUPPORT_CMD     HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x0B)

#define HI_ERR_RTSP_O_HTTP_SVR_ALREADY_RUNNING HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x0C)

#define HI_ERR_RTSP_O_HTTP_SVR_ALREADY_STOPED  HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x0D)
#define HI_ERR_RTSP_O_HTTP_ILLEGALE_CONN_NUM   HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x0E)
#define HI_ERR_RTSP_O_HTTP_OVER_CONN_NUM       HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x0F)
#define HI_ERR_RTSP_O_HTTP_ILLEGALE_REQUEST    HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x10)
#define HI_ERR_RTSP_O_HTTP_ILLEGALE_PARAM      HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x11)
#define HI_ERR_RTSP_O_HTTP_PARSE_METHOD_ERROR  HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x12)
#define HI_ERR_RTSP_O_HTTP_SEND_FAILED    HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x13)
#define HI_ERR_RTSP_O_HTTP_READ_FAILED    HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x14)
#define HI_ERR_RTSP_O_HTTP_CREAT_SESSION_THREAD_FAILED     HI_APP_DEF_ERR(HI_APPID_LIVE_RTSP_O_HTTPSVR, LOG_LEVEL_ERROR, 0x15)

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif /* __cplusplus */

#endif

