// Copyright 2012 Google Inc. All Rights Reserved.

#ifndef SOFTWARE_SOURCE_COMMON_VERSION_H_
#define SOFTWARE_SOURCE_COMMON_VERSION_H_

#define HANTRO_DEC_SW_BUILD_MAJOR 4
#define HANTRO_DEC_SW_BUILD_MINOR 1

#define HANTRO_DEC_SW_BUILD \
  ((HANTRO_DEC_SW_BUILD_MAJOR << 16) + HANTRO_DEC_SW_BUILD_MINOR)

#endif /* SOFTWARE_SOURCE_COMMON_VERSION_H_ */
