/*************************************************
 * this file is auto generated by gen-entry.sh
 * do not edit !
 *
 * Fri Apr 21 14:58:52 CST 2017
 ************************************************/
#include <asm-arm/io.h>
#include <preloader.h>

#define __F(x) (void *)(x)

struct irom_export irf_corona = {

    .init_timer          = __F(0x0000898c),
    .init_serial         = __F(0x00008928),
    .printf              = __F(0x0000d7a4),
    .udelay              = __F(0x00008a38),
    .memcpy              = __F(0x000013f8),
    .strnlen             = __F(0x000013b0),
    .sprintf             = __F(0x0000d5ec),
    .vs_reset            = __F(0x00004b8c),
    .vs_read             = __F(0x000050e0),
    .vs_write            = __F(0x00004bc8),
    .vs_erase            = __F(0x00004c20),
    .vs_isbad            = __F(0x00004c5c),
    .vs_scrub            = __F(0x00004c98),
    .vs_special          = __F(0x00004cd4),
    .vs_assign_by_name   = __F(0x00004fdc),
    .vs_assign_by_id     = __F(0x00004d6c),
    .vs_device_id        = __F(0x00004f8c),
    .vs_is_assigned      = __F(0x00004ae8),
    .vs_align            = __F(0x00004d10),
    .vs_is_device        = __F(0x0000507c),
    .vs_is_opt_available = __F(0x00004b00),
    .vs_device_name      = __F(0x00004f00),
    .boot_device         = __F(0x00000608),
    .isi_check_header    = __F(0x00001998),
    .cdbg_shell          = __F(0x0000626c),
    .simple_strtol       = __F(0x0000c874),
    .strncmp             = __F(0x00001314),
    .strncpy             = __F(0x00001250),
    .cdbg_log_toggle     = __F(0x00006108),
    .module_set_clock    = __F(0x00000714),
    .module_get_clock    = __F(0x0000107c),
    .module_enable       = __F(0x00000740),
    .set_pll             = __F(0x00000624),
    .memset              = __F(0x000013d8),
    .ss_jtag_en          = __F(0x0000f784),
    .malloc              = __F(0x0000158c),
    .free                = __F(0x0000172c),
    .pads_chmod          = __F(0x00000bbc),
    .pads_pull           = __F(0x00000cf4),
    .get_xom             = __F(0x00000590),
    .hash_init           = __F(0x00005824),
    .hash_data           = __F(0x00005790),
    .hash_value          = __F(0x00005720),
    .get_timer           = __F(0x00008a68),
};

