obj-y	+= i80_driver.o i80-interface.o tft3p3469.o st7789s.o st7567.o

EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/common
EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/implementation
EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/implementation/module/access
EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/implementation/module/controller

