obj-y +=dev.o
obj-$(CONFIG_APOLLO3_LCD_SPI_ILI8961) += ili8961.o
obj-$(CONFIG_APOLLO3_LCD_SPI_OTA5182A) += ota5182a.o
obj-$(CONFIG_APOLLO3_CVBS_I2C_IP2906) += ip2906-cvbs.o

EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/common
EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/implementation/module/access
