#! /bin/sh

case "$1" in
	start|"")
		modprobe ddk_sensor i2c_addr=0x6C mipi=1 lanes=4
		modprobe hx280enc_265
		modprobe vdec_g1
		modprobe vdec_g2
		modprobe Felix ui32ClkRate=256000000
		modprobe hx280enc_h1
		videoboxd
		;;
	stop)
		killall videoboxd
		;;
	*)
		echo "Usage: videobox {start|stop}" >&2
		exit 1
		;;
esac

