#!/bin/sh
#
# debug        debug
#

uvc_enable()
{
    modprobe g_webcam 
}

usb_ethernet_enable()
{
	modprobe g_ether
	ifconfig usb0 up
	ifconfig usb0 172.3.0.2
}

case "$1" in
  start)
    modprobe dwc_otg
    mount -t debugfs none /sys/kernel/debug
    # dwc_otg soft disconnect & connect
    echo 0 > /sys/kernel/debug/dwc_otg/link
    echo 1 > /sys/kernel/debug/dwc_otg/link

    if [ -f "/mnt/config/.infotm_uvc_enable" ]; then
        echo "uvc enalbe"
        uvc_enable
    else
        echo "usb ethernet enalbe"
        usb_ethernet_enable
    fi
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

