#! /bin/sh

bootup_tone()
{
    echo "start booting up tone"
    loop=0
    while [ $loop -lt 2 ] 
    do
        echo 200 > /sys/devices/platform/imap-pwm/beep_freq
        usleep 200000
        echo 1 >  /sys/devices/platform/imap-pwm/beep_stop
        usleep 100000
        loop=`expr $loop + 1`
    done
}


case "$1" in
	start|"")
        audiobox &
        #if [ ! -f "/sys/devices/platform/imap-pwm/beep_freq" ]; then
            #abctrl play -d /usr/share/launcher/res/booting.wav -w 32 -s 48000 -n 2 &
        #else
            #bootup_tone &
        #fi  
		;;
	stop)
		killall audiobox
		;;
	*)
		echo "Usage: audiobox {start|stop}" >&2
		exit 1
		;;
esac

