obj-y += lcd_port/
obj-y += hdmi/
obj-y += cvbs/
obj-y += i80/
#obj-y += mipi/
obj-y += interface.o

EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/common
EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/implementation

