#
#  Makefile for the ispost core drivers.
#
#  Each configuration option enables a list of files.
obj-$(CONFIG_INFOTM_ISPOST)   += drv_ispost.o ci_ispost.o

EXTRA_CFLAGS += -DIMG_KERNEL_MODULE
#EXTRA_CFLAGS += -DINFOTM_ISPOST
