#! /bin/sh

case "$1" in
	start|"")
		modprobe Felix clkRate=198000000
		#modprobe ddk_sensor
		#modprobe hx280enc_h1 g_h1_clk=300
		videoboxd
        echo "--------->Videobox started<-----------"
		;;
	stop)
		killall videoboxd
		;;
	*)
		echo "Usage: videobox {start|stop}" >&2
		exit 1
		;;
esac

