obj-y += lcd_port/
#obj-y += cvbs/
obj-y+=dev/
obj-y += interface.o

#obj-y += hdmi/
#obj-y += mipi/

EXTRA_CFLAGS += -Idrivers/infotm/coronampw/display/common
EXTRA_CFLAGS += -Idrivers/infotm/coronampw/display/implementation

