#
# Makefile for the Infotm NAND drivers.
#

obj-$(CONFIG_INFOTM_NAND)	+= infotm_nand_ids.o infotm_nand.o imapx800_nand.o
#obj-$(CONFIG_ARCH_IMAPX800)	+= imapx800_nand.o
#obj-$(CONFIG_MTD_INFOTM_NAND)	+= nand_mtd.o
#obj-$(CONFIG_MTD_INFOTM_NAND)	+= imapx800.o
#obj-$(CONFIG_MTD_INFOTM_NAND)	+= nand_ids.o
#obj-$(CONFIG_MTD_INFOTM_NAND)	+= part.o
#obj-$(CONFIG_INFOTM_NAND)	+= nand_env.o
obj-$(CONFIG_INFOTM_NAND)	+= nand_env.o
obj-y							+= infotm_nftl/ 
#obj-$(CONFIG_MTD_INFOTM_NAND)	+= rtc_reboot.o
#obj-$(CONFIG_MTD_INFOTM_NAND)	+= nand_env.o
#obj-$(CONFIG_MTD_INFOTM_NAND)	+= nand_bbt.o

