LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := libfelix_dyncmd
LOCAL_MODULE_TAGS := eng

EXPORT_FELIX_DYNCMD_INCLUDE_DIRS := \
    $(LOCAL_PATH)/include \
    $(EXPORT_FELIX_COMMON_INCLUDE_DIRS)

LOCAL_C_INCLUDES := \
    $(EXPORT_FELIX_DYNCMD_INCLUDE_DIRS)

LOCAL_SRC_FILES := include $(call all-c-files-under, code)

LOCAL_CFLAGS += $(FELIX_LOCAL_CFLAGS)

include $(BUILD_STATIC_LIBRARY)