#ifndef COMMON_INFT_DATA_H
#define COMMON_INFT_DATA_H

typedef enum{
    ENTRY_VIDOE_INFO_NULL = -1,
    ENTRY_VIDOE_INFO_MIN = 0,
    ENTRY_VIDOE_INFO_HIG = ENTRY_VIDOE_INFO_MIN,
    ENTRY_VIDOE_INFO_MED,
    ENTRY_VIDOE_INFO_LOW,   
    ENTRY_VIDEO_INFO_MJPEG = ENTRY_VIDOE_INFO_LOW,
    ENTRY_AUDIO_PREVIEW,
    ENTRY_AUDIO_PLAYBACK,
    ENTRY_JPEG_INFO,
    ENTRY_INFO_CNT
}SHM_ENTRY_TYPE;

#endif
