#!/bin/bash

echo "/*************************************************"
echo " * this file is auto generated by gen-entry.sh"
echo " * do not edit !"
echo " *"
echo " * `date`"
echo " ************************************************/"
echo
echo "#include <asm-arm/io.h>"
echo "#include \"preloader.h\""
echo
echo "#define __F(x) (void *)(x)"
echo
echo "struct irom_export irf_$1 = {"
echo 

for i in `cat $2 | awk '{print $1}'`; do
	echo "    .`grep $i $2 | awk '{printf("%-20s", $2)};'`= __F(`grep "<$i>:" $3 | awk '{print "0x" $1}'`),"
done
echo "};"
echo
