snd-soc-alc5631-objs := alc5631.o
snd-soc-es8328-objs := es8328.o
snd-soc-es8323-objs := es8323.o
snd-soc-fr1023-objs := fr1023.o
snd-soc-imap_null-objs := imap_null.o
snd-soc-tqlp9624-objs := tqlp9624.o
snd-soc-ip6205-objs := ip6205.o
snd-soc-ip2906-objs := ip2906.o
obj-$(CONFIG_SND_SOC_ALC5631)   += snd-soc-alc5631.o
obj-$(CONFIG_SND_SOC_FR1023)   += snd-soc-fr1023.o
obj-$(CONFIG_SND_SOC_VIRTUAL) += snd-soc-imap_null.o
obj-$(CONFIG_SND_SOC_ES8323)   += snd-soc-es8323.o
obj-$(CONFIG_SND_SOC_ES8328)   += snd-soc-es8328.o
obj-$(CONFIG_SND_SOC_TQLP9624)   += snd-soc-tqlp9624.o
obj-$(CONFIG_SND_SOC_IP6205)	+= snd-soc-ip6205.o
obj-$(CONFIG_SND_SOC_IP2906)	+= snd-soc-ip2906.o

obj-y += bt_codec.o

# for hp detect
obj-y+= hpdetect.o
