################################################################################
#
# hlibcamsensor
#
################################################################################

HLIBCAMSENSOR_VERSION = 1.0.0
HLIBCAMSENSOR_MAINTAINED = YES
HLIBCAMSENSOR_INSTALL_STAGING = YES
HLIBCAMSENSOR_DEPENDENCIES = host-pkgconf
HLIBCAMSENSOR_MAKE = make -s
HLIBCAMSENSOR_CONF_OPT = -DCROSS_COMPILE=$(BR2_TOOLCHAIN_EXTERNAL_PATH)/bin/$(BR2_TOOLCHAIN_EXTERNAL_CUSTOM_PREFIX)-	\
							-DPROC_DEBUG=Release
							
ifeq ($(BR2_PACKAGE_LIBISPV2500),y)
HLIBCAMSENSOR_CONF_OPT += -DCOMP_V2500=yes
endif

ifeq ($(BUILD_ALL_CAMERA_SENSORS),y)
HLIBCAMSENSOR_CONF_OPT += -DCOMP_ALL_SENSORS=yes
else ifeq ($(BUILD_SELECTED_SENSOR), y)
ifeq ($(IIFDG), y)
HLIBCAMSENSOR_CONF_OPT += -DIIFDG=yes
endif
ifeq ($(AR330_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DAR330_DVP=yes
endif
ifeq ($(AR330_MIPI), y)
HLIBCAMSENSOR_CONF_OPT += -DAR330_MIPI=yes
endif
ifeq ($(IMX322_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DIMX322_DVP=yes
endif
ifeq ($(IMX179_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DIMX179_DVP=yes
endif
ifeq ($(OV683_MIPI), y)
HLIBCAMSENSOR_CONF_OPT += -DOV683_MIPI=yes
endif
ifeq ($(OV2710_MIPI), y)
HLIBCAMSENSOR_CONF_OPT += -DOV2710_MIPI=yes
endif
ifeq ($(OV4689), y)
HLIBCAMSENSOR_CONF_OPT += -DOV4689=yes
endif
ifeq ($(OV4688), y)
HLIBCAMSENSOR_CONF_OPT += -DOV4688=yes
endif
ifeq ($(P401), y)
HLIBCAMSENSOR_CONF_OPT += -DP401=yes
endif
ifeq ($(SC2135_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DSC2135_DVP=yes
endif
ifeq ($(SC2235_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DSC2235_DVP=yes
endif
ifeq ($(SC1135_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DSC1135_DVP=yes
endif
ifeq ($(SC3035_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DSC3035_DVP=yes
endif
ifeq ($(STK3855_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DSTK3855_DVP=yes
endif
ifeq ($(NT99142_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DNT99142_DVP=yes
endif
ifeq ($(XC9080_MIPI), y)
HLIBCAMSENSOR_CONF_OPT += -DXC9080_MIPI=yes
endif

ifeq ($(DUAL_BRIDGE), y)
HLIBCAMSENSOR_CONF_OPT += -DDUAL_BRIDGE=yes
endif

endif

ifeq ($(BUILD_ALL_BRIDGE_SENSORS), y)
HLIBCAMSENSOR_CONF_OPT += -DCOMP_ALL_BRIDGE_SENSORS=yes
else ifeq ($(BUILD_SELECTED_BRIDGE_SENSOR), y)
ifeq ($(AR330_DUAL_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DAR330_DUAL_DVP=yes
endif
ifeq ($(NT99142_DUAL_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DNT99142_DUAL_DVP=yes
endif
ifeq ($(SC3035_DUAL_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DSC3035_DUAL_DVP=yes
endif
ifeq ($(HM2131_DUAL_MIPI), y)
HLIBCAMSENSOR_CONF_OPT += -DHM2131_DUAL_MIPI=yes
endif
ifeq ($(OV4689_DUAL_MIPI), y)
HLIBCAMSENSOR_CONF_OPT += -DOV4689_DUAL_MIPI=yes
endif
ifeq ($(H65_DUAL_MIPI), y)
HLIBCAMSENSOR_CONF_OPT += -DH65_DUAL_MIPI=yes
endif
ifeq ($(K02_DUAL_MIPI), y)
HLIBCAMSENSOR_CONF_OPT += -DK02_DUAL_MIPI=yes
endif
ifeq ($(IMX291_DUAL_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DIMX291_DUAL_DVP=yes
endif
endif

ifeq ($(BUILD_ALL_BRIDGE), y)
HLIBCAMSENSOR_CONF_OPT += -DCOMP_ALL_BRIDGE=yes
else ifeq ($(BUILD_SELECTED_BRIDGE), y)
ifeq ($(BRIDGE_SX2_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DBRIDGE_SX2_DVP=yes
endif
ifeq ($(BRIDGE_XC9080_MIPI), y)
HLIBCAMSENSOR_CONF_OPT += -DBRIDGE_XC9080_MIPI=yes
endif
ifeq ($(BRIDGE_OV683_MIPI), y)
HLIBCAMSENSOR_CONF_OPT += -DBRIDGE_OV683_MIPI=yes
endif
ifeq ($(BRIDGE_STK3855_DVP), y)
HLIBCAMSENSOR_CONF_OPT += -DBRIDGE_STK3855_DVP=yes
endif
endif

define HLIBCAMSENSOR_POST_INSTALL_STAGING
	cp -rfv $(HLIBCAMSENSOR_SRCDIR)/hlibcamsensor.pc $(STAGING_DIR)/usr/lib/pkgconfig/
	cp -rfv $(@D)/*.so $(STAGING_DIR)/usr/lib
endef

HLIBCAMSENSOR_POST_INSTALL_STAGING_HOOKS += HLIBCAMSENSOR_POST_INSTALL_STAGING

$(eval $(cmake-package))
