#!/bin/sh
#
# debug        debug
#

uvc_enable()
{
    modprobe g_webcam 
}

usb_ethernet_enable()
{
	modprobe g_ether
	ifconfig usb0 up
	ifconfig usb0 172.3.0.2
}

case "$1" in
  start)
    modprobe dwc_otg
    mount -t debugfs none /sys/kernel/debug
    # dwc_otg soft disconnect & connect
    echo 0 > /sys/kernel/debug/dwc_otg/link
    echo 1 > /sys/kernel/debug/dwc_otg/link

	echo 0 > /sys/bus/platform/drivers/dwc_otg/is_host

	echo 124 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio124/direction
	echo 0 > /sys/class/gpio/gpio124/value

	#modprobe g_infotm_cam file=/dev/spiblock2 removable=1
	#echo "" >  /sys/devices/platform/dwc_otg/gadget/lun0/file
	#modprobe g_webcam
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

