#! /bin/sh

case "$1" in
	start|"")
		modprobe Felix clkRate=198000000
        #below two module has been built-in kernel image
		#modprobe ddk_sensor 
		#modprobe vench2 g_clk=150000000
		videoboxd
        echo "--------->Videobox started<-----------"
		;;
	stop)
		killall videoboxd
		;;
	*)
		echo "Usage: videobox {start|stop}" >&2
		exit 1
		;;
esac

