obj-y += lcd_panel_params/
obj-y += lcd_panel.o

EXTRA_CFLAGS += -Idrivers/infotm/coronampw/display/common
EXTRA_CFLAGS += -Idrivers/infotm/coronampw/display/implementation/module/terminal/lcd_panel/lcd_panel_params
EXTRA_CFLAGS += -Idrivers/infotm/coronampw/display/implementation/module/interface/dev
