#! /bin/sh

case "$1" in
	start|"")
        echo 120 > /sys/class/gpio/export             
        echo "out" > /sys/class/gpio/gpio120/direction
        echo 1 > /sys/class/gpio/gpio120/value
		modprobe Felix clkRate=192000000
		modprobe ddk_sensor
		modprobe hx280enc_h1  g_h1_clk=360
		videoboxd
		;;
	stop)
		killall videoboxd
		;;
	*)
		echo "Usage: videobox {start|stop}" >&2
		exit 1
		;;
esac

