#! /bin/sh

case "$1" in
	start|"")
		modprobe hx280enc_h1 g_h1_clk=300
		modprobe Felix clkRate=256000000
        initpath=
        if [ -f "/mnt/config/.infotm_uvc_enable" ]; then 
            initpath="/root/.videobox/uvc.json"
        fi
		videoboxd $initpath
		;;
	stop)
		killall videoboxd
		;;
	*)
		echo "Usage: videobox {start|stop}" >&2
		exit 1
		;;
esac

