#
# Makefile for the Synopsys HDMI driver
#

obj-y	+= halHdcp.o
obj-y	+= hdcp.o
obj-y	+= hdcpParams.o
obj-y	+= hdcpVerify.o

EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/api
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/bsp
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/core
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/edid
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/hdcp
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/phy
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/util
