obj-y += lcd_panel_params/
obj-y += lcd_panel.o

EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/common
EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/implementation/module/terminal/lcd_panel/lcd_panel_params

