obj-y += lcd_port/
obj-y += hdmi/
obj-y += cvbs/
#obj-y += mipi/
obj-y += interface.o

EXTRA_CFLAGS += -Idrivers/infotm/common/display/common
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation

