obj-$(CONFIG_CTP_GSLX681)       += gslX681.o
obj-$(CONFIG_CTP_GSLX682)       += gslX682.o
obj-$(CONFIG_CTP_GSLX680_Q8)	+= gslX680_q8_kehai.o
obj-$(CONFIG_CTP_GT9147) += gt9xx.o  
obj-$(CONFIG_CTP_GT911) += gt911.o  
#obj-$(CONFIG_CTP_GSLX682)       += gsl_point_id.o
obj-y       += gsl_point_id.o
$(obj)/gsl_point_id.o:      $(srctree)/$(obj)/gsl_point_id   
	    cp $(srctree)/$(obj)/gsl_point_id   $(obj)/gsl_point_id.o



