#
# Makefile for the Synopsys HDMI driver
#

obj-y	+= colorimetryDataBlock.o
obj-y	+= dtd.o
obj-y	+= edid.o
obj-y	+= halEdid.o
obj-y	+= hdmivsdb.o
obj-y	+= monitorRangeLimits.o
obj-y	+= shortAudioDesc.o
obj-y	+= shortVideoDesc.o
obj-y	+= speakerAllocationDataBlock.o
obj-y	+= videoCapabilityDataBlock.o

EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/api
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/bsp
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/core
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/edid
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/hdcp
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/phy
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/util
