obj-y	+=cvbs.o gm7122.o 

obj-$(CONFIG_LCD_SPI_ILI8961)  += ili8961.o
obj-$(CONFIG_LCD_SPI_ILI9806S)  += ili9806s.o
obj-$(CONFIG_LCD_SPI_OTA5182A) += ota5182a.o

EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/common
EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/implementation/module/access
