obj-y += mipi_dsi.o
obj-y += synopsys_mipi_dsi_host/

EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/common
EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/implementation/module/access
EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/implementation/module/interface/mipi_dsi/synopsys_mipi_dsi_host
