#!/bin/sh
#mount -t vfat /dev/mmcblk1p1 /mnt
result=`ls /dev/mmcblk0p*`
var=0
event_mount="mount"
for point in $result 
do 
	mkdir /mnt/sd$var
	mount  $point  /mnt/sd$var
	eventsend $event_mount  $point
	let var+=1
done

exit 0
