/* Copyright 2013 Google Inc. All Rights Reserved.
 *
 * NAL unit type definitions. */

#ifndef HEVC_NAL_UNIT_TYPE_H_
#define HEVC_NAL_UNIT_TYPE_H_

enum NalUnitType {
  NAL_CODED_SLICE_TRAIL_N = 0,
  NAL_CODED_SLICE_TRAIL_R = 1,
  NAL_CODED_SLICE_TSA_N = 2,
  NAL_CODED_SLICE_TSA_R = 3,
  NAL_CODED_SLICE_STSA_N = 4,
  NAL_CODED_SLICE_STSA_R = 5,
  NAL_CODED_SLICE_RADL_N = 6,
  NAL_CODED_SLICE_RADL_R = 7,
  NAL_CODED_SLICE_RASL_N = 8,
  NAL_CODED_SLICE_RASL_R = 9,
  NAL_CODED_SLICE_BLA_W_LP = 16,
  NAL_CODED_SLICE_BLA_W_DLP = 17,
  NAL_CODED_SLICE_BLA_N_LP = 18,
  NAL_CODED_SLICE_IDR_W_LP = 19,
  NAL_CODED_SLICE_IDR_N_LP = 20,
  NAL_CODED_SLICE_CRA = 21,
  NAL_RSV_RAP_VCL22 = 22,
  NAL_RSV_RAP_VCL23 = 23,
  NAL_VIDEO_PARAM_SET = 32,
  NAL_SEQ_PARAM_SET = 33,
  NAL_PIC_PARAM_SET = 34,
  NAL_ACCESS_UNIT_DELIMITER = 35,
  NAL_END_OF_SEQUENCE = 36,
  NAL_END_OF_BITSTREAM = 37,
  NAL_FILLER_DATA = 38,
  NAL_PREFIX_SEI = 39,
  NAL_SUFFIX_SEI = 40,
  NAL_MAX_TYPE_VALUE = 63
};

#endif
