# Copyright 2013 Google Inc. All Rights Reserved.

# list of used sourcefiles
HEVC_SRCS += software/source/hevc/hevc_asic.c \
             software/source/hevc/hevc_byte_stream.c \
             software/source/hevc/hevcdecapi.c \
             software/source/hevc/hevc_decoder.c \
             software/source/hevc/hevc_dpb.c \
             software/source/hevc/hevc_fb_mngr.c \
             software/source/hevc/hevc_nal_unit.c \
             software/source/hevc/hevc_pic_order_cnt.c \
             software/source/hevc/hevc_pic_param_set.c \
             software/source/hevc/hevc_seq_param_set.c \
             software/source/hevc/hevc_slice_header.c \
             software/source/hevc/hevc_storage.c \
             software/source/hevc/hevc_util.c \
             software/source/hevc/hevc_exp_golomb.c \
             software/source/hevc/hevc_vui.c
