#                                                    
#  Makefile for the input core drivers.              
#                                                    
#  Each configuration option enables a list of files.
#                                                    
obj-$(CONFIG_APOLLO3_INPUT)   += keyboard/                                 

