set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER /nfs/dev/buildroot-2014.02/output/host/usr/bin/arm-buildroot-linux-uclibcgnueabihf-gcc)
set(CMAKE_CXX_COMPILER /nfs/dev/buildroot-2014.02/output/host/usr/bin/arm-buildroot-linux-uclibcgnueabihf-g++)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -pipe -O2 " CACHE STRING "Buildroot CFLAGS" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -pipe -O2 " CACHE STRING "Buildroot CXXFLAGS" FORCE)
set(CMAKE_INSTALL_SO_NO_EXE 0)
set(CMAKE_PROGRAM_PATH "/nfs/dev/buildroot-2014.02/output/host/usr/bin")
set(CMAKE_FIND_ROOT_PATH "/nfs/dev/buildroot-2014.02/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(ENV{PKG_CONFIG_SYSROOT_DIR} "/nfs/dev/buildroot-2014.02/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot")
