obj-$(CONFIG_INFOTM_DRV_IMAPX15)   += clk/
obj-$(CONFIG_INFOTM_POWER)	+= power/
obj-$(CONFIG_INFOTM_GPIO)	+= gpio/
obj-$(CONFIG_IMAPX15_INPUT)    += input/
obj-$(CONFIG_INFOTM_NAND)    += mtd/
obj-$(CONFIG_INFOTM_G2D)	+= g2d/
obj-$(CONFIG_INFOTM_EMIF)	+= emif/
#obj-$(CONFIG_INFOTM_ADC)	+= adc/
