 obj-$(CONFIG_Q3F_GPIO_KEYS)        += q3f_gpio_keys.o
 obj-$(CONFIG_Q3F_POWER_KEY_EC610)        += ec610-pwrkey.o
 obj-$(CONFIG_Q3F_POWER_KEY_IP6205)        += ip6205-pwrkey.o
 obj-$(CONFIG_Q3F_POWER_KEY_IP6208)        += ip6208-pwrkey.o
 obj-$(CONFIG_Q3F_POWER_KEY_IP6203)        += ip6203-pwrkey.o
 obj-$(CONFIG_Q3F_POWER_KEY_FPGA)        += fpga-pwrkey.o
