 obj-$(CONFIG_APOLLO3_GPIO_KEYS)        += apollo3_gpio_keys.o
 obj-$(CONFIG_APOLLO3_POWER_KEY_IP6313)        += ip6313-pwrkey.o
 obj-$(CONFIG_APOLLO3_POWER_KEY_IP6303)        += ip6303-pwrkey.o
 obj-$(CONFIG_APOLLO3_POWER_KEY_FPGA)        += fpga-pwrkey.o
