BOARD_WIFI_VENDOR := realtek
BOARD_WLAN_DEVICE := rtl8188eu
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_rtl
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_rtl

WIFI_DRIVER_MODULE_PATH := /system/modules/8188eu.ko
WIFI_DRIVER_MODULE_NAME := 8188eu
WIFI_DRIVER_MODULE_ARG := ifname=wlan0\ if2name=p2p0
WIFI_DRIVER_FW_PATH_STA := STA
WIFI_DRIVER_FW_PATH_AP := AP
WIFI_DRIVER_FW_PATH_P2P := P2P

BOARD_USES_GENERIC_AUDIO := false

BOARD_HAL_STATIC_LIBRARIES = libhealthd.$(TARGET_BOARD_PLATFORM)
