obj-y += osd_x15.o
EXTRA_CFLAGS += -Idrivers/infotm/q3f/display/common
EXTRA_CFLAGS += -Idrivers/infotm/q3f/display/implementation
EXTRA_CFLAGS += -Idrivers/infotm/q3f/display/implementation/module/access
EXTRA_CFLAGS += -Idrivers/infotm/q3f/display/implementation/module/controller

