snd-soc-imapx-es8328-objs := imapx_es8328.o
obj-$(CONFIG_SND_IMAPX_SOC_ES8328) += snd-soc-imapx-es8328.o

snd-soc-imapx-es8323-objs := imapx_es8323.o
obj-$(CONFIG_SND_IMAPX_SOC_ES8323) += snd-soc-imapx-es8323.o

snd-soc-imapx-alc5631-objs := imapx_alc5631.o
obj-$(CONFIG_SND_IMAPX_SOC_ALC5631) += snd-soc-imapx-alc5631.o

snd-soc-imapx-spdif-objs := imapx_spdif.o
obj-$(CONFIG_SND_IMAPX_SOC_SPDIF)	+= snd-soc-imapx-spdif.o

snd-soc-imapx_tqlp9624-objs := imapx_tqlp9624.o
obj-$(CONFIG_SND_IMAPX_SOC_TQLP9624)  += snd-soc-imapx_tqlp9624.o

snd-soc-imapx_fr1023-objs := imapx_fr1023.o
obj-$(CONFIG_SND_IMAPX_SOC_FR1023)  += snd-soc-imapx_fr1023.o

snd-soc-imapx_ip6205-objs := imapx_ip6205.o
obj-$(CONFIG_SND_IMAPX_SOC_IP6205)	+= snd-soc-imapx_ip6205.o

snd-soc-imapx_ip2906-objs := imapx_ip2906.o
obj-$(CONFIG_SND_IMAPX_SOC_IP2906)	+= snd-soc-imapx_ip2906.o
