obj-y += access.o
obj-y += clk.o
obj-y += init.o
obj-y += vic.o
obj-y += core/
obj-y += logo/
obj-y += framebuffer/
obj-y += osd/
obj-y += controller/
obj-y += peripherals/

EXTRA_CFLAGS += -Idrivers/infotm/common/display2/include
