obj-y += lcdc.o

EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/common
EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/implementation/module/access
EXTRA_CFLAGS += -Idrivers/infotm/imapx15/emif
EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/implementation/module/controller

