cmake_minimum_required(VERSION 2.8)

if(NOT DEFINED SIMIMAGE_PREFIX)
	# set FELIXLIB_PREFIX to directory where the current file file is located
	get_filename_component(SIMIMAGE_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
endif()

set (SIMIMAGE_FOUND TRUE)

if (NOT DEFINED SAVE_LOCKS)
    set(SAVE_LOCKS FALSE)
endif()

set (SIMIMAGE_INCLUDE_DIRS ${SIMIMAGE_PREFIX})
set (SIMIMAGE_DEFINITIONS -DPIXELSIZE=4)
set (SIMIMAGE_DOXYGEN_SRC ${SIMIMAGE_PREFIX})

if (SAVE_LOCKS)
	if(WIN32)
		find_package(PThreadWin32 REQUIRED)
	endif()

	set (SIMIMAGE_INCLUDE_DIRS ${SIMIMAGE_INCLUDE_DIRS} ${PTHREADWIN32_INCLUDE_DIRS})
	set (SIMIMAGE_DEFINITIONS ${SIMIMAGE_DEFINITIONS} ${PTHREADWIN32_DEFINITIONS} -DSAVE_LOCKS)
endif()

set (SIMIMAGE_NAME sim_image)
set (SIMIMAGE_LIBRARIES ${SIMIMAGE_NAME})
