obj-$(CONFIG_INFOTM_ADC) += adc/
obj-$(CONFIG_INFOTM_HWMON) += hwmon/
obj-$(CONFIG_INFOTM_PWM) += pwm/
obj-$(CONFIG_INFOTM_COMMON_DISPLAY) += display/
obj-$(CONFIG_INFOTM_BACKLIGHT) += backlight/

obj-$(CONFIG_INFOTM_MMC) += mmc/
obj-$(CONFIG_INFOTM_ITEM) += items/
obj-$(CONFIG_INFOTM_NORFALSH_FTL) += spi_ftl/
obj-$(CONFIG_INFOTM_LEDS) += leds/
obj-$(CONFIG_INFOTM_RTC) += rtc/
obj-$(CONFIG_INFOTM_I2C) += i2c/

#obj-$(CONFIG_INFOTM_DISPLAY) += display/
#obj-$(CONFIG_INFOTM_BACKLIGHT) += backlight/

obj-$(CONFIG_INFOTM_OTG) += otg/
obj-$(CONFIG_INFOTM_MEDIA_SUPPORT) += InfotmMedia/
obj-$(CONFIG_INFOTM_NET) += net/
obj-$(CONFIG_INFOTM_SOUND) += sound/
obj-$(CONFIG_INFOTM_BELT) += belt/
obj-$(CONFIG_INFOTM_SWITCH) += switch/
obj-$(CONFIG_INFOTM_GSENSOR) += sensor/
obj-$(CONFIG_INFOTM_TOUCHSCREEN) += touchscreen/
obj-$(CONFIG_INFOTM_VIDEO_CAPTURE) += camera/
obj-$(CONFIG_INFOTM_CPUFREQ) += dvfs/
obj-$(CONFIG_APOLLO_CPUFREQ) += dvfs_apollo/
obj-$(CONFIG_INFOTM_SPI) += spi/
obj-$(CONFIG_INFOTM_BT) += bt/
obj-$(CONFIG_INFOTM_FR) += fr/
obj-$(CONFIG_INFOTM_WDT) += watchdog/
obj-$(CONFIG_INFOTM_ENV) += env/
obj-$(CONFIG_INFOTM_POWER) += power/
obj-$(CONFIG_INFOTM_CMN1_TIMER) += timer/
obj-y += pr_detect/
#obj-$(CONFIG_INFOTM_DISPLAY2) += display2/
