obj-$(CONFIG_IMAPX910_CLK)  += clk.o
obj-$(CONFIG_IMAPX910_CLK)  += clk-bus.o
obj-$(CONFIG_IMAPX910_CLK)  += clk-cpu.o
obj-$(CONFIG_IMAPX910_CLK)  += clk-dev.o
obj-$(CONFIG_IMAPX910_CLK)  += clk-pll.o
obj-$(CONFIG_IMAPX910_CLK)  += clk-vitual.o
