obj-$(CONFIG_MACH_IMAPX910) += scaler_ids.o
obj-$(CONFIG_MACH_IMAPX15) += scaler_g2d.o
obj-y		+= scaler.o scaler_cpu.o

EXTRA_CFLAGS += -Idrivers/infotm/q3f/display/common
EXTRA_CFLAGS += -Idrivers/infotm/q3f/display/implementation
EXTRA_CFLAGS += -Idrivers/infotm/q3f/display/implementation/module/access
EXTRA_CFLAGS += -Idrivers/infotm/q3f/display/implementation/module/controller
EXTRA_CFLAGS += -Idrivers/infotm/q3f/display/implementation/module/scaler
