#obj-$(CONFIG_MACH_IMAPX800) += platform_x15.o


# Temp for lighten lcd
obj-y += platform_x15.o

EXTRA_CFLAGS += -Idrivers/infotm/q3f/display/common
EXTRA_CFLAGS += -Idrivers/infotm/q3f/display/implementation

