# videobox

VIDEOBOX_VERSION = 1.0.0
VIDEOBOX_SOURCE =
VIDEOBOX_SITE  =

VIDEOBOX_LICENSE =
VIDEOBOX_LICENSE_FILES = README

VIDEOBOX_MAINTAINED = YES
VIDEOBOX_AUTORECONF = YES
VIDEOBOX_INSTALL_STAGING = YES
VIDEOBOX_MAKE = make -s
VIDEOBOX_DEPENDENCIES = host-pkgconf hlibfr eventhub hlibitems qlibsys

ifeq ($(BR2_PACKAGE_VIDEOBOX_DGPIXEL),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_DGPIXEL=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_DGFRAME),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_DGFRAME=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_DGMATH),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_DGMATH=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_DGOV),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_DGOV=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_V2500),y)
	VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_V2500=yes
	VIDEOBOX_DEPENDENCIES += hlibispv2500
	VIDEOBOX_DEPENDENCIES += hlibcamsensor

	ifeq ($(BR2_PACKAGE_VIDEOBOX_V2500_IQ_REALTIME_SAVE_RAW),y)
		VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_V2500_IQ_REALTIME_SAVE_RAW=yes
	endif
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_V2505),y)
	VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_V2505=yes
	VIDEOBOX_DEPENDENCIES += hlibispv2505
	VIDEOBOX_DEPENDENCIES += hlibcamsensor
	ifeq ($(BR2_PACKAGE_VIDEOBOX_V2505_HW_AWB),y)
		VIDEOBOX_CONF_OPT += -DINFOTM_V2505_HW_AWB=yes
	endif
	ifeq ($(BR2_PACKAGE_VIDEOBOX_V2505_HW_BLENDING_8ALPHA),y)
		VIDEOBOX_CONF_OPT += -DINFOTM_V2505_BLEND_8STEP_ALPHA=yes
	endif
	ifeq ($(BR2_PACKAGE_VIDEOBOX_V2505_HW_BLENDING),y)
		VIDEOBOX_CONF_OPT += -DINFOTM_V2505_HW_BLENDING=yes
	endif
	ifeq ($(BR2_PACKAGE_VIDEOBOX_V2505_IQ_REALTIME_SAVE_RAW),y)
		VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_V2505_IQ_REALTIME_SAVE_RAW=yes
	endif
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_ISP),y)
	VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_ISP=yes
	VIDEOBOX_DEPENDENCIES += hlibcamsensor
	ifeq ($(BR2_PACKAGE_ISP_V2500),y)
		VIDEOBOX_DEPENDENCIES += hlibispv2500
		VIDEOBOX_CONF_OPT += -DCOMPILE_ISP_V2500=yes
	endif
	ifeq ($(BR2_PACKAGE_ISP_V2505),y)
		VIDEOBOX_DEPENDENCIES += hlibispv2505
		VIDEOBOX_CONF_OPT += -DCOMPILE_ISP_V2505=yes

		ifeq ($(BR2_PACKAGE_VIDEOBOX_V2505_HW_BLENDING),y)
			VIDEOBOX_CONF_OPT += -DINFOTM_V2505_HW_BLENDING=yes
		endif
                ifeq ($(BR2_PACKAGE_VIDEOBOX_V2505_AWB_ALG_PLANCKIAN),y)
                        VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_V2505_AWB_ALG_PLANCKIAN=yes
                endif
	endif
	ifeq ($(BR2_PACKAGE_VIDEOBOX_V2505_HW_AWB),y)
		VIDEOBOX_CONF_OPT += -DINFOTM_V2505_HW_AWB=yes
	endif
	ifeq ($(BR2_PACKAGE_VIDEOBOX_V2505_HW_BLENDING_8ALPHA),y)
		VIDEOBOX_CONF_OPT += -DINFOTM_V2505_BLEND_8STEP_ALPHA=yes
	endif
	ifeq ($(BR2_PACKAGE_VIDEOBOX_ISP_IQ_REALTIME_SAVE_RAW),y)
		VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_ISP_IQ_REALTIME_SAVE_RAW=yes
	endif
        ifeq ($(BR2_PACKAGE_VIDEOBOX_V2505_AWB_ALG_PLANCKIAN),y)
                VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_V2505_AWB_ALG_PLANCKIAN=yes
        endif
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_CAMV4L2),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_V4L2=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_SOFTLAYER),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_SOFTLAYER=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_FILESINK),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_FILESINK=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_FILESOURCE),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_FILESOURCE=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_H2),y)
VIDEOBOX_DEPENDENCIES += hlibh2v1
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_H2=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_H2V4),y)
VIDEOBOX_DEPENDENCIES += hlibh2v4
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_H2V4=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_VENCODER_H2),y)
VIDEOBOX_DEPENDENCIES += hlibh2v1
VIDEOBOX_CONF_OPT += -DVENCODER_DEPEND_H2V1=yes
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_VENCODER=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_VENCODER_H2V4),y)
VIDEOBOX_DEPENDENCIES += hlibh2v4
VIDEOBOX_CONF_OPT += -DVENCODER_DEPEND_H2V4=yes
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_VENCODER=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_G2),y)
VIDEOBOX_DEPENDENCIES += hlibg2v1
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_G2=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_IDS),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_IDS=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_IDS2),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_IDS2=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_VAMOVEMENT),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_VAMOVEMENT=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_MVMOVEMENT),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_MVMOVEMENT=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_PP),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_PP=yes
VIDEOBOX_DEPENDENCIES += hlibg1v6
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_G1264),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_G1264=yes
VIDEOBOX_DEPENDENCIES += hlibg1v6
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_G1JDEC),y)
	VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_G1JDEC=yes
	VIDEOBOX_DEPENDENCIES += hlibg1v6
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_H1JPEG),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_H1JPEG=yes
VIDEOBOX_DEPENDENCIES += hlibh1v6

ifeq ($(BR2_PACKAGE_VIDEOBOX_H1JPEG_SWSCALE), y)
    VIDEOBOX_CONF_OPT += -DCOMPILE_H1JPEG_SWSCALE=yes
    VIDEOBOX_DEPENDENCIES += qlibmediautils
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_H1JPEG_CROP), y)
    VIDEOBOX_CONF_OPT += -DCOMPILE_H1JPEG_CROP=yes
    VIDEOBOX_DEPENDENCIES += qlibmediautils
endif

endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_H1264),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_H1264=yes
VIDEOBOX_DEPENDENCIES += hlibh1v6
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_VENCODER_H1264),y)
VIDEOBOX_DEPENDENCIES += hlibh1v6
VIDEOBOX_CONF_OPT += -DVENCODER_DEPEND_H1V6=yes
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_VENCODER=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_JENC),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_JENC=yes
VIDEOBOX_DEPENDENCIES += hlibjenc

ifeq ($(BR2_PACKAGE_VIDEOBOX_JENC_SWSCALE), y)
	VIDEOBOX_CONF_OPT += -DCOMPILE_JENC_SWSCALE=yes
	VIDEOBOX_DEPENDENCIES += qlibmediautils
endif

endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_FFVDEC),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_FFVDEC=yes
VIDEOBOX_DEPENDENCIES += libffmpeg
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_ISPOSTV1),y)
	VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_ISPOSTV1=yes
	VIDEOBOX_DEPENDENCIES += hlibispostv1
	ifeq ($(BR2_PACKAGE_VIDEOBOX_ISPOSTV1_FCE),y)
		VIDEOBOX_DEPENDENCIES += libgridtools 
		VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_ISPOSTV1_FCE=yes
		VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_ISPOSTV1_FCE_PARA=$(BR2_PACKAGE_VIDEOBOX_ISPOSTV1_FCE_PARA)
	endif
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_ISPOSTV2),y)
	VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_ISPOSTV2=yes
	VIDEOBOX_DEPENDENCIES += hlibispostv2
	VIDEOBOX_DEPENDENCIES += libmneon
	ifeq ($(BR2_PACKAGE_VIDEOBOX_ISPOSTV2_FCE),y)
		VIDEOBOX_DEPENDENCIES += libgridtools 
		VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_ISPOSTV2_FCE=yes
		VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_ISPOSTV2_FCE_PARA=$(BR2_PACKAGE_VIDEOBOX_ISPOSTV2_FCE_PARA)
	endif
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_FODETV2),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_FODETV2=yes
VIDEOBOX_DEPENDENCIES += hlibfodetv2
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_VAQRSCANNER),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_VAQRSCANNER=yes
VIDEOBOX_DEPENDENCIES += libzbar
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_MARKER),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_MARKER=yes
VIDEOBOX_DEPENDENCIES += libiconv

ifeq ($(BR2_ENABLE_FREETYPE),y)
VIDEOBOX_DEPENDENCIES += libfreetype
VIDEOBOX_CONF_OPT += -DCOMPILE_LIB_FREETYPE=yes
else
# uninstall
define VIDEOBOX_POST_INSTALL_TARGET_LIBS
	rm -rf $(TARGET_DIR)/usr/lib/libfreetype*
endef
endif

endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_SOFTLAYER),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_SOFTLAYER=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_TFESTITCHER),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_TFESTITCHER=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_BADENCODER),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_BADENCODER=yes
VIDEOBOX_DEPENDENCIES += hlibh1v6
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_FFPHOTO),y)
    VIDEOBOX_DEPENDENCIES += libffmpeg
    VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_FFPHOTO=yes
    ifeq ($(BR2_PACKAGE_VIDEOBOX_FFPHOTO_SWSCALE),y)
        VIDEOBOX_CONF_OPT += -DCOMPILE_FFPHOTO_SWSCALE=yes
    endif
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_SWC),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_SWC=yes
VIDEOBOX_DEPENDENCIES += hlibg1v6
VIDEOBOX_DEPENDENCIES += hlibispostv1
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_IQ_TUNING_TOOL_APIS),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IQ_TUNING_TOOL_APIS=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_ISPLUS),y)
	VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_ISPLUS=yes
	VIDEOBOX_DEPENDENCIES += hlibispostv2
	VIDEOBOX_DEPENDENCIES += libmneon
	VIDEOBOX_DEPENDENCIES += hlibispv2505
	VIDEOBOX_DEPENDENCIES += hlibcamsensor
	ifeq ($(BR2_PACKAGE_VIDEOBOX_ISPLUS_FCE),y)
		VIDEOBOX_DEPENDENCIES += libgridtools
		VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_ISPLUS_FCE=yes
		VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_ISPLUS_FCE_PARA=$(BR2_PACKAGE_VIDEOBOX_ISPLUS_FCE_PARA)
	endif
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_ISPOSTV1_IQ_TUNING_TOOL_APIS),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_ISPOSTV1_IQ_TUNING_TOOL_APIS=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_ISPOSTV2_IQ_TUNING_TOOL_APIS),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_ISPOSTV2_IQ_TUNING_TOOL_APIS=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_BUFSYNC),y)
VIDEOBOX_CONF_OPT += -DCOMPILE_IPU_BUFSYNC=yes
endif

ifeq ($(BR2_PACKAGE_VIDEOBOX_OPTIMIZATION), y)
VIDEOBOX_CONF_OPT += -DCOMPILE_VIDEOBOX_OPTIMIZATION=yes
endif

# install headers
define VIDEOBOX_POST_INSTALL_STAGING_HEADERS
	mkdir -p $(STAGING_DIR)/usr/include/qsdk
	mkdir -p $(STAGING_DIR)/usr/lib/pkgconfig
	cp -rfv $(VIDEOBOX_SRCDIR)/lib/include/qsdk/*.h  $(STAGING_DIR)/usr/include/qsdk
	cp -rfv $(VIDEOBOX_SRCDIR)/lib/videobox.pc  $(STAGING_DIR)/usr/lib/pkgconfig/

	mkdir -p $(TARGET_DIR)/root/.videobox
	cp -rfv $(VIDEOBOX_SRCDIR)/test/paths/demos/dual_720_1080.json $(TARGET_DIR)/root/.videobox/path.json
endef

VIDEOBOX_POST_INSTALL_STAGING_HOOKS  += VIDEOBOX_POST_INSTALL_STAGING_HEADERS

VIDEOBOX_POST_INSTALL_TARGET_HOOKS += VIDEOBOX_POST_INSTALL_TARGET_LIBS

$(eval $(cmake-package))
