include drivers/infotm/common/InfotmMedia/env.mk
EXTRA_CFLAGS += -Idrivers/infotm/common/InfotmMedia/utlz_lib/include
EXTRA_CFLAGS += -Idrivers/infotm/common/InfotmMedia/include

obj-$(CONFIG_INFOTM_ISP) += imapx_isp.o
imapx_isp-y := isp_core.o isp_reg.o isp_crop.o isp_scl.o isp_ief.o isp_ee.o isp_acc.o isp_acm.o

