#!/bin/sh
#
# Start mdev....
#

case "$1" in
  start)
	echo "Starting mdev new..."
	echo /sbin/mdev >/proc/sys/kernel/hotplug
	echo 1150000 > /sys/class/regulator/regulator.1/microvolts
	/sbin/mdev -s
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
