obj-y += logo_bmp.o

EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/common
EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/abstraction   
EXTRA_CFLAGS += -Idrivers/infotm/apollo/display/implementation

