obj-y += lcdc.o

EXTRA_CFLAGS += -Idrivers/infotm/coronampw/display/common
EXTRA_CFLAGS += -Idrivers/infotm/coronampw/display/implementation/module/access
EXTRA_CFLAGS += -Idrivers/infotm/coronampw/emif

