include drivers/infotm/common/InfotmMedia/env.mk
EXTRA_CFLAGS += -Idrivers/infotm/common/InfotmMedia/utlz_lib/include
EXTRA_CFLAGS += -Idrivers/infotm/common/InfotmMedia/include
EXTRA_CFLAGS += -Idrivers/infotm/common/sensors/
obj-$(CONFIG_INFOTM_CAMIF) += imapx_camif.o
imapx_camif-y :=camif_core.o camif_reg.o

