obj-$(CONFIG_Q3F_REGULATOR_EC610)      += ec610-regulator.o
obj-$(CONFIG_Q3F_REGULATOR_IP6203)      += ip6203-regulator.o
obj-$(CONFIG_Q3F_REGULATOR_IP620x)      += ip620x-regulator.o
obj-$(CONFIG_Q3F_REGULATOR_IP6303)      += ip6303-regulator.o
