# audiobox

AUDIOBOX_VERSION = 1.0.0
AUDIOBOX_SOURCE = 
AUDIOBOX_SITE  = 

AUDIOBOX_LICENSE = 
AUDIOBOX_LICENSE_FILES = README

AUDIOBOX_MAINTAINED = YES
AUDIOBOX_AUTORECONF = YES
AUDIOBOX_INSTALL_STAGING = YES
VIDEOBOX_MAKE = make -s
AUDIOBOX_DEPENDENCIES = host-pkgconf hlibfr eventhub alsa-lib hlibvcp7g

ifeq ($(BR2_PACKAGE_HLIBVCP7G_DSP_SUPPORT),y)
AUDIOBOX_DEPENDENCIES += hlibdsp
AUDIOBOX_DEPENDENCIES += libcodecs
#AUDIOBOX_CONF_OPT += -DCOMPILE_IPU_DGOV=yes
endif

ifeq ($(BR2_PACKAGE_HLIBDSP_AECV1), y)
AUDIOBOX_CONF_OPT +=-DCOMPILE_AUDIOBOX_USE_AECV1=yes
endif

ifeq ($(BR2_PACKAGE_HLIBDSP_AECV2), y)
AUDIOBOX_CONF_OPT +=-DCOMPILE_AUDIOBOX_USE_AECV2=yes
endif

ifeq ($(BR2_PACKAGE_HLIBVCP7G_ARM_SUPPORT),y)
AUDIOBOX_DEPENDENCIES += libcodecs
endif

ifeq ($(BR2_PACKAGE_AUDIOBOX_OPTIMIZATION), y)
AUDIOBOX_CONF_OPT += -DCOMPILE_AUDIOBOX_OPTIMIZATION=yes
endif

define AUDIOBOX_POST_INSTALL_STAGING_HEADERS
	mkdir -p $(STAGING_DIR)/usr/include/qsdk
	mkdir -p $(STAGING_DIR)/usr/lib/pkgconfig
	cp -rfv $(AUDIOBOX_SRCDIR)/include/audiobox.h  $(STAGING_DIR)/usr/include/qsdk
	cp -rfv $(AUDIOBOX_SRCDIR)/audiobox.pc  $(STAGING_DIR)/usr/lib/pkgconfig/
endef

AUDIOBOX_POST_INSTALL_STAGING_HOOKS += AUDIOBOX_POST_INSTALL_STAGING_HEADERS

$(eval $(cmake-package))

