#
# Makefile for the kernel multimedia device drivers.
#

include drivers/infotm/common/InfotmMedia/env.mk

EXTRA_CFLAGS += -Idrivers/infotm/common/InfotmMedia/include
EXTRA_CFLAGS += -Idrivers/infotm/common/InfotmMedia/utlz_lib/include
EXTRA_CFLAGS += -Idrivers/infotm/common/InfotmMedia/utlz_lib/source

obj-y += utlz_lib.o
obj-y += utlz_pwl_linux.o

#EXTRA_CFLAGS += -DIM_DEBUG

