#ifndef NAMES_H
#define NAMES_H

namespace VisionLive
{

#define NAME_MAINWINDOW_MENUBAR_FILEMENU "File"
#define NAME_MAINWINDOW_MENUBAR_CONNECTIONMENU "Connection"
#define NAME_MAINWINDOW_MENUBAR_VIEWMENU "View"
#define NAME_MAINWINDOW_MENUBAR_STYLESHEETMENU "Set Style Sheet"
#define NAME_MAINWINDOW_MENUBAR_STYLESHEETMENU_DEFAULTACTION "Default"
#define NAME_MAINWINDOW_MENUBAR_STYLESHEETMENU_CUSTOMACTION "Custom"
#define NAME_MAINWINDOW_MENUBAR_MODULEACCESSMENU "Module Access"
#define NAME_MAINWINDOW_MENUBAR_HELPENU "Help"

#define NAME_MAINWINDOW_LOGVIEW_ERRORLOG "Error"
#define NAME_MAINWINDOW_LOGVIEW_WARNINGLOG "Warning"
#define NAME_MAINWINDOW_LOGVIEW_INFOLOG "Info"
#define NAME_MAINWINDOW_LOGVIEW_ACTIONLOG "Action"

#define NAME_TABLOGVIEW_LOG_TYPE_ERROR "Error"
#define NAME_TABLOGVIEW_LOG_TYPE_WARNING "Warning"
#define NAME_TABLOGVIEW_LOG_TYPE_MESSAGE "Message"

} // namepsace VisionLive

#endif // NAMES_H
