#ifndef __IMAPX800_ISP_H__
#define __IMAPX800_ISP_H__
// <path/to/>Q3_fpga_sportDv/linux/arch/arm/mach-apollo/include/mach/imap-isp.h

#define IMAP_ISP_BASE       0x22000000
#define IMAP_ISP_SIZE       SZ_1M

// ISP base address
#define ISP_PERI_BASE_ADDR                IMAP_ISP_BASE

// ISP page address
#define ISP_FELIX_CORE_PAGE_ADDR            (ISP_PERI_BASE_ADDR + 0x0000)

#define ISP_FELIX_GAMMA_LUT_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0x0C00)

#define ISP_FELIX_CONTEXT_0_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0x1000)
#define ISP_FELIX_CONTEXT_1_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0x2000)
#define ISP_FELIX_CONTEXT_2_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0x3000)
#define ISP_FELIX_CONTEXT_3_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0x4000)
#define ISP_FELIX_CONTEXT_4_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0x5000)
#define ISP_FELIX_CONTEXT_5_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0x6000)
#define ISP_FELIX_CONTEXT_6_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0x7000)
#define ISP_FELIX_CONTEXT_7_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0x8000)
#define ISP_FELIX_CONTEXT_MAX               (2)
#define ISP_FELIX_CONTEXT_OFFSET            (ISP_FELIX_CONTEXT_1_PAGE_ADDR - ISP_FELIX_CONTEXT_0_PAGE_ADDR)

#define ISP_FELIX_MMU_PAGE_ADDR             (ISP_PERI_BASE_ADDR + 0x9000)

#define ISP_FELIX_DG_IIF_PAGE_ADDR          (ISP_PERI_BASE_ADDR + 0xA000)

#define ISP_FELIX_SCB_PAGE_ADDR             (ISP_PERI_BASE_ADDR + 0xB000)

#define ISP_FELIX_GASKET_00_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xC000)
#define ISP_FELIX_GASKET_01_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xC200)
#define ISP_FELIX_GASKET_02_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xC400)
#define ISP_FELIX_GASKET_03_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xC600)
#define ISP_FELIX_GASKET_04_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xC800)
#define ISP_FELIX_GASKET_05_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xCA00)
#define ISP_FELIX_GASKET_06_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xCC00)
#define ISP_FELIX_GASKET_07_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xCE00)
#define ISP_FELIX_GASKET_08_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xD000)
#define ISP_FELIX_GASKET_09_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xD200)
#define ISP_FELIX_GASKET_10_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xD400)
#define ISP_FELIX_GASKET_11_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xD600)
#define ISP_FELIX_GASKET_12_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xD800)
#define ISP_FELIX_GASKET_13_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xDA00)
#define ISP_FELIX_GASKET_14_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xDC00)
#define ISP_FELIX_GASKET_15_PAGE_ADDR       (ISP_PERI_BASE_ADDR + 0xDE00)
#define ISP_FELIX_GASKET_MAX                (3)
#define ISP_FELIX_GASKET_OFFSET             (ISP_FELIX_GASKET_01_PAGE_ADDR - ISP_FELIX_GASKET_00_PAGE_ADDR)

#define ISP_FELIX_AXI_PAGE_ADDR             (ISP_PERI_BASE_ADDR + 0xDFF0)

#define ISP_FELIX_TEST_DG_00_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xE000)
#define ISP_FELIX_TEST_DG_01_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xE200)
#define ISP_FELIX_TEST_DG_02_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xE400)
#define ISP_FELIX_TEST_DG_03_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xE600)
#define ISP_FELIX_TEST_DG_04_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xE800)
#define ISP_FELIX_TEST_DG_05_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xEA00)
#define ISP_FELIX_TEST_DG_06_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xEC00)
#define ISP_FELIX_TEST_DG_07_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xEE00)
#define ISP_FELIX_TEST_DG_08_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xF000)
#define ISP_FELIX_TEST_DG_09_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xF200)
#define ISP_FELIX_TEST_DG_10_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xF400)
#define ISP_FELIX_TEST_DG_11_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xF600)
#define ISP_FELIX_TEST_DG_12_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xF800)
#define ISP_FELIX_TEST_DG_13_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xFA00)
#define ISP_FELIX_TEST_DG_14_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xFC00)
#define ISP_FELIX_TEST_DG_15_PAGE_ADDR      (ISP_PERI_BASE_ADDR + 0xFE00)
#define ISP_FELIX_TEST_DG_MAX               (0)
#define ISP_FELIX_TEST_DG_OFFSET            (ISP_FELIX_TEST_DG_01_PAGE_ADDR - ISP_FELIX_TEST_DG_00_PAGE_ADDR)

#define ISP_FELIX_TEST_MMU_PAGE_ADDR        (ISP_PERI_BASE_ADDR + 0x10000)

#define ISP_FELIX_TEST_IO_PAGE_ADDR         (ISP_PERI_BASE_ADDR + 0x12000)

#define ISP_FELIX_GASKET_PHY_0_PAGE_ADDR    (ISP_PERI_BASE_ADDR + 0x11000)
//#define ISP_FELIX_GASKET_PHY_1_PAGE_ADDR    (ISP_PERI_BASE_ADDR + 0x11200)
//#define ISP_FELIX_GASKET_PHY_2_PAGE_ADDR    (ISP_PERI_BASE_ADDR + 0x11400)


// System Core page.
#define CORE_CORE_ID_OFFSET                 (0x0000)
#define CORE_CORE_ID_2_OFFSET               (0x0004)
#define CORE_CORE_REVISION_OFFSET           (0x0010)
#define CORE_UID_NUM_OFFSET                 (0x0014)
#define CORE_DESIGNER_REV_FIELD_1_OFFSET    (0x0020)
#define CORE_DESIGNER_REV_FIELD_2_OFFSET    (0x0030)
#define CORE_HDF_CONTEXTS_SUPPORTED_OFFSET  (0x0034)
#define CORE_MAX_ACTIVE_WIDTH_OFFSET        (0x0038)
#define CORE_DPF_READ_MAP_FIFO_SIZE_OFFSET  (0x003C)
#define CORE_DESIGNER_REV_FIELD_3_OFFSET    (0x0040)
#define CORE_FELIX_CONTROL_OFFSET           (0x0050)
#define CORE_FELIX_PWR_CTRL_OFFSET          (0x0054)
#define CORE_FELIX_PWR_STATUS_OFFSET        (0x0058)
#define CORE_CORE_RESET_OFFSET              (0x005C)
#define CORE_ENC_OUT_CTRL_OFFSET            (0x0060)
#define CORE_DE_CTRL_OFFSET                 (0x0064)
#define CORE_FELIX_INTERRUPT_SOURCE_OFFSET  (0x0068)
#define CORE_FELIX_TS_COUNTER_OFFSET        (0x006C)
#define CORE_DI_CTRL_OFFSET                 (0x0070)
#define CORE_DI_SIZE_OFFSET                 (0x0074)
#define CORE_DI_PIXEL_RATE_OFFSET           (0x0078)
#define CORE_DI_LINK_ADDR_OFFSET            (0x007C)
#define CORE_DI_TAG_OFFSET                  (0x0080)
#define CORE_DI_ADDR_Y_OFFSET               (0x0084)
#define CORE_DI_ADDR_Y_STRIDE_OFFSET        (0x0088)
#define CORE_DI_ADDR_C_OFFSET               (0x008C)
#define CORE_DI_ADDR_C_STRIDE_OFFSET        (0x0090)
#define CORE_DEBUG_ACTIVE_BLOCKS_OFFSET     (0x0094)
#define CORE_FELIX_PWR_CTRL_2_OFFSET        (0x0100)
#define CORE_FELIX_PWR_STATUS_2_OFFSET      (0x0104)
#define CORE_DESIGNER_REV_FILEDS_EXTEND_OFFSET (0x0120)	// From 0x0120-0x015F
#define CORE_MAX_DESIGNER_REV_FILEDS_EXTEND (16)
#define CORE_RTM_A_CTRL_OFFSET              (0x0200)
#define CORE_RTM_A_EXT_CTRL_OFFSET          (0x0204)
#define CORE_RTM_A_OFFSET                   (0x0208)
#define CORE_RTM_B_CTRL_OFFSET              (0x020C)
#define CORE_RTM_B_EXT_CTRL_OFFSET          (0x0210)
#define CORE_RTM_B_OFFSET                   (0x0214)
#define CORE_DEBUG_DRIVER_INFO_OFFSET       (0x0300)	// From 0x0300-0x033F
#define CORE_MAX_DEBUG_DRIVER_INFO          (16)
#define CORE_MMU_RESP_STALL_CTRL_OFFSET     (0x0500)
#define CORE_REQ_CMD_STALL_OFFSET           (0x0504)
#define CORE_MMU_CMD_STALL_CTRL_OFFSET      (0x0600)	// From 0x0600-0x0623
#define CORE_MAX_MMU_CMD_STALL_CTRL         (9)
#define CORE_DEBUG_GRP_0_OFFSET             (0x0700)
#define CORE_DEBUG_GRP_1_OFFSET             (0x0704)
#define CORE_DEBUG_GRP_2_OFFSET             (0x0708)
#define CORE_DEBUG_GRP_3_OFFSET             (0x070C)
#define CORE_DEBUG_GRP_4_OFFSET             (0x0710)
#define CORE_DEBUG_GRP_5_OFFSET             (0x0714)
#define CORE_DEBUG_GRP_6_OFFSET             (0x0718)
#define CORE_FPGA_BUILD_OFFSET              (0x07FC)

#define CORE_FELIX_INTERRUPT_SOURCE_CONTEXT_FIELD   (0x000000ff)
#define CORE_FELIX_INTERRUPT_SOURCE_MMU_FIELD       (0x00000100)
#define CORE_FELIX_INTERRUPT_SOURCE_DG_IIF_FIELD    (0x00000200)
#define CORE_FELIX_INTERRUPT_SOURCE_DG_TEST_FIELD   (0xff000000)

// Context page.
#define CNTXT_INTERRUPT_STATUS_OFFSET               (0x0008)
#define CNTXT_INTERRUPT_ENABLE_OFFSET               (0x000C)
#define CNTXT_INTERRUPT_CLEAR_OFFSET                (0x0010)
#define CNTXT_FELIX_CONTEXT_MEMORY_CONTROL_2_OFFSET (0x0048)
#define CNTXT_CONTEXT_LINK_EMPTYNESS_OFFSET         (0x0050)
#define CNTXT_SAVE_CONFIG_FLAGS_OFFSET              (0x00C0)
#define CNTXT_DPF_SENSITIVITY_OFFSET                (0x022C)
#define CNTXT_MGM_CLIP_IN_OFFSET                    (0x027C)
#define CNTXT_MGM_CORE_IN_OUT_OFFSET                (0x0280)
#define CNTXT_MGM_SLOPE_0_1_OFFSET                  (0x0284)
#define CNTXT_MGM_SLOPE_2_R_OFFSET                  (0x0288)
#define CNTXT_TNM_BYPASS_OFFSET                     (0x0458)
#define CNTXT_FLD_TH_OFFSET                         (0x0488)
#define CNTXT_FLD_SCENE_CHANGE_TH_OFFSET            (0x048C)
#define CNTXT_FLD_DFT_OFFSET                        (0x0490)
#define CNTXT_SHA_PARAMS_0_OFFSET                   (0x0498)
#define CNTXT_DGM_CLIP_IN_OFFSET                    (0x05D8)
#define CNTXT_DGM_CORE_IN_OUT_OFFSET                (0x05DC)
#define CNTXT_DGM_SLOPE_0_1_OFFSET                  (0x05E0)
#define CNTXT_DGM_SLOPE_2_R_OFFSET                  (0x05E4)

#define MMU_MMU_CONTROL0_OFFSET             (0x0000)
#define MMU_MMU_CONTROL1_OFFSET             (0x0004)
#define MMU_MMU_ADDRESS_CONTROL_OFFSET      (0x0070)
#define MMU_MMU_STATUS_0_OFFSET             (0x0088)
#define MMU_MMU_STATUS_1_OFFSET             (0x008C)

#define MMU_MMU_FAULT_CLEAR_FIELD           (0x0100)

// Data generator image interface page.
#define DG_IIF_DG_INTER_STATUS_OFFSET       (0x0030)
#define DG_IIF_DG_INTER_ENABLE_OFFSET       (0x0034)
#define DG_IIF_DG_INTER_CLEAR_OFFSET        (0x0038)
#define DG_IIF_MIPI_CRTL_OFFSET             (0x0050)

// AXI page.
#define AXI_FELIX_AXI_OFFSET                (0x0004)



#endif //__IMAPX800_ISP_H__
