obj-y += logo_bmp.o

EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/common
EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/abstraction
EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/implementation

