#ifndef __IMAPX_GTIMER_H__
#define __IMAPX_GTIMER_H__

#define PRI_TIMER_CLK		(15000000)
#define PRI_TIMER_REG_MAX	(0xFFFFFFFE)


/* g-timer for Cortex-A5 */

#define GTIMER_CNTR_LOWER		(GTIMER_BASE_ADDR + 0x0)
#define GTIMER_CNTR_UPPER		(GTIMER_BASE_ADDR + 0x4)
#define GTIMER_CTLR				(GTIMER_BASE_ADDR + 0x8)
#define GTIMER_INTSTR			(GTIMER_BASE_ADDR + 0xc)
#define GTIMER_COMPVALR_LOWER	(GTIMER_BASE_ADDR + 0x10)
#define GTIMER_COMPVALR_UPPER	(GTIMER_BASE_ADDR + 0x14)
#define GTIMER_AUTOINCRESMENT	(GTIMER_BASE_ADDR + 0x18)

#endif /*__IMAPX_GTIMER_H__*/
