obj-y += synopsys_hdmi_tx_1.4a/
obj-y += hdmi.o hdmi_audio.o

EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/common
EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/implementation/module/access
EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/api
EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/bsp
EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/core
EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/edid
EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/hdcp
EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/phy
EXTRA_CFLAGS += -Idrivers/infotm/apollo3/display/implementation/module/interface/hdmi/synopsys_hdmi_tx_1.4a/util

