obj-$(CONFIG_INFOTM_DRV_IMAPX910)	+= mfd/ regulator/ power/ clk/
obj-$(CONFIG_IMAPX910_INPUT)	+= input/
obj-$(CONFIG_INFOTM_GPIO)		+= gpio/
obj-$(CONFIG_INFOTM_MTD)        += mtd/
obj-$(CONFIG_IMAPX910_HWMON)    += hwmon/
obj-y					+= power_domain/
