obj-y += osd_x15.o
#obj-$(CONFIG_MACH_IMAPX15) += osd_x15.o
#obj-$(CONFIG_MACH_IMAPX910) += osd_x9.o
EXTRA_CFLAGS += -Idrivers/infotm/common/display/common
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/access
EXTRA_CFLAGS += -Idrivers/infotm/common/display/implementation/module/controller

