cmake_minimum_required (VERSION 2.8)

get_filename_component (FELIXCOMMON_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)

set (FELIXCOMMON_FOUND TRUE)
set (FELIXCOMMON_INCLUDE_DIRS ${FELIXCOMMON_PREFIX}/include/)
set (FELIXCOMMON_DEFINES)
set (FELIXCOMMON_NAME FelixCommon)
set (FELIXCOMMON_LIBRARIES ${FELIXCOMMON_NAME})

set (FELIXCOMMON_BUILD_KO ${FELIXCOMMON_PREFIX}/FelixCommon_kernel.cmake)
