#! /bin/sh

case "$1" in
	start|"")
		source /etc/profile.d/envsetup.sh
		launcher &
		;;
	stop)
		killall launcher
		killall launcher
		;;
	*)
		echo "Usage: libramain {start|stop}" >&2
		exit 1
		;;
esac

