cmake_minimum_required(VERSION 2.8)

find_package(SimImage REQUIRED) # used in header files
find_package(LinkedList REQUIRED) # used in header files
set (FELIXDG_FOUND TRUE)
find_package(FelixAPI REQUIRED)

get_filename_component(FELIXDG_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
set (FELIXDG_PREFIX ${FELIXDG_PREFIX}/data_generator)



set (FELIXDG_INCLUDE_DIRS 
	${FELIXDG_PREFIX}/include
	${SIMIMAGE_INCLUDE_DIRS}
	${LINKEDLIST_INCLUDE_DIRS}
	${FELIXAPI_INCLUDE_DIRS}
)

set (FELIXDG_DEFINITIONS ${FELIXDG_DEFINITIONS}
	${SIMIMAGE_DEFINITIONS}
	${LINKEDLIST_DEFINITIONS}
	${FELIXAPI_DEFINITIONS}
)

set (FELIXDG_NAME ExtDG)
set (FELIXDG_LIBRARIES ${FELIXDG_NAME}_User)
set (FELIXDG_BUILD_KO ${FELIXDG_PREFIX}/FelixDG_kernel.cmake)

if(NOT CI_BUILD_KERNEL_MODULE)
    set (FELIXDG_LIBRARIES ${FELIXDG_LIBRARIES} ${FELIXDG_NAME}_Kernel)
endif()

if (DEBUG_MODULES)
	message ("FELIXDG_INCLUDE_DIRS=${FELIXDG_INCLUDE_DIRS}")
	message ("FELIXDG_DEFINITIONS=${FELIXDG_DEFINITIONS}")
	message ("FELIXDG_LIBRARIES=${FELIXDG_LIBRARIES}")
endif()

mark_as_advanced(FELIXDG_INCLUDE_DIRS FELIXDG_DEFINITIONS FELIXDG_LIBRARIES FELIXDG_NAME)
