#! /bin/sh

case "$1" in
	start|"")
		modprobe Felix clkRate=198000000
		modprobe ddk_sensor 
		modprobe vench2 g_clk=150000000
		videoboxd
		;;
	stop)
		killall videoboxd
		;;
	*)
		echo "Usage: videobox {start|stop}" >&2
		exit 1
		;;
esac

