#include "spv_language_res.h"


const char *language_en[] = {
    "On",
    "Off",
    "Auto",
    "Ok",
    "Cancel",
    "Delete",
    "Exit",
    "Back",
    "N/A",
    "File",
    "Files",
    "Restore Default",
    "Restore default settings?",

    //video settings
    "Video Settings",
    "Resolution: ",
    "1080FHD",
    "720P 60FPS",
    "720P 30FPS",
    "WVGA",
    "VGA",
    "Loop Recording: ",
    "Rear Camera: ",
    "Picture In Picture: ",
    "WDR: ",
    "EV Compensation: ",
    "+2.0",
    "+1.5",
    "+1.0",
    "+0.5",
    "0",
    "-0.5",
    "-1.0",
    "-1.5",
    "-2.0",
    "Record Audio: ",
    "Date Stamp: ",
    "G-Sensor: ",
    "ADAS: ",
    "ADAS Calibration",
    "Lane center line",
    "Hood top edge line",
    "High",
    "Medium",
    "Low",
    "Plate Number Stamp: ",

    //photo settings
    "Photo Settings",
    "Capture Mode: ",
    "Single",
    "2S Timer",
    "5S Timer",
    "10S Timer",
    "12M",
    "10M",
    "8M",
    "5M",
    "3M",
    "2MHD",
    "1.3M",
    "Sequence: ",
    "Quality: ",
    "Fine",
    "Normal",
    "Economy",
    "Sharpness: ",
    "Strong",
    "Soft",
    "White Balance: ",
    "Daylight",
    "Cloudy",
    "Tungsten",
    "Fluorescent",
    "Color: ",
    "Color",
    "Black&White",
    "Sepia",
    "ISO Limit: ",
    "800",
    "400",
    "200",
    "100",
    "Anti-Shaking: ",

    //playback
    "Playback",

    //setup
    "Setup",
    "Wi-Fi: ",
    "Date / Time",
    "Date Setup",
    "Time Setup",
    "Automatic synchronization: ",
    "Auto Power Off: ",
    "10 Seconds",
    "20 Seconds",
    "30 Seconds",
    "1 Minute",
    "3 Minutes",
    "5 Minutes",
    "10 Minutes",
    "Volume: ",
    "10%",
    "20%",
    "30%",
    "40%",
    "50%",
    "60%",
    "70%",
    "80%",
    "90%",
    "100%",
    "Key Tone: ",
    "Language: ",
    "English",
    "简体中文",
	"繁體中文",
    "Français",
    "Español",
    "Italiano",
    "Português",
    "Deutsch",
    "Русский",
    "Delayed Shutdown: ",
    "Display",
    "Sleep: ",
    "Never",
    "Brightness: ",
    "TV Mode: ",
    "Parking Guard: ",
    "NTSC",
    "PAL",
    "Frequency: ",
    "50Hz",
    "60Hz",
    "IR LED: ",
    "Image Rotation: ",
    "Format",
    "Camera Reset",
    "Plate Number: ",
    "Version: ",

    "AM",
    "PM",
    "Date Setting: M/D/Y",
    "Time Setting",
    "Plate Number",
    //new strings
    "Wireless mode enabled",
    "Pairing for %02d:%02d min",
    "PIN: %s",
    "Put App into Pairing mode and enter PIN",
    "Pairing Stopped",
    "Delete last file?",
    "Delete all files?",
    "Delete progress...",
    "Format progress...",
    "Format SD Error",
    "Reset camera to defaults?",
    "Reset Wi-Fi Settings?",
    "Wireless settings reset",
    "SD Card Empty",
    "SD Card Full",
    "No SD Card",
    "SD Card Error",
    "SD Card Error,Format it",
    "SD Card is preparing",
    "Video Playback Error",
    "USB Connected\nCamera Files Accessible",
    "Camera busy",
    "Reset",
    "Format SD Card?",

};

const char *language_zh[] = {
    "开",
    "关",
    "自动",
    "确认",
    "取消",
    "删除",
    "退出",
    "返回",
    "N/A",
    "文件",
    "文件",
    "恢复默认",
    "恢复默认设置?",

    "录影设置",
    "分辨率: ",
    "1080FHD",
    "720P 60FPS",
    "720P 30FPS",
    "WVGA",
    "VGA",
    "循环录影: ",
    "后置镜头: ",
    "画中画: ",
    "WDR: ",
    "曝光补偿: ",
    "+2.0",
    "+1.5",
    "+1.0",
    "+0.5",
    "0",
    "-0.5",
    "-1.0",
    "-1.5",
    "-2.0",
    "录音: ",
    "时间标签: ",
    "重力感应: ",
    "ADAS: ",
    "ADAS校准",
    "车道中央线",
    "引擎盖上边缘线",
    "高",
    "中",
    "低",
    "车牌: ",


    "拍照设置",
    "拍摄模式: ",
    "单拍",
    "2秒定时",
    "5秒定时",
    "10秒定时",
    "12M",
    "10M",
    "8M",
    "5M",
    "3M",
    "2MHD",
    "1.3M",
    "连拍: ",
    "质量: ",
    "好",
    "一般",
    "经济",
    "锐度: ",
    "强烈",
    "柔和",
    "白平衡: ",
    "日光",
    "阴天",
    "钨丝灯",
    "荧光灯",

    "色彩: ",
    "色彩",
    "黑白",
    "棕褐色",
    "ISO 限制: ",
    "800",
    "400",
    "200",
    "100",
    "防抖动: ",

    "回放",//@@@

    "设置",//@@@
    "无线: ",
    "日期/时间",
    "日期设置",
    "时间设置",
    "自动同步: ",
    "自动关机: ",
    "10秒",
    "20秒",
    "30秒",
    "1分钟",
    "3分钟",
    "5分钟",
    "10分钟",

    "音量: ",
    "10%",
    "20%",
    "30%",
    "40%",
    "50%",
    "60%",
    "70%",
    "80%",
    "90%",
    "100%",
    "按键声音: ",


    "多语言: ",
    "English",
    "简体中文",
	"繁體中文",
    "Français",
    "Español",
    "Italiano",
    "Português",
    "Deutsch",
    "Русский",
    "延时关机: ",
    "显示",
    "睡眠: ",
    "从不",
    "亮度: ",
    "TV模式: ",
    "停车守卫: ",
    "NTSC",
    "PAL",
    "光源频率: ",
    "50Hz",
    "60Hz",
    "补光灯: ",
    "影像倒置: ",
    "格式化",
    "重置相机",
    "车牌号: ",
    "版本: ",

    "AM",
    "PM",
    "日期设置: 月/日/年",
    "时间设置",
    "车牌号",

    //new strings
    "开启无线网络",
    "配对时间剩余%02d:%02d分钟",
    "密码: %06d",
    "进入应用软件配对模式并输入密码",
    "配对停止",
    "是否删除上一个文件?",
    "是否删除所有文件?",
    "正在删除文件...",
    "正在格式化...",
    "格式化出错",
    "是否重置相机为默认值?",
    "是否重置无线网络?",
    "重置无线网络设置",
    "存储卡为空",
    "存储卡已满",
    "未检测到存储卡",
    "存储卡错误",
    "存储卡错误,格式化",
    "存储卡准备中",
    "视频播放错误",
    "USB已连接\n相机数据可以使用",
    "相机忙",
    "重置",
    "是否格式化存储卡?",

};

const char *language_tw[] = {
	"開",
	"關",
	"自動",
	"確認",
	"取消",
	"删除",
	"退出",
	"返回",
    "N/A",
	"文件",
	"文件",
	"恢復默認",
    "恢復默認設置?",

	"錄影設置",
	
	"開辨率: ",
    "1080FHD",
    "720P 60FPS",
    "720P 30FPS",
    "WVGA",
    "VGA",
    "循環錄影: ",
    "後置鏡頭: ",
    "畫中畫: ",    
    "WDR: ",
	"曝光補償: ",
    "+2.0",
    "+1.5",
    "+1.0",
    "+0.5",
    "0",
    "-0.5",
    "-1.0",
    "-1.5",
    "-2.0",
    "錄音: ",
    "時間標籤: ",
    "重力感應: ",
    "ADAS: ",
    "ADAS校准",
    "車道中央線",
    "引擎蓋上邊緣線",
	"高",
	"中",
	"低",
	"車牌: ",


	"拍照設置",
	"拍攝模式: ",
	"單拍",
	"2秒定時",
	"5秒定時",
	"10秒定時",
	"12M",
    "10M",
    "8M",
    "5M",
    "3M",
    "2MHD",
    "1.3M",
    "連拍: ",
    "質量: ",
	"好",
	"一般",
	"經濟",
	"銳度: ",
	"强烈",
	"柔和",
	"白平衡: ",
	"日光",
	"陰天",
	"鎢絲燈",
	"熒光燈",
	
	"色彩: ",
	"色彩",
	"黑白",
	"棕褐色",
	"ISO 限制: ",
	"800",
    "400",
    "200",
    "100",
	"防抖動: ",

	"回放",//@@@

	"設置",//@@@
    "Wi-Fi: ",
	"日期/時間",
	"日期設置",
	"時間設置",
    "自動同步: ",
	"自動關機: ",
	"10秒",
	"20秒",
	"30秒",
	"1分鐘",
	"3分鐘",
	"5分鐘",
	"10分鐘",

	"音量: ",
    "10%",
    "20%",
    "30%",
    "40%",
    "50%",
    "60%",
    "70%",
    "80%",
    "90%",
    "100%",
	"按鍵聲音: ",


	"多語言: ",
    "English",
    "简体中文",
	"繁體中文",
    "Français",
    "Español",
    "Italiano",
    "Português",
    "Deutsch",
    "Русский",
    "延時關機: ",
    "顯示",
    "睡眠: ",
    "從不",
    "亮度: ",
    "TV模式: ",
	"停車守衛: ",
    "NTSC",
    "PAL",
    "光源頻率: ",
    "50Hz",
    "60Hz",
    "補光燈: ",
    "影像倒置: ",
    "格式化",
    "重置相機",
    "車牌號: ",
    "版本: ",
    
    "AM",
    "PM",
	"日期設置: 月/日/年",
	"時間設置",
	"車牌號",

	//new strings
	"開啟無線網絡",
	"配對時間剩余%02d:%02d分鐘",
	"密碼: %06d",
	"進入應用軟件配對模式并輸入密碼",
	"配對停止",
	"是否删除上一個文件?",
	"是否删除所有文件?",
	"正在删除文件...",
	"正在格式化...",
	"格式化出錯",
	"是否重置相機為默認值?",
	"是否重置無綫網絡?",
	"重置無綫網絡設置",
	"存儲卡為空",
	"存儲卡已滿",
	"未检测到存儲卡",
	"存儲卡錯誤",
	"存儲卡錯誤,格式化",
	"存儲卡準備中",
	"視頻播放錯誤",
	"USB已連接\n相機數據可以使用",
	"相機忙",
    "重置",
    "是否格式化存儲卡?",

};

const char *language_fr[] = {
    "Sur",
    "Désactivé",
    "Auto",
    "Ok",
    "Annuler",
    "Effacement",
    "Quitter",
    "Dos",
    "N/A",
    "Fichier",
    "Fichiers",
    "Retour à l'original",
    "Restaurer les paramètres par défaut?",

    "Configurations Vidéo",

    "Résolution: ",
    "1080FHD",
    "720P 60FPS",
    "720P 30FPS",
    "WVGA",
    "VGA",
    "enregistrement en boucle: ",
    "Caméra arrière: ",
    "Picture In Picture:",
    "WDR: ",
    "Compensation de la valeur d'exposition: ",
    "+2.0",
    "+1.5",
    "+1.0",
    "+0.5",
    "0",
    "-0.5",
    "-1.0",
    "-1.5",
    "-2.0",
    "Enregistrement audio: ",
    "timbre dateur: ",
    "G-Sensor: ",
    "ADAS: ",
    "ADAS étalonnage",
    "lane médiane",
    "top Edgeline de capot",
    "Élevé",
    "Moyen",
    "Faible",
    "Plate Nombre Stamp: ",


    "Configurations photo",
    "Mode Capture: ",
    "unique",
    "2S minuterie",
    "5S minuterie",
    "10S minuterie",
    "12M",
    "10M",
    "8M",
    "5M",
    "3M",
    "2MHD",
    "1.3M",
    "Continues: ",
    "qualité: ",
    "amende",
    "normal",
    "économie",
    "Netteté: ",
    "fort",
    "doux",
    "Équilibre des blancs: ",
    "lumière du jour",
    "nuageux",
    "tungstène",
    "fluorescent",

    "Couleur: ",
    "Couleur",
    "Noir Blanc",
    "sépia",
    "Limite ISO: ",
    "800",
    "400",
    "200",
    "100",
    "Anti-Shaking: ",

    "Lecture",//@@@

    "Configuration",//@@@
    "Wi-Fi: ",
    "Date/Heure",
    "Réglage de la date",
    "Réglage de l'heure",
    "Synchronisation automatique: ",
    "Auto Power Off: ",
    "10 secondes",
    "20 secondes",
    "30 secondes",
    "1 Minute",
    "3 Minutes",
    "5 Minutes",
    "10 Minutes",

    "Volume: ",
    "10%",
    "20%",
    "30%",
    "40%",
    "50%",
    "60%",
    "70%",
    "80%",
    "90%",
    "100%",
    "Tonalité: ",


    "langue: ",
    "English",
    "简体中文",
	"繁體中文",
    "Français",
    "Español",
    "Italiano",
    "Português",
    "Deutsch",
    "Русский",
    "Delayed Shutdown: ",
    "exposition",
    "sommeil: ",
    "jamais",
    "Luminosité: ",
    "Mode TV: ",
    "Parking Surveillé: ",
    "NTSC",
    "PAL",
    "fréquence: ",
    "50Hz",
    "60Hz",
    "LED IR: ",
    "rotation de l'image: ",
    "Format",
    "Réinitialiser la caméra",
    "Immatriculation: ",
    "Version: ",

    "AM",
    "PM",
    "Réglage de la date: M/D/Y",
    "réglage de l'heure",
    "Immatriculation",

    //new strings
    "Mode sans fil active",
    "Pairing pour %02d:%02d min",
    "PIN: %06d",
    "Mettez App en mode d'appairage et de saisir le code PIN",
    "Jumelage Stopped",
    "effacer dernier fichier?",
    "Effacer tous les fichier?",
    "Effacer progrès...",
    "Format progrès...",
    "Format SD erreur",
    "réinitialiser l'appareil photo aux valeurs par défaut?",
    "Réinitialiser les paramètres Wi-Fi?",
    "Réinitialiser les paramètres sans fil",
    "Carte SD vide",
    "Carte SD pleine",
    "Pas de carte SD",
    "SD erreur de carte",
    "SD Card Error, formater",
    "SD Card prépare",
    "Erreur lecture de vidéos",
    "USB connecté\nCaméra fichiers accessibles",
    "caméra occupés",
    "réinitialiser",
    "Formater la carte SD?",


};

const char *language_es[] = {
    "En",
    "Apagado",
    "Auto",
    "Ok",
    "Cancelar",
    "Eliminar",
    "Salir",
    "Espalda",
    "N/A",
    "Archivo",
    "Archivos",
    "Restaurar valores predeterminados",
    "Restaurar la configuración predeterminada?",

    "Configuración de Vídeo",

    "Resolución: ",
    "1080FHD",
    "720P 60FPS",
    "720P 30FPS",
    "WVGA",
    "VGA",
    "grabación en bucle: ",
    "Cámara trasera: ",
    "Imagen en imagen:",
    "WDR: ",
    "Compensación del valor de exposición: ",
    "+2.0",
    "+1.5",
    "+1.0",
    "+0.5",
    "0",
    "-0.5",
    "-1.0",
    "-1.5",
    "-2.0",
    "Grabar Audio: ",
    "sello de la fecha: ",
    "G-Sensor: ",
    "ADAS: ",
    "ADAS calibración",
    "carril central",
    "top Edgeline campana",
    "alto",
    "medio",
    "bajo",
    "Número de Placa de sellos: ",


    "Configuración de foto",
    "Modo de captura: ",
    "Individual",
    "temporizador 2S",
    "temporizador 5S",
    "temporizador 10S",
    "12M",
    "10M",
    "8M",
    "5M",
    "3M",
    "2MHD",
    "1.3M",
    "Continuo: ",
    "Calidad: ",
    "multa",
    "normal",
    "economía",
    "Nitidez: ",
    "fuerte",
    "suave",
    "Balance de blancos: ",
    "luz",
    "nublado",
    "tungsteno",
    "fluorescente",

    "color: ",
    "color",
    "Blanco y Negro",
    "sepia",
    "Límite ISO: ",
    "800",
    "400",
    "200",
    "100",
    "Anti-Sacudida: ",

    "Reproducción",//@@@

    "Configuración",//@@@
    "Wi-Fi: ",
    "Fecha/Hora",
    "Fecha de instalación",
    "Configuración de la hora",
    "Sincronización automática: ",
    "Apagado Automático: ",
    "10 segundos",
    "20 segundos",
    "30 segundos",
    "1 Minuto",
    "3 Minutos",
    "5 Minutos",
    "10 Minutos",

    "Volume: ",
    "10%",
    "20%",
    "30%",
    "40%",
    "50%",
    "60%",
    "70%",
    "80%",
    "90%",
    "100%",
    "Tono De Las Teclas: ",


    "Lengua: ",
    "English",
    "简体中文",
	"繁體中文",
    "Français",
    "Español",
    "Italiano",
    "Português",
    "Deutsch",
    "Русский",
    "Delayed Shutdown: ",
    "visualización",
    "sueño: ",
    "Nunca",
    "Brillo: ",
    "Modo TV: ",
    "Aparcamiento Vigilado: ",
    "NTSC",
    "PAL",
    "Frecuencia: ",
    "50Hz",
    "60Hz",
    "IR LED: ",
    "rotación de imagen: ",
    "Formato",
    "Restablecer cámara",
    "Número de la placa: ",
    "Versión: ",

    "AM",
    "PM",
    "Ajuste de la fecha: M/D/A",
    "ajuste del tiempo",
    "Número de la placa",

    //new strings
    "Modo inalámbrico habilitado",
    "El emparejamiento de %02d:%02d min",
    "PIN: %06d",
    "Ponga App en modo de sincronización e introduzca el PIN",
    "Maridaje Detenido",
    "Eliminar último archivo?",
    "Elimine todos los archivos?",
    "Eliminar el progreso...",
    "Formato de Progreso...",
    "Formato SD de error",
    "Restablecer los valores predeterminados de la cámara?",
    "Restablecer configuración de Wi-Fi?",
    "Restablecen los ajustes inalámbricos",
    "Tarjeta SD vacía",
    "Tarjeta SD completa",
    "No hay tarjeta SD",
    "Error de la tarjeta SD",
    "Tarjeta SD de error, formatearlo",
    "SD Card está preparando",
    "Error de reproducción de vídeo",
    "USB conectados\nArchivos de Cámara Accesible",
    "cámara ocupada",
    "reajustar",
    "Formatear tarjeta SD?",


};

const char *language_it[] = {
    "Su",
    "Spegnimento",
    "Auto",
    "Ok",
    "Cancellare",
    "Elimina",
    "Uscita",
    "Indietro",
    "N/A",
    "File",
    "File",
    "Ripristino predefinito",
    "Ripristina le impostazioni di default?",

    "Impostazioni Video",

    "Risoluzione: ",
    "1080FHD",
    "720P 60FPS",
    "720P 30FPS",
    "WVGA",
    "VGA",
    "registrazione del ciclo: ",
    "Videocamera posteriore: ",
    "Picture In Picture",
    "WDR: ",
    "Compensazione valore esposizione: ",
    "+2.0",
    "+1.5",
    "+1.0",
    "+0.5",
    "0",
    "-0.5",
    "-1.0",
    "-1.5",
    "-2.0",
    "Registrazione audio: ",
    "Date Stamp: ",
    "G-Sensor: ",
    "ADAS: ",
    "ADAS calibratura",
    "corsia centrale",
    "top Edgeline cofano",
    "Alta",
    "Media",
    "Bassa",
    "Targa Stamp: ",


    "Impostazioni Foto",
    "Capture Mode: ",
    "Singola",
    "timer 2S",
    "timer 5S",
    "timer 10S",
    "12M",
    "10M",
    "8M",
    "5M",
    "3M",
    "2MHD",
    "1.3M",
    "Contínuo: ",
    "Qualità: ",
    "bene",
    "normale",
    "economia",
    "Nitidezza: ",
    "forte",
    "morbido",
    "Bilanciamento del bianco: ",
    "luce del giorno",
    "nuvoloso",
    "tungsteno",
    "fluorescente",

    "Colore: ",
    "Colore",
    "Nero Bianco",
    "nero di seppia",
    "Limite ISO: ",
    "800",
    "400",
    "200",
    "100",
    "Anti-Shaking: ",

    "Riproduzione",//@@@

    "Configurazione",//@@@
    "Wi-Fi: ",
    "Data/Ora",
    "Data Setup",
    "Impostazione ora",
    "Sincronizzazione automatica: ",
    "Spegnimento automatico: ",
    "10 secondi",
    "20 secondi",
    "30 secondi",
    "1 Minuti",
    "3 Minuti",
    "5 Minuti",
    "10 Minuti",

    "Volume: ",
    "10%",
    "20%",
    "30%",
    "40%",
    "50%",
    "60%",
    "70%",
    "80%",
    "90%",
    "100%",
    "Tono Dei Tasti: ",


    "Lingua: ",
    "English",
    "简体中文",
	"繁體中文",
    "Français",
    "Español",
    "Italiano",
    "Português",
    "Deutsch",
    "Русский",
    "Arresto ritardato: ",
    "display",
    "sonno: ",
    "mai",
    "Luminosità: ",
    "Modalità TV: ",
    "Parcheggio Custodito: ",
    "NTSC",
    "PAL",
    "Frequenza: ",
    "50Hz",
    "60Hz",
    "LED IR: ",
    "rotazione immagine: ",
    "Format",
    "Reset telecamera",
    "Targa: ",
    "Versione: ",

    "AM",
    "PM",
    "Impostare la data: M/D/Y",
    "impostazione del tempo",
    "Targa",

    //new strings
    "Modalità wireless abilitata",
    "Pairing per %02d:%02d min",
    "PIN: %06d",
    "Mettere App in modalità di abbinamento e inserire il PIN",
    "Abbinamento Arrestato",
    "Eliminare ultimo file?",
    "Eliminare tutti i file?",
    "Elimina corso...",
    "Formato Progress...",
    "Format SD Error",
    "Ripristina fotocamera ai valori di default?",
    "Ripristina impostazioni Wi-Fi?",
    "Ripristinate le impostazioni wireless",
    "Scheda SD vuota",
    "Scheda SD piena",
    "No SD Card",
    "Errore della scheda SD",
    "Errore scheda SD, formattarla",
    "SD sta preparando",
    "Errore riproduzione video",
    "USB collegato\nCamera i file accessibili",
    "fotocamera occupato",
    "reset",
    "Formatta scheda SD?",

};

const char *language_pt[] = {
    "Em",
    "Encerramento",
    "Auto",
    "Ok",
    "Cancelar",
    "Apagar",
    "Saída",
    "de volta",
    "N/A",
    "Arquivo",
    "Arquivos",
    "Restaurar padrão",
    "Restaurar a configuração original?",

    "Definições de Vídeo",

    "Resoluçã: ",
    "1080FHD",
    "720P 60FPS",
    "720P 30FPS",
    "WVGA",
    "VGA",
    "Gravação de Loop: ",
    "Câmera traseira: ",
    "Picture In Picture",
    "WDR: ",
    "Compensação do valor de exposição: ",
    "+2.0",
    "+1.5",
    "+1.0",
    "+0.5",
    "0",
    "-0.5",
    "-1.0",
    "-1.5",
    "-2.0",
    "Record Audio: ",
    "data do Selo: ",
    "G-Sensor: ",
    "ADAS: ",
    "ADAS calibragem",
    "lane central",
    "hood topo Edgeline",
    "Alta",
    "Média",
    "Baixa",
    "Placa Número de Carimbos: ",


    "DEFINIÇÕES DE FOTO",
    "Modo de captura: ",
    "Single",
    "2S temporizador",
    "5S temporizador",
    "10S temporizador",
    "12M",
    "10M",
    "8M",
    "5M",
    "3M",
    "2MHD",
    "1.3M",
    "Contínuo: ",
    "qualidade: ",
    "Bem",
    "normal",
    "economia",
    "Nitidez: ",
    "forte",
    "suave",
    "Equilíbrio de brancos: ",
    "luz do dia",
    "nublado",
    "tungstênio",
    "fluorescente",

    "Cor: ",
    "Cor",
    "Preto Branco",
    "sépia",
    "Limite ISO: ",
    "800",
    "400",
    "200",
    "100",
    "Anti-Agitando: ",

    "Reprodução",//@@@

    "Configuração",//@@@
    "Wi-Fi: ",
    "Data/Hora",
    "data Setup",
    "Configuração tempo",
    "Sincronização automática: ",
    "Auto Power Off: ",
    "10 segundo",
    "20 segundo",
    "30 segundo",
    "1 Minuto",
    "3 Minutos",
    "5 Minutos",
    "10 Minutos",

    "Volume: ",
    "10%",
    "20%",
    "30%",
    "40%",
    "50%",
    "60%",
    "70%",
    "80%",
    "90%",
    "100%",
    "Tom Key: ",


    "língua: ",
    "English",
    "简体中文",
	"繁體中文",
    "Français",
    "Español",
    "Italiano",
    "Português",
    "Deutsch",
    "Русский",
    "Shutdown adiada: ",
    "exibição",
    "Dorme: ",
    "nem",
    "brilho: ",
    "Modo TV: ",
    "Parque com vigilância: ",
    "NTSC",
    "PAL",
    "freqüência: ",
    "50Hz",
    "60Hz",
    "LED IR: ",
    "rotação de imagem: ",
    "Formato",
    "redefinição de câmara",
    "Número Da Placa: ",
    "versão: ",

    "AM",
    "PM",
    "Data Ambiente: M/D/Y",
    "definição do tempo",
    "Número Da Placa",

    //new strings
    "Modo wireless ativado",
    "O emparelhamento para %02d:%02d min",
    "PIN: %06d",
    "Coloque App no modo de emparelhamento e introduza PIN",
    "O emparelhamento Parou",
    "Apagar último arquivo?",
    "Exclua todos os arquivos?",
    "Excluir progresso...",
    "Formato Progresso...",
    "Format SD erro",
    "Redefinir câmera para os padrões?",
    "Redefinir Ajustes de Wi-Fi?",
    "Redefinir as configurações sem fio",
    "Cartão SD vazio",
    "Cartão SD cheio",
    "Sem cartão SD",
    "Erro no cartão SD",
    "Erro no cartão SD, formate-o",
    "Cartão SD está a preparar",
    "Erro de reprodução de vídeo",
    "USB conectado\nArquivos Camera Accessible",
    "câmera ocupado",
    "restabelecer",
    "SD Card Format?",

};

const char *language_de[] = {
    "Auf",
    "Aus",
    "Auto",
    "Ok",
    "Stornieren",
    "Löschen",
    "Ausgang",
    "Zurück",
    "N/A",
    "Datei",
    "Dateien",
    "Standard wiederherstellen",
    "Standardeinstellungen wiederherstellen?",

    "Video-Einstellungen",

    "Auflösung: ",
    "1080FHD",
    "720P 60FPS",
    "720P 30FPS",
    "WVGA",
    "VGA",
    "Loop-Aufnahme: ",
    "Rückfahrkamera:",
    "Bild in Bild",
    "WDR: ",
    "Belichtungswert kompensation: ",
    "+2.0",
    "+1.5",
    "+1.0",
    "+0.5",
    "0",
    "-0.5",
    "-1.0",
    "-1.5",
    "-2.0",
    "Audio aufnehmen: ",
    "Datumsstempel: ",
    "G-Sensor: ",
    "ADAS: ",
    "ADAS kalibrierung",
    "Fahrspurmittel",
    "Motorhaube Edgeline",
    "Hoch",
    "Mittel",
    "Niedrig",
    "Kennzeichen Stamp: ",


    "Foto Einstellungen",
    "Aufnahmemodus: ",
    "Einzel",
    "2S-Timer",
    "5S-Timer",
    "10S-Timer",
    "12M",
    "10M",
    "8M",
    "5M",
    "3M",
    "2MHD",
    "1.3M",
    "Kontinuierlich: ",
    "Qualität: ",
    "Geldbuße",
    "normal",
    "Wirtschaft",
    "Schärfe: ",
    "stark",
    "weich",
    "Weißabgleich: ",
    "Tageslicht",
    "bewölkt",
    "Wolfram",
    "fluoreszierend",

    "Farbe: ",
    "Farbe",
    "Schwarz-Weiss",
    "Sepia",
    "ISO-Limit: ",
    "800",
    "400",
    "200",
    "100",
    "Anti-Shaking: ",

    "Wiedergabe",//@@@

    "Setup",//@@@
    "Wi-Fi: ",
    "Datum/Uhrzeit",
    "Datum-Setup",
    "Zeiteinstellung",
    "Automatische synchronisation: ",
    "Auto Power Off: ",
    "10 Sekunden",
    "20 Sekunden",
    "30 Sekunden",
    "1 Minute",
    "3 Minuten",
    "5 Minuten",
    "10 Minuten",

    "Volume: ",
    "10%",
    "20%",
    "30%",
    "40%",
    "50%",
    "60%",
    "70%",
    "80%",
    "90%",
    "100%",
    "Tastenton: ",


    "Sprache: ",
    "English",
    "简体中文",
	"繁體中文",
    "Français",
    "Español",
    "Italiano",
    "Português",
    "Deutsch",
    "Русский",
    "Verzögerte Abschaltung: ",
    "Anzeige",
    "schlafen: ",
    "nie",
    "Helligkeit: ",
    "TV-Modus: ",
    "Bewachter Parkplatz: ",
    "NTSC",
    "PAL",
    "Frequenz: ",
    "50Hz",
    "60Hz",
    "IR LED: ",
    "Bilddrehung: ",
    "Format",
    "Kamera-Reset",
    "Kennzeichen: ",
    "Version: ",

    "AM",
    "PM",
    "Datum Einstellung: M/D/Y",
    "Zeiteinstellung",
    "Kennzeichen",

    //new strings
    "Wireless-Modus aktiviert",
    "Pairing für %02d:%02d min",
    "PIN: %06d",
    "Setzen App in den Pairing-Modus und geben Sie PIN",
    "Pairing Stopped",
    "Löschen letzten Datei?",
    "Löschen Sie alle Dateien?",
    "Fortschritte zu löschen...",
    "Format Fortschritt...",
    "Format SD Error",
    "Zurücksetzen der Kamera auf die Standardwerte?",
    "Zurücksetzen Wi-Fi-Einstellungen?",
    "Wireless-Einstellungen zurücksetzen",
    "SD-Karte Leere",
    "SD-Karte voll",
    "Keine SD-Karte",
    "SD-Kartenfehler",
    "SD-Kartenfehler, formatieren Sie",
    "SD-Karte bereitet",
    "Video-Wiedergabe Error",
    "USB angeschlossen\nKamera-Dateizugriff",
    "Kamera beschäftigt",
    "rücksetzen",
    "Format SD Card?",

};

const char *language_ru[] = {
    "На",
    "от",
    "автоматический",
    "Хорошо",
    "отменить",
    "удалять",
    "выход",
    "назад",
    "N/A",
    "файл",
    "файлы",
    "Сброс настроек",
    "Восстановление настроек по умолчанию?",

    "Параметры видео",

    "разрешение: ",
    "1080FHD",
    "720P 60FPS",
    "720P 30FPS",
    "WVGA",
    "VGA",
    "Запись петли: ",
    "Камера заднего вида:",
    "Картинка в картинке:",
    "WDR: ",
    "Компенсация экспозиции: ",
    "+2.0",
    "+1.5",
    "+1.0",
    "+0.5",
    "0",
    "-0.5",
    "-1.0",
    "-1.5",
    "-2.0",
    "Запись аудио: ",
    "Штамп даты: ",
    "G-сенсор: ",
    "ADAS: ",
    "ADAS калибровка",
    "переулок осевой",
    "капот сверху Edgeline",
    "высокая",
    "среда",
    "низкий",
    "Номерных Пунш: ",


    "установка фото",
    "Режим съемки: ",
    "один",
    "2S таймер",
    "5S таймер",
    "10S таймер",
    "12M",
    "10M",
    "8M",
    "5M",
    "3M",
    "2MHD",
    "1.3M",
    "непрерывный: ",
    "Качество: ",
    "отлично",
    "нормальный",
    "экономика",
    "четкость: ",
    "сильный",
    "мягкий",
    "баланс белого: ",
    "дневной свет",
    "облачный",
    "вольфрам",
    "флуоресцентный",

    "Цвет: ",
    "Цвет",
    "Черно-Белый",
    "сепия",
    "предел ISO: ",
    "800",
    "400",
    "200",
    "100",
    "Анти-встряхивания: ",

    "воспроизведение",//@@@

    "Установить",//@@@
    "Wi-Fi: ",
    "Дата/время",
    "Дата установки",
    "Время установки",
    "Автоматическая синхронизация: ",
    "Автоматическое Выключение: ",
    "10 секунд",
    "20 секунд",
    "30 секунд",
    "1 минута",
    "3 минуты",
    "5 минут",
    "10 минут",

    "Объем: ",
    "10%",
    "20%",
    "30%",
    "40%",
    "50%",
    "60%",
    "70%",
    "80%",
    "90%",
    "100%",
    "Тональность: ",


    "язык: ",
    "English",
    "简体中文",
	"繁體中文",
    "Français",
    "Español",
    "Italiano",
    "Português",
    "Deutsch",
    "Русский",
    "Задержка выключения: ",
    "дисплей",
    "Спать: ",
    "никогда",
    "Яркость: ",
    "ТВ режим: ",
    "Охраняемая стоянка: ",
    "NTSC",
    "PAL",
    "Частота: ",
    "50Hz",
    "60Hz",
    "ИК-светодиод: ",
    "поворот изображения: ",
    "Формат",
    "сброс камеры",
    "Номерной Знак: ",
    "Версия: ",

    "AM",
    "PM",
    "Дата установки: М/Д/Г",
    "установка времени",
    "Номерной Знак",

    //new strings
    "Включен беспроводной режим",
    "Сопряжение для %02d:%02d мин",
    "PIN-код: %06d",
    "Положите приложение в режиме сопряжения и введите PIN-код",
    "Сопряжение Остановился",
    "Удалить последний файл?",
    "Удалить все файлы?",
    "Удалить прогресс...",
    "Формат Прогресс...",
    "Форматирование SD Ошибка",
    "Сброс камеры на значения по умолчанию?",
    "Сбросить настройки Wi-Fi?",
    "Сбросить настройки беспроводной",
    "SD-карта Пусто",
    "SD-карта полная",
    "Нет SD-карты",
    "SD-карта Ошибка",
    "Ошибка SD-карты, отформатировать его",
    "Карта SD готовится",
    "Воспроизведение видео Ошибка",
    "USB подключен\nКамера доступа к файлам",
    "камера занята",
    "сброс",
    "Формат SD-карты?",


};

const char **g_language = language_en;

int GetStringId(const char *value)
{
    int i, id = 0;
    for(i = 0; i < STRING_END; i ++)
    {
        if(!strcasecmp(value, language_en[i]))
        {
            id = i + 1;
            break;
        }
    }
    return id;
}

