#! /bin/sh

case "$1" in
	start|"")
		modprobe ddk_sensor
		modprobe hx280enc_265
		modprobe vdec_g1
		modprobe vdec_g2
		modprobe Felix
		modprobe hx280enc_h1
		videoboxd
		;;
	stop)
		killall videoboxd
		;;
	*)
		echo "Usage: videobox {start|stop}" >&2
		exit 1
		;;
esac

