# Copyright 2013 Google Inc. All Rights Reserved.
#
# Makefile for VP9 decoder control code.

# list of used sourcefiles
VP9_SRCS := software/source/vp9/vp9decapi.c \
            software/source/vp9/vp9hwd_asic.c \
            software/source/vp9/vp9hwd_bool.c \
            software/source/vp9/vp9hwd_buffer_queue.c \
            software/source/vp9/vp9hwd_decoder.c \
            software/source/vp9/vp9hwd_headers.c \
            software/source/vp9/vp9hwd_output.c \
            software/source/vp9/vp9hwd_probs.c \
            software/source/vp9/vp9_modecontext.c \
            software/source/vp9/vp9_entropymode.c \
            software/source/vp9/vp9_entropymv.c \
            software/source/vp9/vp9_treecoder.c \
            software/source/vp9/vp9_modecont.c
