#                                                    
#  Makefile for the input core drivers.              
#                                                    
#  Each configuration option enables a list of files.
#                                                    
obj-$(CONFIG_IMAPX15_INPUT)   += keyboard/                                 
#obj-y   += touchscreen/                              

