#ifndef COMMON_INFT_ACTION_H
#define COMMON_INFT_ACTION_H

typedef enum {
    INFT_ACTION_MODE_MIN=0,
    INFT_ACTION_MODE_PREVIEW = INFT_ACTION_MODE_MIN,
    INFT_ACTION_MODE_PLAYBACK,
    INFT_ACTION_MODE_PLAYBACK_PAUSE,
    INFT_ACTION_MODE_PLAYBACK_RESUME,
    INFT_ACTION_MODE_RECORD,
    INFT_ACTION_MODE_RECORD_REAR,
    INFT_ACTION_MODE_DISPPIC,
    INFT_ACTION_MODE_SINGLE,
    INFT_ACTION_MODE_BURST,
    INFT_ACTION_MODE_AUDIOPLAY,
    INFT_ACTION_MODE_PLAYBACK_PREPARE,
    INFT_ACTION_MODE_MAX,

}INFT_ACTION_MODE;

typedef enum{
    ACTION_STATE_BEGIN,
	ACTION_STATE_END,
	ACTION_STATE_ERROR,
	ACTION_STATE_ERROR_SD_FULL,
	ACTION_STATE_ERROR_NO_SD,
	ACTION_STATE_MAX,
}ENUM_ACITON_STATE;

typedef enum{
    INFT_CAMERA_FRONT=0,
	INFT_CAMERA_REAR=1,
	INFT_CAMERA_FRONT_REAR=2,
	INFT_CAMERA_REAR_FRONT,
	INFT_CAMERA_MAX,
}ENUM_INFT_CAMERA;



typedef struct Inft_Action_Attr{
	ENUM_INFT_CAMERA camera;
    INFT_ACTION_MODE mode;   
    ENUM_ACITON_STATE state;
    unsigned int enable;

    union
    {
        char startTime[256];
    }args;

    struct Inft_Action_Attr* next;

}Inft_Action_Attr;

#endif
